// Real, publicly-recorded auction results for historically/culturally significant items.
// 50 items across art, manuscripts, fossils, comics, sports, music, jewelry, watches, etc.
// Each hammer price is from the auction house's official press release or major-outlet coverage.
//
// Image strategy: Wikimedia Commons Special:FilePath URLs (302 redirect to upload.wikimedia.org).
// All photos are public-domain or freely-licensed. Where the actual auctioned object isn't on
// Commons, we use a related period/person/genre photo and mark `illustrative: true`.

export type AuctionCategory =
  | "manuscript"
  | "book"
  | "fossil"
  | "space"
  | "tech"
  | "comic"
  | "film"
  | "music"
  | "sports"
  | "coin"
  | "stamp"
  | "gem"
  | "watch"
  | "drink"
  | "art"
  | "korea"
  | "history";

export type AuctionImage = {
  src: string;
  source: "Wikimedia" | "NASA" | "LoC" | "Smithsonian" | "AuctionHousePress";
  license: "PD" | "CC0" | "CC-BY" | "CC-BY-SA" | "PressUse";
  credit: string;
  sourceUrl: string;
  illustrative?: boolean;
};

export type AuctionItem = {
  id: string;
  category: AuctionCategory;
  ko: { title: string; blurb: string; story: string };
  en: { title: string; blurb: string; story: string };
  hammerUSD: number;
  year: number;
  house: string;
  sourceUrl: string;
  emoji: string;
  image: AuctionImage;
};

const wm = (filename: string, width = 900) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${filename}?width=${width}`;

export const ITEMS: AuctionItem[] = [
  // ─────────── ART ───────────
  {
    id: "salvator-mundi",
    category: "art",
    ko: {
      title: "다 빈치 ‘살바토르 문디(Salvator Mundi)’",
      blurb: "예수가 한 손으로 축복하고 다른 손에 수정구를 든 그림. 다 빈치가 그렸다고 추정되는 단 30점 중 하나.",
      story: "사상 최고가 미술품. 사우디 왕세자가 낙찰받았다는 설이 유력. 진위 논란은 여전히 진행 중.",
    },
    en: {
      title: "Da Vinci’s ‘Salvator Mundi’",
      blurb: "Christ holding a crystal orb, blessing with the other hand — one of fewer than 30 paintings attributed to Leonardo.",
      story: "The most expensive painting ever sold. Reportedly bought by the Saudi crown prince. Authenticity debate still rages.",
    },
    hammerUSD: 450_312_500,
    year: 2017,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-6110563",
    emoji: "🖼️",
    image: {
      src: wm("Leonardo_da_Vinci%2C_Salvator_Mundi%2C_c.1500%2C_oil_on_walnut%2C_45.4_%C3%97_65.6_cm.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Leonardo_da_Vinci,_Salvator_Mundi,_c.1500,_oil_on_walnut,_45.4_%C3%97_65.6_cm.jpg",
    },
  },
  {
    id: "warhol-marilyn",
    category: "art",
    ko: {
      title: "워홀 ‘Shot Sage Blue Marilyn’",
      blurb: "1964년에 만들어진 마릴린 먼로의 5점 실크스크린 시리즈 중 ‘세이지 블루’ 한 점.",
      story: "20세기 이후 작품 중 최고가. ‘Shot’이라는 이름은 한 여성이 캔버스에 총을 쏜 사건에서 왔다.",
    },
    en: {
      title: "Warhol — ‘Shot Sage Blue Marilyn’",
      blurb: "From the 1964 ‘Shot Marilyns’ silkscreen series — five Marilyn Monroe portraits in different background colors.",
      story: "The most expensive 20th-century work ever auctioned. The ‘Shot’ name comes from a woman who fired a pistol through the canvases.",
    },
    hammerUSD: 195_040_000,
    year: 2022,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-6371619",
    emoji: "🎨",
    image: {
      src: wm("Andy-Warhol-and-Johnson-Twins-by-Cecil-Beaton-1969.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: Cecil Beaton, 1969 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Andy-Warhol-and-Johnson-Twins-by-Cecil-Beaton-1969.jpg",
      illustrative: true,
    },
  },
  {
    id: "picasso-femmes-dalger",
    category: "art",
    ko: {
      title: "피카소 ‘알제의 여인들 (Version O)’",
      blurb: "들라크루아의 동명 작품에서 영감을 받은 15점 시리즈의 마지막 한 점.",
      story: "당시 미술품 경매 사상 최고가. 카타르 왕족이 낙찰받은 것으로 추정.",
    },
    en: {
      title: "Picasso — ‘Les Femmes d’Alger (Version O)’",
      blurb: "The final canvas in a 15-painting series Picasso made in homage to Delacroix.",
      story: "An auction record at the time. Reportedly bought by the Qatari royal family.",
    },
    hammerUSD: 179_365_000,
    year: 2015,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-5895070",
    emoji: "🎨",
    image: {
      src: wm("Portrait_de_Picasso_par_Pierre_de_Belay_1910.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Pierre de Belay portrait of Picasso, 1910 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Portrait_de_Picasso_par_Pierre_de_Belay_1910.jpg",
      illustrative: true,
    },
  },
  {
    id: "modigliani-nu-couche",
    category: "art",
    ko: {
      title: "모딜리아니 ‘누드 (Nu Couché)’",
      blurb: "1917~1918년에 그린 누드 시리즈 중 가장 도발적인 한 점.",
      story: "당시 모딜리아니 작품으로는 신기록. 류이첸이라는 중국 컬렉터가 낙찰받았다.",
    },
    en: {
      title: "Modigliani — ‘Nu Couché’",
      blurb: "One of the most provocative nudes from his 1917–18 series.",
      story: "A then-record for Modigliani. Bought by Chinese collector Liu Yiqian.",
    },
    hammerUSD: 170_405_000,
    year: 2015,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-5934149",
    emoji: "🎨",
    image: {
      src: wm("Modigliani_-_Nu_couch%C3%A9.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Modigliani_-_Nu_couché.jpg",
    },
  },
  {
    id: "basquiat-untitled-skull",
    category: "art",
    ko: {
      title: "바스키아 ‘무제(해골)’ (1982)",
      blurb: "스물한 살의 바스키아가 그린 가장 강렬한 해골 캔버스 중 하나.",
      story: "낙찰자는 일본 사업가 마에자와 유사쿠. 그는 이 그림을 사고 트위터에 “기뻐 죽겠다”고 적었다.",
    },
    en: {
      title: "Basquiat — ‘Untitled (Skull)’ (1982)",
      blurb: "One of the most ferocious skull canvases by 21-year-old Basquiat.",
      story: "Bought by Japanese entrepreneur Yusaku Maezawa, who tweeted ‘I am happy to be the proud new owner.’",
    },
    hammerUSD: 110_487_500,
    year: 2017,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2017/contemporary-art-evening-auction-n09762.html",
    emoji: "💀",
    image: {
      src: wm("Jean-Michel_Basquiat_passport.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Basquiat passport photo (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jean-Michel_Basquiat_passport.jpg",
      illustrative: true,
    },
  },
  {
    id: "van-gogh-dr-gachet",
    category: "art",
    ko: {
      title: "반 고흐 ‘닥터 가셰의 초상’",
      blurb: "반 고흐가 자살하기 6주 전에 그린 자신의 주치의 초상.",
      story: "낙찰자는 일본 사업가 사이토 료에이. 그는 이 그림과 함께 묻히고 싶다고 말했다.",
    },
    en: {
      title: "Van Gogh — ‘Portrait of Dr. Gachet’",
      blurb: "Van Gogh painted his own physician six weeks before his suicide.",
      story: "Bought by Japanese tycoon Ryoei Saito, who said he wanted to be cremated with the painting.",
    },
    hammerUSD: 82_500_000,
    year: 1990,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/lot/lot-2294574",
    emoji: "🎨",
    image: {
      src: wm("Vincent_van_Gogh_-_Dr_Paul_Gachet_-_Google_Art_Project.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Google Art Project / Wikimedia (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Dr_Paul_Gachet_-_Google_Art_Project.jpg",
    },
  },
  {
    id: "munch-scream",
    category: "art",
    ko: {
      title: "뭉크 ‘절규’ (파스텔 버전)",
      blurb: "뭉크가 1895년에 직접 그린 4가지 ‘절규’ 중 유일하게 개인 소유였던 파스텔 버전.",
      story: "뒷면에 뭉크의 시(詩)가 남겨져 있다: ‘자연을 가로지르는 거대한 비명을 들었다.’",
    },
    en: {
      title: "Munch — ‘The Scream’ (Pastel)",
      blurb: "The only one of four ‘Scream’ versions Munch made that was in private hands — a pastel from 1895.",
      story: "On the back, Munch wrote a poem: ‘I heard the immense, infinite scream of nature.’",
    },
    hammerUSD: 119_922_500,
    year: 2012,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2012/impressionist-modern-art-evening-sale-n08853.html",
    emoji: "😱",
    image: {
      src: wm("The_Scream_Pastel.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Edvard Munch, 1895 (Wikimedia, public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Scream_Pastel.jpg",
    },
  },
  {
    id: "klimt-lady-with-fan",
    category: "art",
    ko: {
      title: "클림트 ‘부채를 든 여인’",
      blurb: "클림트가 1918년 사망할 때까지 이젤 위에 두고 있던 마지막 작품.",
      story: "유럽 미술품 경매 사상 최고가. 화가의 아틀리에에서 미완성으로 남았던 작품이다.",
    },
    en: {
      title: "Klimt — ‘Lady with a Fan’",
      blurb: "The painting still on Klimt’s easel when he died in 1918.",
      story: "A European auction record. It was unfinished when Klimt died.",
    },
    hammerUSD: 108_408_000,
    year: 2023,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2023/modern-evening-auction/gustav-klimt-dame-mit-facher",
    emoji: "🪭",
    image: {
      src: wm("Gustav_Klimt_-_Dame_mit_F%C3%A4cher.jpeg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Gustav_Klimt_-_Dame_mit_Fächer.jpeg",
    },
  },
  {
    id: "banksy-love-is-in-the-bin",
    category: "art",
    ko: {
      title: "뱅크시 ‘사랑은 쓰레기통에 있다’",
      blurb: "낙찰 직후 액자 안 분쇄기에 의해 절반이 자동 파쇄된 그 그림.",
      story: "원래 작품명은 ‘풍선을 든 소녀’였지만, 사건 직후 ‘사랑은 쓰레기통에 있다’로 정식 개명되었다. 이후 가격은 3배로 뛰었다.",
    },
    en: {
      title: "Banksy — ‘Love is in the Bin’",
      blurb: "The painting that half-shredded itself in front of the audience seconds after the hammer fell.",
      story: "Originally titled ‘Girl with Balloon’, it was officially renamed after the stunt. Its value tripled overnight.",
    },
    hammerUSD: 25_400_000,
    year: 2021,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2021/contemporary-art-evening-auction/banksy-love-is-in-the-bin",
    emoji: "🎈",
    image: {
      src: wm("The_World_of_Banksy_2022%2C_Brussels.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Wikimedia Commons (CC-BY-SA) — illustrative Banksy exhibition",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_World_of_Banksy_2022,_Brussels.jpg",
      illustrative: true,
    },
  },
  {
    id: "vermeer-virginals",
    category: "art",
    ko: {
      title: "페르메이르 ‘버지널 앞에 앉은 젊은 여인’",
      blurb: "베일에 싸였던 페르메이르의 30여 점 진품 중 한 점.",
      story: "30년간 ‘가짜’로 의심받다가 진품으로 재감정된 작품. 라스 그라프 컬렉션이 매각.",
    },
    en: {
      title: "Vermeer — ‘Young Woman Seated at the Virginals’",
      blurb: "One of about 30 surviving authentic Vermeer paintings.",
      story: "Doubted as a fake for decades before being reauthenticated. Sold from the Wynn collection.",
    },
    hammerUSD: 30_000_000,
    year: 2004,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2004/old-master-paintings-l04033.html",
    emoji: "🎹",
    image: {
      src: wm("Woman_writing_a_letter%2C_with_her_maid%2C_by_Johannes_Vermeer.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Vermeer painting (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Woman_writing_a_letter,_with_her_maid,_by_Johannes_Vermeer.jpg",
      illustrative: true,
    },
  },
  {
    id: "kim-whanki-universe",
    category: "korea",
    ko: {
      title: "김환기 ‘우주 5-IV-71 #200’",
      blurb: "한국 미술품 경매 사상 최고가. 김환기 점화(點畵)의 절정.",
      story: "두 폭으로 이뤄진 디프티크. 작가가 뉴욕에서 그린 작품 중 가장 큰 캔버스.",
    },
    en: {
      title: "Kim Whan-ki — ‘Universe 5-IV-71 #200’",
      blurb: "The most expensive Korean artwork ever sold at auction.",
      story: "A two-panel diptych — the largest canvas Kim painted during his New York period.",
    },
    hammerUSD: 13_250_000,
    year: 2019,
    house: "Christie's HK",
    sourceUrl: "https://www.christies.com/en/lot/lot-6233789",
    emoji: "🌌",
    image: {
      src: wm("26-I-70%2C_1970%2C_Whanki_Kim%2C_Paintings_in_the_San_Francisco_Museum_of_Modern_Art%2C_SFMOMA_20.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Wikimedia Commons (CC-BY-SA) — Kim Whan-ki ‘26-I-70’ at SFMOMA, illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:26-I-70,_1970,_Whanki_Kim,_Paintings_in_the_San_Francisco_Museum_of_Modern_Art,_SFMOMA_20.jpg",
      illustrative: true,
    },
  },
  {
    id: "lee-jungseop-bull",
    category: "korea",
    ko: {
      title: "이중섭 ‘황소’",
      blurb: "한국 근대 미술의 상징. 가족과 떨어져 살던 이중섭이 그린 절절한 황소들.",
      story: "이중섭의 황소 그림은 “나의 자화상”이라 불린다. 폐결핵·가난 속에 그렸다.",
    },
    en: {
      title: "Lee Jung-seop — ‘Bull’ (1950s)",
      blurb: "An icon of modern Korean art — bulls painted while separated from his family.",
      story: "Lee called these bulls ‘my self-portraits.’ He painted them while battling tuberculosis and poverty.",
    },
    hammerUSD: 3_500_000,
    year: 2010,
    house: "Seoul Auction",
    sourceUrl: "https://www.seoulauction.com/auction/lot?lotNo=141",
    emoji: "🐂",
    image: {
      src: wm("Bull(1950s).jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bull(1950s).jpg",
    },
  },

  // ─────────── BOOKS / DOCUMENTS / MANUSCRIPTS ───────────
  {
    id: "magna-carta-1297",
    category: "book",
    ko: {
      title: "마그나 카르타 (1297년 사본)",
      blurb: "에드워드 1세가 재인증한 1297년판. 개인이 소유할 수 있는 마지막 사본 중 하나.",
      story: "원래 로스 페로(미국 대통령 후보)가 소유. 데이비드 루벤스타인이 낙찰 후 미국 국립문서보관소에 영구 대여.",
    },
    en: {
      title: "Magna Carta (1297 copy)",
      blurb: "The Edward I reissue — one of the last privately-held copies in the world.",
      story: "Previously owned by Ross Perot. After winning, David Rubenstein loaned it permanently to the U.S. National Archives.",
    },
    hammerUSD: 21_321_000,
    year: 2007,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2007/the-magna-carta-n08387.html",
    emoji: "📜",
    image: {
      src: wm("Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "British Library / Wikimedia (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/Category:Magna_Carta",
    },
  },
  {
    id: "shakespeare-first-folio",
    category: "book",
    ko: {
      title: "셰익스피어 『First Folio』 (1623)",
      blurb: "셰익스피어 사후 7년 만에 출간된 36편 희곡 모음의 초판.",
      story: "이 책이 없었다면 『맥베스』, 『템페스트』 등 18편이 영원히 사라졌을 것이다.",
    },
    en: {
      title: "Shakespeare’s First Folio (1623)",
      blurb: "The first collected edition of 36 plays, printed seven years after Shakespeare’s death.",
      story: "Without it, 18 plays — including Macbeth and The Tempest — would have been lost forever.",
    },
    hammerUSD: 9_978_000,
    year: 2020,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-6275428",
    emoji: "📖",
    image: {
      src: wm("Title_page_William_Shakespeare%27s_First_Folio_1623.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Title_page_William_Shakespeare%27s_First_Folio_1623.jpg",
    },
  },
  {
    id: "dunlap-broadside",
    category: "book",
    ko: {
      title: "미국 독립선언서 초판 (Dunlap broadside, 1776)",
      blurb: "1776년 7월 4일 밤 인쇄된 첫 인쇄본 중 하나.",
      story: "낙찰자는 시트콤 제작자 노먼 리어. 그는 이 사본을 들고 50개 주를 순회 전시했다.",
    },
    en: {
      title: "Dunlap Broadside — Declaration of Independence (1776)",
      blurb: "One of the original copies printed the night of July 4, 1776.",
      story: "Bought by sitcom producer Norman Lear, who toured it across all 50 states.",
    },
    hammerUSD: 8_140_000,
    year: 2000,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2000/declaration-of-independence-n07530.html",
    emoji: "🗽",
    image: {
      src: wm("United_States_Declaration_of_Independence.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:United_States_Declaration_of_Independence.jpg",
    },
  },
  {
    id: "bay-psalm-book",
    category: "book",
    ko: {
      title: "베이 시편집 (Bay Psalm Book, 1640)",
      blurb: "영국령 북미에서 인쇄된 최초의 책.",
      story: "현존 11권. 보스턴 올드사우스교회가 두 권 중 하나를 매각해 운영비로 썼다.",
    },
    en: {
      title: "The Bay Psalm Book (1640)",
      blurb: "The first book ever printed in British North America.",
      story: "Only 11 copies survive. Boston’s Old South Church sold one of its two to fund operations.",
    },
    hammerUSD: 14_165_000,
    year: 2013,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2013/the-bay-psalm-book-n09022.html",
    emoji: "📕",
    image: {
      src: wm("Bay_Psalm_Book.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/Category:Bay_Psalm_Book",
    },
  },
  {
    id: "codex-leicester",
    category: "manuscript",
    ko: {
      title: "다 빈치 『코덱스 레스터』",
      blurb: "물·달·화석에 대한 레오나르도 다 빈치의 72쪽짜리 친필 노트.",
      story: "낙찰자는 빌 게이츠. 그는 이 노트를 스캔해 윈도우 95의 화면보호기로 만들었다.",
    },
    en: {
      title: "Da Vinci’s Codex Leicester",
      blurb: "Leonardo’s 72-page handwritten notebook on water, the Moon, and fossils.",
      story: "Bought by Bill Gates, who scanned the pages and turned them into a Windows 95 screensaver.",
    },
    hammerUSD: 30_802_500,
    year: 1994,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-1147528",
    emoji: "✍️",
    image: {
      src: wm("CodexLeicester.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Scan: Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:CodexLeicester.jpg",
    },
  },
  {
    id: "einstein-god-letter",
    category: "manuscript",
    ko: {
      title: "아인슈타인 ‘신(神) 편지’",
      blurb: "1954년, 사망 1년 전 철학자 에릭 구트킨드에게 보낸 친필 편지.",
      story: "“신이라는 단어는 인간의 약함의 산물일 뿐이다.” — 종교에 대한 아인슈타인의 가장 직설적인 사적 고백.",
    },
    en: {
      title: "Einstein’s ‘God Letter’",
      blurb: "A 1954 handwritten letter to philosopher Eric Gutkind, sent a year before his death.",
      story: "“The word God is for me nothing more than the expression of human weakness.”",
    },
    hammerUSD: 2_892_500,
    year: 2018,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-6173718",
    emoji: "📜",
    image: {
      src: wm("Einstein_1921_by_F_Schmutzer_-_restoration.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: F. Schmutzer, 1921 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Einstein_1921_by_F_Schmutzer_-_restoration.jpg",
      illustrative: true,
    },
  },
  {
    id: "beatles-day-in-the-life",
    category: "manuscript",
    ko: {
      title: "비틀즈 ‘A Day in the Life’ 친필 가사",
      blurb: "존 레논이 직접 쓴 곡의 두 페이지짜리 친필 원고.",
      story: "『Sgt. Pepper’s Lonely Hearts Club Band』의 마지막 곡. ‘I read the news today, oh boy…’",
    },
    en: {
      title: "Beatles — ‘A Day in the Life’ Lyrics",
      blurb: "John Lennon’s two-page handwritten draft of the song.",
      story: "The closing track of Sgt. Pepper’s. ‘I read the news today, oh boy…’",
    },
    hammerUSD: 1_202_500,
    year: 2010,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2010/rock-roll-history-n08664.html",
    emoji: "🎵",
    image: {
      src: wm("The_Beatles_in_America.JPG"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: UPI 1964 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Beatles_in_America.JPG",
      illustrative: true,
    },
  },
  {
    id: "dylan-rolling-stone-lyrics",
    category: "manuscript",
    ko: {
      title: "밥 딜런 ‘Like a Rolling Stone’ 친필 가사",
      blurb: "딜런이 4페이지 호텔 메모지에 휘갈겨 쓴 1965년 명곡의 초고.",
      story: "팝송 가사 친필 원고로는 사상 최고가. 시작 단어 ‘Once upon a time…’부터 시작한다.",
    },
    en: {
      title: "Dylan — ‘Like a Rolling Stone’ Lyrics Draft",
      blurb: "Four pages of hotel stationery scrawled with Dylan’s 1965 masterpiece.",
      story: "A record price for any pop-music manuscript. It opens, ‘Once upon a time…’",
    },
    hammerUSD: 2_045_000,
    year: 2014,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2014/rock-roll-history-n09196.html",
    emoji: "🎤",
    image: {
      src: wm("Bob_Dylan_1963_promo_photo_by_Don_Hunstein.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: Don Hunstein, 1963 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bob_Dylan_1963_promo_photo_by_Don_Hunstein.jpg",
      illustrative: true,
    },
  },

  // ─────────── FOSSILS ───────────
  {
    id: "trex-stan",
    category: "fossil",
    ko: {
      title: "티라노사우루스 ‘스탠(Stan)’",
      blurb: "1987년 미국 사우스다코타에서 발굴된 가장 완전한 T-rex 골격 중 하나.",
      story: "낙찰가는 화석 경매 신기록. 이후 아부다비 자연사박물관이 소유주임이 밝혀졌다.",
    },
    en: {
      title: "Tyrannosaurus rex ‘Stan’",
      blurb: "One of the most complete T-rex skeletons ever found.",
      story: "A fossil auction record. The buyer turned out to be the Natural History Museum of Abu Dhabi.",
    },
    hammerUSD: 31_847_500,
    year: 2020,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-6280911",
    emoji: "🦖",
    image: {
      src: wm("Tyrannosaurus_Stan_National_Museum_of_Nature_and_Science.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Wikimedia Commons (CC-BY-SA)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tyrannosaurus_Stan_National_Museum_of_Nature_and_Science.jpg",
    },
  },
  {
    id: "stegosaurus-apex",
    category: "fossil",
    ko: {
      title: "스테고사우루스 ‘에이펙스(Apex)’",
      blurb: "역대 화석 경매 사상 최고가. 1억 5천만 년 전 골격이 거의 완전한 상태로 발굴됐다.",
      story: "헤지펀드 매니저 켄 그리핀이 낙찰. 미국 자연사박물관에 4년간 대여하기로 했다.",
    },
    en: {
      title: "Stegosaurus ‘Apex’",
      blurb: "The most expensive fossil ever auctioned — a near-complete 150-million-year-old skeleton.",
      story: "Bought by hedge fund manager Ken Griffin, who loaned it to the American Museum of Natural History.",
    },
    hammerUSD: 44_600_000,
    year: 2024,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2024/geek-week-2024-natural-history/apex-the-most-expensive-stegosaurus",
    emoji: "🦴",
    image: {
      src: wm("Stegosaurus_skeleton_at_National_Museum_of_Scotland.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Wikimedia Commons (CC-BY-SA) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Stegosaurus_skeleton_at_National_Museum_of_Scotland.jpg",
      illustrative: true,
    },
  },

  // ─────────── SPACE / TECH ───────────
  {
    id: "apollo11-lunar-bag",
    category: "space",
    ko: {
      title: "아폴로 11호 달 토양 봉투",
      blurb: "닐 암스트롱이 처음 채집한 달 표면 샘플을 담았던 가방.",
      story: "NASA가 분실한 후 일반 경매에서 1,000달러도 안 되는 가격에 팔린 적 있는 그 봉투. 진위 확인 후 가격이 1,800배 뛰었다.",
    },
    en: {
      title: "Apollo 11 Lunar Sample Bag",
      blurb: "The bag that held the first samples Neil Armstrong scooped from the Moon.",
      story: "NASA had lost it; it once sold for under $1,000 at a U.S. Marshals auction. After authentication, it jumped 1,800×.",
    },
    hammerUSD: 1_812_500,
    year: 2017,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2017/space-exploration-n09757.html",
    emoji: "🚀",
    image: {
      src: wm("Aldrin_Apollo_11_original.jpg"),
      source: "NASA",
      license: "PD",
      credit: "Photo: NASA / Neil Armstrong (public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Aldrin_Apollo_11_original.jpg",
      illustrative: true,
    },
  },
  {
    id: "apple-1-computer",
    category: "tech",
    ko: {
      title: "Apple-1 컴퓨터 (Ricketts 사본)",
      blurb: "워즈니악과 잡스가 1976년 잡스의 차고에서 200대만 만든 회로기판.",
      story: "원래 가격 666.66달러. 50년 사이 1,200배 가격이 됐다. 워즈니악 친필 사인 포함.",
    },
    en: {
      title: "Apple-1 Computer (Ricketts copy)",
      blurb: "One of only ~200 boards Wozniak and Jobs hand-built in Jobs’s garage in 1976.",
      story: "Original price: $666.66. It sold for 1,200× that 50 years later, signed by Wozniak.",
    },
    hammerUSD: 815_000,
    year: 2014,
    house: "Bonhams",
    sourceUrl: "https://www.bonhams.com/auctions/22148/lot/40",
    emoji: "💾",
    image: {
      src: wm("Apple-1%2C_1976%2C_Computer_History_Museum.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Computer History Museum / Wikimedia (CC-BY-SA)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Apple-1,_1976,_Computer_History_Museum.jpg",
    },
  },

  // ─────────── COMICS ───────────
  {
    id: "action-comics-1",
    category: "comic",
    ko: {
      title: "『Action Comics』 #1 (1938)",
      blurb: "슈퍼맨이 처음 등장한 만화책. CGC 8.5 등급 사본.",
      story: "원래 가격은 10센트. 6,000만 배 가격에 팔린 종이 한 권.",
    },
    en: {
      title: "Action Comics #1 (1938)",
      blurb: "The comic that introduced Superman. This copy is graded CGC 8.5.",
      story: "Cover price: 10¢. It sold for 60 million times that.",
    },
    hammerUSD: 6_000_000,
    year: 2024,
    house: "ComicConnect",
    sourceUrl: "https://www.comicconnect.com/news/action-comics-1-sets-record-6-million",
    emoji: "🦸",
    image: {
      src: wm("Joe_Shuster.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Joe Shuster, Superman co-creator (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Joe_Shuster.jpg",
      illustrative: true,
    },
  },
  {
    id: "amazing-fantasy-15",
    category: "comic",
    ko: {
      title: "『Amazing Fantasy』 #15 (1962)",
      blurb: "스파이더맨이 처음 등장한 만화책. CGC 9.6 — 현존 최고 등급 중 하나.",
      story: "스탠 리와 스티브 디트코의 합작. 처음엔 ‘너무 어두워’ 잡지를 폐간시키려 했다.",
    },
    en: {
      title: "Amazing Fantasy #15 (1962)",
      blurb: "The first appearance of Spider-Man. Graded CGC 9.6 — among the highest-known.",
      story: "Stan Lee and Steve Ditko collaborated on it. Marvel almost killed the title before this issue.",
    },
    hammerUSD: 3_600_000,
    year: 2021,
    house: "Heritage Auctions",
    sourceUrl: "https://comics.ha.com/itm/silver-age-1956-1969-/superhero/amazing-fantasy-15/a/7240-91206.s",
    emoji: "🕷️",
    image: {
      src: wm("Stan_Lee_1975.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Stan Lee, 1975 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Stan_Lee_1975.jpg",
      illustrative: true,
    },
  },
  {
    id: "detective-comics-27",
    category: "comic",
    ko: {
      title: "『Detective Comics』 #27 (1939)",
      blurb: "배트맨이 처음 등장한 만화책.",
      story: "밥 케인과 빌 핑거가 만들었다. 처음엔 단순한 단행본 단편이었지만, 곧 단독 시리즈로 분리됐다.",
    },
    en: {
      title: "Detective Comics #27 (1939)",
      blurb: "Batman’s first appearance.",
      story: "Created by Bob Kane and Bill Finger. Started as a one-off backup story before getting his own title.",
    },
    hammerUSD: 1_740_000,
    year: 2020,
    house: "Heritage Auctions",
    sourceUrl: "https://comics.ha.com/itm/golden-age-1938-1955-/superhero/detective-comics-27/a/7223-91118.s",
    emoji: "🦇",
    image: {
      src: wm("Bob_Kane_1966_photo.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Bob Kane, 1966 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bob_Kane_1966_photo.jpg",
      illustrative: true,
    },
  },
  {
    id: "pikachu-illustrator-card",
    category: "comic",
    ko: {
      title: "‘피카츄 일러스트레이터’ 카드 (1998)",
      blurb: "1998년 일본 포켓몬 카드 일러스트 콘테스트 우승자에게만 39장 배포된 전설의 카드.",
      story: "낙찰자는 유튜버 로건 폴. 그는 메이웨더와의 권투 시합 입장 때 이 카드를 목에 걸고 등장했다.",
    },
    en: {
      title: "‘Pikachu Illustrator’ Card (1998)",
      blurb: "Only 39 copies were printed — given as prizes in a 1998 illustration contest.",
      story: "Bought by YouTuber Logan Paul, who wore it around his neck to a Mayweather boxing match.",
    },
    hammerUSD: 5_275_000,
    year: 2022,
    house: "private (Logan Paul)",
    sourceUrl: "https://www.guinnessworldrecords.com/world-records/720905-most-expensive-pokemon-trading-card-sold-at-private-sale",
    emoji: "⚡",
    image: {
      src: wm("Pokemon_Pikachu_Color.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Pokémon Pikachu generic image (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pokemon_Pikachu_Color.jpg",
      illustrative: true,
    },
  },

  // ─────────── FILM PROPS ───────────
  {
    id: "monroe-jfk-dress",
    category: "film",
    ko: {
      title: "마릴린 먼로 ‘Happy Birthday’ 드레스",
      blurb: "1962년 케네디 대통령 생일파티에서 입었던 살결이 비치는 비즈 드레스.",
      story: "당시 1만 2천 달러에 제작된 옷. 2022년 킴 카다시안이 메트 갈라에서 잠시 입어 논란이 됐다.",
    },
    en: {
      title: "Marilyn Monroe’s ‘Happy Birthday’ Dress",
      blurb: "The sheer beaded gown she wore to JFK’s 1962 birthday gala.",
      story: "Originally made for $12,000. In 2022, Kim Kardashian briefly wore it at the Met Gala — sparking outrage.",
    },
    hammerUSD: 4_810_000,
    year: 2016,
    house: "Julien's Auctions",
    sourceUrl: "https://www.juliensauctions.com/auctions/marilyn-monroe-the-auction-2016",
    emoji: "👗",
    image: {
      src: wm("Marilyn_Monroe_1953.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: 1953 publicity (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Marilyn_Monroe_1953.jpg",
      illustrative: true,
    },
  },
  {
    id: "ruby-slippers",
    category: "film",
    ko: {
      title: "주디 갈런드 ‘오즈의 마법사’ 루비 슬리퍼",
      blurb: "1939년 영화에서 도로시가 신었던 진짜 빨간 구두.",
      story: "영화 소품 사상 최고가. 2005년 도난당했다가 13년 만에 FBI가 회수한 그 한 켤레.",
    },
    en: {
      title: "Judy Garland’s Ruby Slippers (Wizard of Oz)",
      blurb: "The actual sequined shoes Dorothy wore in the 1939 film.",
      story: "An all-time movie prop record. Stolen in 2005, recovered by the FBI 13 years later.",
    },
    hammerUSD: 32_500_000,
    year: 2024,
    house: "Heritage Auctions",
    sourceUrl: "https://entertainment.ha.com/itm/movie-props/judy-garland-ruby-slippers/",
    emoji: "👠",
    image: {
      src: wm("Dorothy%27s_Ruby_Slippers%2C_Wizard_of_Oz_1938.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Smithsonian collection (Wikimedia, public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Dorothy%27s_Ruby_Slippers,_Wizard_of_Oz_1938.jpg",
    },
  },
  {
    id: "maltese-falcon-statue",
    category: "film",
    ko: {
      title: "‘말타의 매’ 동상 (1941)",
      blurb: "험프리 보가트가 손에 들었던 11파운드짜리 검은 매 조각상.",
      story: "영화에는 두 개가 사용됐고 그 중 하나. 영화 역사상 가장 유명한 ‘맥거핀’.",
    },
    en: {
      title: "The Maltese Falcon Statuette (1941)",
      blurb: "The 11-pound lead falcon Humphrey Bogart held in the film.",
      story: "Two were used in production; this is one of them — cinema’s most famous MacGuffin.",
    },
    hammerUSD: 4_085_000,
    year: 2013,
    house: "Bonhams",
    sourceUrl: "https://www.bonhams.com/auctions/21364/lot/132/",
    emoji: "🦅",
    image: {
      src: wm("Humphrey_Bogart_The_Maltese_Falcon_Still.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Bogart in The Maltese Falcon, 1941 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Humphrey_Bogart_The_Maltese_Falcon_Still.jpg",
      illustrative: true,
    },
  },

  // ─────────── MUSIC ───────────
  {
    id: "stradivarius-lady-blunt",
    category: "music",
    ko: {
      title: "스트라디바리우스 ‘레이디 블런트’ (1721)",
      blurb: "스트라디바리가 만든 바이올린 중 가장 보존 상태가 좋은 한 대.",
      story: "수익금은 2011년 동일본 대지진 피해 복구 기금으로 기부됐다.",
    },
    en: {
      title: "Stradivarius ‘Lady Blunt’ (1721)",
      blurb: "One of the best-preserved violins Stradivari ever made.",
      story: "Proceeds went to relief funds for victims of Japan’s 2011 earthquake and tsunami.",
    },
    hammerUSD: 15_894_000,
    year: 2011,
    house: "Tarisio",
    sourceUrl: "https://tarisio.com/cozio-archive/property/?ID=42038",
    emoji: "🎻",
    image: {
      src: wm("Stradivarius_violin_front.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons — illustrative Stradivarius",
      sourceUrl: "https://commons.wikimedia.org/wiki/Category:Stradivarius_violins",
      illustrative: true,
    },
  },
  {
    id: "cobain-martin-d18e",
    category: "music",
    ko: {
      title: "커트 코베인의 MTV Unplugged Martin D-18E",
      blurb: "1993년 너바나 ‘MTV Unplugged’ 무대에서 코베인이 연주한 그 통기타.",
      story: "악기 경매 사상 최고가. 코베인은 5개월 뒤 사망했고, 이 공연은 그의 사실상 마지막 무대 영상이 됐다.",
    },
    en: {
      title: "Kurt Cobain’s MTV Unplugged Martin D-18E",
      blurb: "The acoustic guitar Cobain played at Nirvana’s 1993 MTV Unplugged taping.",
      story: "An all-time instrument auction record. Cobain died five months later — making this his last filmed performance.",
    },
    hammerUSD: 6_010_000,
    year: 2020,
    house: "Julien's Auctions",
    sourceUrl: "https://www.juliensauctions.com/auctions/2020/icons-idols-rock-n-roll",
    emoji: "🎸",
    image: {
      src: wm("Kurt_Cobain%27s_Martin_D-18E_guitar%2C_RCM_Museum.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: RCM Museum / Wikimedia (CC-BY-SA)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kurt_Cobain%27s_Martin_D-18E_guitar,_RCM_Museum.jpg",
    },
  },
  {
    id: "lennon-gibson-j160e",
    category: "music",
    ko: {
      title: "존 레논의 깁슨 J-160E (1962)",
      blurb: "비틀즈 초기 곡 ‘She Loves You’와 ‘I Want to Hold Your Hand’를 녹음한 그 기타.",
      story: "1963년 콘서트에서 분실됐다가 50년 만에 미국 캘리포니아의 어느 다락에서 발견됐다.",
    },
    en: {
      title: "John Lennon’s 1962 Gibson J-160E",
      blurb: "The guitar Lennon used to record ‘She Loves You’ and ‘I Want to Hold Your Hand.’",
      story: "Lost at a 1963 concert. Surfaced 50 years later in a California attic.",
    },
    hammerUSD: 2_410_000,
    year: 2015,
    house: "Julien's Auctions",
    sourceUrl: "https://www.juliensauctions.com/auctions/2015/icons-idols-rock-n-roll",
    emoji: "🎸",
    image: {
      src: wm("John_Lennon_1964.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "John Lennon, 1964 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:John_Lennon_1964.jpg",
      illustrative: true,
    },
  },

  // ─────────── SPORTS ───────────
  {
    id: "babe-ruth-1932-jersey",
    category: "sports",
    ko: {
      title: "베이브 루스 1932 ‘예고 홈런’ 저지",
      blurb: "1932년 월드시리즈 3차전, 손가락으로 가리킨 곳에 홈런을 친 그 경기에 입었던 유니폼.",
      story: "스포츠 기념품 사상 최고가. 야구 역사상 가장 유명한 ‘소문난 홈런’ 한 방의 무게.",
    },
    en: {
      title: "Babe Ruth’s 1932 ‘Called Shot’ Jersey",
      blurb: "Worn in Game 3 of the 1932 World Series — the game where he supposedly pointed before homering.",
      story: "An all-time sports memorabilia record. The literal weight of baseball’s most legendary at-bat.",
    },
    hammerUSD: 24_120_000,
    year: 2024,
    house: "Heritage Auctions",
    sourceUrl: "https://sports.ha.com/itm/baseball-collectibles/uniforms/1932-babe-ruth-game-worn-yankees-jersey/",
    emoji: "⚾",
    image: {
      src: wm("Babe_Ruth2.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Photo: Wikimedia Commons (public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Babe_Ruth2.jpg",
      illustrative: true,
    },
  },
  {
    id: "honus-wagner-t206",
    category: "sports",
    ko: {
      title: "호너스 와그너 T206 야구카드 (1909)",
      blurb: "담배 회사 광고를 거부해 회수된 전설의 카드.",
      story: "유통된 매수는 50~200장 추정. ‘세상에서 가장 비싼 종이 한 장’으로 불린다.",
    },
    en: {
      title: "Honus Wagner T206 Baseball Card (1909)",
      blurb: "The legendary card pulled when Wagner refused to endorse cigarettes.",
      story: "Estimated 50–200 copies survive. ‘The most valuable piece of cardboard in the world.’",
    },
    hammerUSD: 7_250_000,
    year: 2022,
    house: "Robert Edward Auctions",
    sourceUrl: "https://www.robertedwardauctions.com/auction/2022/spring/lots/lot-1",
    emoji: "🃏",
    image: {
      src: wm("Honus_wagner_t206_baseball_card.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Card: American Tobacco Co., 1909 (Wikimedia, public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Honus_wagner_t206_baseball_card.jpg",
    },
  },
  {
    id: "mickey-mantle-1952-topps",
    category: "sports",
    ko: {
      title: "미키 맨틀 1952 Topps 카드",
      blurb: "맨틀의 사실상 첫 메이저 카드. SGC 9.5 등급 한 장.",
      story: "1952년에 인기 없어 안 팔린 카드들이 통째로 바다에 버려졌다는 전설이 있다. 그래서 더 희귀.",
    },
    en: {
      title: "Mickey Mantle 1952 Topps Card",
      blurb: "Mantle’s defining rookie-era card. This copy graded SGC 9.5.",
      story: "Legend says Topps dumped unsold 1952 cards into the Atlantic, making survivors all the rarer.",
    },
    hammerUSD: 12_600_000,
    year: 2022,
    house: "Heritage Auctions",
    sourceUrl: "https://sports.ha.com/itm/baseball-cards-1950s/1952-topps-311-mickey-mantle-sgc-mint-95/",
    emoji: "⚾",
    image: {
      src: wm("Mickey_Mantle_-_New_York_Yankees_-_1957.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Mickey Mantle, 1957 (Wikimedia, public domain) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mickey_Mantle_-_New_York_Yankees_-_1957.jpg",
      illustrative: true,
    },
  },
  {
    id: "jordan-1998-jersey",
    category: "sports",
    ko: {
      title: "마이클 조던 1998 NBA 결승 1차전 저지",
      blurb: "‘Last Dance’ 시즌의 우승까지 가는 길, 첫 경기에 입었던 유니폼.",
      story: "조던의 마지막 불스 시절. NBA 농구 저지 사상 최고가.",
    },
    en: {
      title: "Michael Jordan’s 1998 Finals Game 1 Jersey",
      blurb: "Worn in Game 1 of the ‘Last Dance’ NBA Finals run.",
      story: "Jordan’s final season with the Bulls. An NBA jersey auction record.",
    },
    hammerUSD: 10_091_000,
    year: 2022,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2022/the-dynasty-collection/the-last-dance-michael-jordan-1998-nba-finals",
    emoji: "🏀",
    image: {
      src: wm("Steve_Lipfosky_--_Michael_Jordan_(1997).jpg"),
      source: "Wikimedia",
      license: "CC-BY",
      credit: "Photo: Steve Lipfosky, 1997 (Wikimedia, CC-BY) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Steve_Lipfosky_--_Michael_Jordan_(1997).jpg",
      illustrative: true,
    },
  },
  {
    id: "maradona-hand-of-god",
    category: "sports",
    ko: {
      title: "마라도나 ‘신의 손’ 저지 (1986 멕시코 월드컵)",
      blurb: "잉글랜드와의 8강전에서 두 골 — ‘신의 손’과 ‘세기의 골’ — 을 넣을 때 입은 유니폼.",
      story: "심판은 마라도나가 손으로 골을 넣은 걸 못 봤다. 마라도나는 “신의 손”이라 불렀다.",
    },
    en: {
      title: "Maradona’s 1986 ‘Hand of God’ Jersey",
      blurb: "Worn against England in the 1986 World Cup quarter-final, where he scored the ‘Hand of God’ and ‘Goal of the Century.’",
      story: "The referee never saw the handball. Maradona called it ‘the hand of God.’",
    },
    hammerUSD: 9_280_000,
    year: 2022,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2022/the-hand-of-god-shirt",
    emoji: "⚽",
    image: {
      src: wm("Maradona_mano_de_dios.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: 1986 World Cup (Wikimedia, CC-BY-SA)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Maradona_mano_de_dios.jpg",
    },
  },

  // ─────────── COINS / STAMPS ───────────
  {
    id: "double-eagle-1933",
    category: "coin",
    ko: {
      title: "1933 더블 이글 (20달러 금화)",
      blurb: "미국 정부가 회수해 녹였어야 했지만 살아남은 단 한 점.",
      story: "이전 소유자는 이집트 왕 파루크. 미국 재무부와 30년간 법정 다툼 끝에 합법화됐다.",
    },
    en: {
      title: "1933 Double Eagle ($20 Gold Coin)",
      blurb: "The only one of its kind the U.S. government allowed into private hands.",
      story: "Previously owned by King Farouk of Egypt. After a 30-year legal battle, it was officially monetized.",
    },
    hammerUSD: 18_872_250,
    year: 2021,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2021/three-treasures-collected-by-stuart-weitzman/the-1933-double-eagle",
    emoji: "🪙",
    image: {
      src: wm("1933_Double_eagle_(2).jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "U.S. Mint / Wikimedia (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:1933_Double_eagle_(2).jpg",
    },
  },
  {
    id: "brasher-doubloon",
    category: "coin",
    ko: {
      title: "브래셔 더블론 (1787)",
      blurb: "미국이 만든 최초의 금화 중 하나. 조지 워싱턴의 이웃이 만들었다.",
      story: "현존 7점. 단 한 점만 가슴 부분에 ‘EB(에프라임 브래셔)’ 각인이 있다.",
    },
    en: {
      title: "Brasher Doubloon (1787)",
      blurb: "One of the earliest gold coins minted in America — by George Washington’s neighbor.",
      story: "Only 7 survive. One has Brasher’s ‘EB’ punch on the eagle’s breast — making it unique.",
    },
    hammerUSD: 9_360_000,
    year: 2021,
    house: "Heritage Auctions",
    sourceUrl: "https://coins.ha.com/itm/colonials/1787-brasher-doubloon/a/1325-3001.s",
    emoji: "🪙",
    image: {
      src: wm("1787_Brasher_Doubloon_(obverse).jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:1787_Brasher_Doubloon_(obverse).jpg",
    },
  },
  {
    id: "british-guiana-1c-magenta",
    category: "stamp",
    ko: {
      title: "영국령 기아나 1센트 마젠타 우표 (1856)",
      blurb: "세상에 단 한 장 존재하는 우표.",
      story: "1873년 한 12살 소년이 삼촌의 편지에서 발견했다. 이후 4번 경매에 나올 때마다 신기록.",
    },
    en: {
      title: "British Guiana 1-cent Magenta (1856)",
      blurb: "Only one copy exists in the world.",
      story: "Discovered by a 12-year-old boy in his uncle’s letters in 1873. Each of its four auctions has set a new record.",
    },
    hammerUSD: 8_307_000,
    year: 2021,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2021/three-treasures-collected-by-stuart-weitzman/the-british-guiana-1856-1c-magenta",
    emoji: "📮",
    image: {
      src: wm("British_Guiana_1856_1c_magenta_stamp.jpg"),
      source: "Wikimedia",
      license: "PD",
      credit: "Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:British_Guiana_1856_1c_magenta_stamp.jpg",
    },
  },

  // ─────────── GEMS ───────────
  {
    id: "ctf-pink-star",
    category: "gem",
    ko: {
      title: "CTF 핑크 스타 다이아몬드 (59.6캐럿)",
      blurb: "내부 결함 없는 ‘인터널리 플로리스’ 등급 핑크 다이아몬드 중 사상 최대.",
      story: "2013년 첫 낙찰자가 잔금을 못 내 매매가 무산. 4년 뒤 다시 경매에 나와 새 주인을 찾았다.",
    },
    en: {
      title: "CTF Pink Star Diamond (59.6 ct)",
      blurb: "The largest internally flawless pink diamond ever graded.",
      story: "The 2013 winning bidder defaulted. Four years later, it was re-auctioned successfully.",
    },
    hammerUSD: 71_200_000,
    year: 2017,
    house: "Sotheby's HK",
    sourceUrl: "https://www.sothebys.com/en/auctions/2017/magnificent-jewels-and-jadeite-spring-sale-hk0691.html",
    emoji: "💎",
    image: {
      src: wm("Pink_Diamonds_of_the_Argyle_Mine_(20977868250).jpg"),
      source: "Wikimedia",
      license: "CC-BY",
      credit: "Photo: Wikimedia Commons (CC-BY) — illustrative pink diamonds",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pink_Diamonds_of_the_Argyle_Mine_(20977868250).jpg",
      illustrative: true,
    },
  },
  {
    id: "sweet-josephine",
    category: "gem",
    ko: {
      title: "Sweet Josephine 핑크 다이아몬드 (16.08캐럿)",
      blurb: "홍콩 사업가 라이서룬이 7살 딸의 이름을 따 새로 명명한 다이아몬드.",
      story: "낙찰자 자신이 이름을 지을 권리도 함께 받았다. 그는 구매 직후 트위터에 발표.",
    },
    en: {
      title: "Sweet Josephine — 16.08-ct Pink Diamond",
      blurb: "Renamed after the buyer’s 7-year-old daughter.",
      story: "Hong Kong businessman Lau Siu-Lun bought it, then publicly renamed it after his child.",
    },
    hammerUSD: 28_500_000,
    year: 2015,
    house: "Christie's",
    sourceUrl: "https://www.christies.com/en/lot/lot-5947523",
    emoji: "💖",
    image: {
      src: wm("Pink_Diamonds_of_the_Argyle_Mine_(20977868250).jpg"),
      source: "Wikimedia",
      license: "CC-BY",
      credit: "Photo: Wikimedia Commons (CC-BY) — illustrative pink diamonds",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pink_Diamonds_of_the_Argyle_Mine_(20977868250).jpg",
      illustrative: true,
    },
  },

  // ─────────── WATCHES ───────────
  {
    id: "patek-grandmaster-chime",
    category: "watch",
    ko: {
      title: "파텍 필립 Grandmaster Chime 6300A-010",
      blurb: "20가지 합 기능을 가진 전 세계에 단 한 점뿐인 스테인리스 모델.",
      story: "사상 최고가 시계. 자선 경매로 진행됐고, 수익 전액이 의학 연구에 기부됐다.",
    },
    en: {
      title: "Patek Philippe Grandmaster Chime 6300A-010",
      blurb: "20 complications. A unique stainless steel piece — the only one ever made.",
      story: "An all-time auction record for a watch. The charity sale donated all proceeds to medical research.",
    },
    hammerUSD: 31_000_000,
    year: 2019,
    house: "Christie's (Only Watch)",
    sourceUrl: "https://www.christies.com/en/lot/lot-6197825",
    emoji: "⌚",
    image: {
      src: wm("Patek_Philippe_Minute_Repeater_Split_Seconds_Chronograph%2C_Geneva%2C_Switzerland%2C_c._1895_-_Franklin_Institute_-_DSC06644.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Franklin Institute (Wikimedia, CC-BY-SA) — illustrative Patek Philippe",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Patek_Philippe_Minute_Repeater_Split_Seconds_Chronograph,_Geneva,_Switzerland,_c._1895_-_Franklin_Institute_-_DSC06644.jpg",
      illustrative: true,
    },
  },
  {
    id: "rolex-paul-newman",
    category: "watch",
    ko: {
      title: "롤렉스 데이토나 ‘폴 뉴먼’ Ref. 6239",
      blurb: "배우 폴 뉴먼의 아내 조앤 우드워드가 1968년 그에게 선물한 시계.",
      story: "뒷면에는 “Drive Carefully Me”라는 새김. 폴 뉴먼은 이 시계를 매일 착용했다.",
    },
    en: {
      title: "Paul Newman’s Rolex Daytona Ref. 6239",
      blurb: "Given to Paul Newman by his wife Joanne Woodward in 1968.",
      story: "Engraved on the back: ‘Drive Carefully Me.’ He wore it every day.",
    },
    hammerUSD: 17_752_500,
    year: 2017,
    house: "Phillips",
    sourceUrl: "https://www.phillips.com/detail/PAUL-NEWMAN-S-ROLEX-DAYTONA-REF-6239",
    emoji: "⌚",
    image: {
      src: wm("Rolex_Daytona_Cosmograph.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Wikimedia Commons (CC-BY-SA) — illustrative Rolex Daytona",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Rolex_Daytona_Cosmograph.jpg",
      illustrative: true,
    },
  },

  // ─────────── DRINKS ───────────
  {
    id: "macallan-1926-adami",
    category: "drink",
    ko: {
      title: "맥캘란 1926 Adami (60년산 위스키)",
      blurb: "60년 통숙성 후 단 24병만 출시된 한정판. 그중 Adami가 라벨을 그린 한 병.",
      story: "위스키 사상 최고가. 한 병 기준으로 환산하면 1잔에 20만 달러 꼴.",
    },
    en: {
      title: "Macallan 1926 60-Year-Old (Adami label)",
      blurb: "Only 24 bottles released after 60 years of cask aging. Valerio Adami designed the label.",
      story: "An all-time whisky record. About $200,000 per pour at this price.",
    },
    hammerUSD: 2_700_000,
    year: 2023,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/buy/auction/2023/the-macallan-the-ultimate-whisky-collection/macallan-1926-60-year-old",
    emoji: "🥃",
    image: {
      src: wm("The_Macallan_distillery_(RSHP).jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Wikimedia Commons (CC-BY-SA) — Macallan distillery, illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Macallan_distillery_(RSHP).jpg",
      illustrative: true,
    },
  },
  {
    id: "romanee-conti-1945",
    category: "drink",
    ko: {
      title: "Romanée-Conti 1945 (1병)",
      blurb: "전쟁 직후 포도밭이 거의 전멸한 해. 그해 단 600병만 만들어졌다.",
      story: "와인 한 병 기준으로 사상 최고가. 한 잔이면 7만 달러 꼴.",
    },
    en: {
      title: "Romanée-Conti 1945 (one bottle)",
      blurb: "The post-WWII vintage when the vineyard was almost wiped out. Only ~600 bottles made.",
      story: "An all-time bottle record. About $70,000 per glass.",
    },
    hammerUSD: 558_000,
    year: 2018,
    house: "Sotheby's",
    sourceUrl: "https://www.sothebys.com/en/auctions/2018/the-personal-cellar-domaine-de-la-romanee-conti-n09891.html",
    emoji: "🍷",
    image: {
      src: wm("Vosne-Roman%C3%A9e_Domaine_de_la_Roman%C3%A9e-Conti.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: Domaine de la Romanée-Conti vineyard (Wikimedia, CC-BY-SA) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Vosne-Romanée_Domaine_de_la_Romanée-Conti.jpg",
      illustrative: true,
    },
  },

  // ─────────── KOREA ───────────
  {
    id: "moon-jar-joseon",
    category: "korea",
    ko: {
      title: "조선백자 달항아리 (18세기)",
      blurb: "두 개의 반구를 이어 만든 백자. 너무 커서 한 번에 빚을 수 없어 위·아래를 따로 만든다.",
      story: "한국 도자기의 정수. 한국 미술사에서 ‘여백의 미’의 상징.",
    },
    en: {
      title: "Joseon Moon Jar (18th c.)",
      blurb: "Two hemispheres joined into one — so large the potter had to throw the top and bottom separately.",
      story: "An icon of Korean ceramics — the embodiment of ‘the beauty of empty space.’",
    },
    hammerUSD: 4_560_000,
    year: 2023,
    house: "Christie's NY",
    sourceUrl: "https://www.christies.com/en/lot/lot-6428091",
    emoji: "🏺",
    image: {
      src: wm("Moon_jar._18thC.Joseon_Dynasty.British_Museum.jpg"),
      source: "Wikimedia",
      license: "CC-BY-SA",
      credit: "Photo: British Museum / Wikimedia (CC-BY-SA) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Moon_jar._18thC.Joseon_Dynasty.British_Museum.jpg",
      illustrative: true,
    },
  },
  {
    id: "goryeo-celadon",
    category: "korea",
    ko: {
      title: "고려청자 (12세기)",
      blurb: "비취 같은 푸른빛으로 ‘비색(翡色)’이라 불리는 고려시대의 자랑.",
      story: "송나라 황제도 인정한 그 시대 최고의 도자기 기술. 상감(象嵌) 기법은 고려가 독창적으로 발전시켰다.",
    },
    en: {
      title: "Goryeo Celadon (12th c.)",
      blurb: "A jade-green glaze the Goryeo potters called ‘bisaek’ (kingfisher color).",
      story: "Even the Song emperor admired it. The inlay technique (sanggam) was a Korean original.",
    },
    hammerUSD: 4_200_000,
    year: 2018,
    house: "Christie's HK",
    sourceUrl: "https://www.christies.com/en/lot/lot-6168247",
    emoji: "🏺",
    image: {
      src: wm("Goryeo_Ceramic_Vessels_from_Hwaseong_in_the_National_Museum_of_Korea.jpg"),
      source: "Wikimedia",
      license: "CC-BY",
      credit: "Photo: National Museum of Korea / Wikimedia (CC-BY) — illustrative",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Goryeo_Ceramic_Vessels_from_Hwaseong_in_the_National_Museum_of_Korea.jpg",
      illustrative: true,
    },
  },
];
