import type { AnimeResult, AnimeQuestion, AnimeTestConfig } from "@/lib/anime-test";

// 일반 20명. 히든 1명(유미르 프리츠=시조 유미르)은 config.hiddens 로 분리, results[] 에 넣지 않는다.
// 각 캐릭터는 정확히 4개 문항에 등장. 히든 트리거(ymir_fritz) 4개 선택지 전부 선택 시 발동.
const RESULTS: AnimeResult[] = [
  {
    key: "eren",
    name: { ko: "엘런 예거", en: "Eren Yeager" },
    oneLiner: { ko: "어떤 대가를 치르더라도 자유를 향해 나아가는 사람", en: "Someone who charges toward freedom no matter the cost." },
    description: {
      ko: "당신은 어떤 벽도, 어떤 대가도 자유를 향한 발걸음을 막을 수 없다고 믿는 사람입니다. 처음엔 소중한 것을 지키기 위해 싸웠지만, 세상의 진실을 알게 될수록 목표는 점점 커지고 더 급진적으로 변해갔습니다. 당신의 분노는 방향이 있고, 의지는 꺾이지 않습니다. 멈추는 법을 모른다는 것이 당신의 가장 큰 무기이자 가장 위험한 점이에요.",
      en: "You believe nothing — no wall, no cost — can stop you from moving toward freedom. You started fighting to protect what you loved, but as you learned the truth of the world, your goals grew bigger and more radical. Your anger has direction, your will doesn't bend. Not knowing how to stop is both your greatest weapon and your greatest danger.",
    },
    strength: { ko: "꺾이지 않는 의지와 목표를 향한 압도적인 추진력.", en: "Unbreakable will and overwhelming drive toward your goal." },
    weakPoint: { ko: "멈추지 못해 소중한 것들을 놓쳐버릴 수 있어요.", en: "You may lose what matters most by never being able to stop." },
    friendSays: { ko: "넌 무섭도록 진심이야. 그게 좋기도 하고 무섭기도 해.", en: "You're frighteningly sincere. That's both admirable and terrifying." },
    shareLine: { ko: "나 진격 테스트에서 엘런 나왔다. 자유를 향해 달리는 사람이래.", en: "I got Eren on the AoT test — the one who charges toward freedom no matter what." },
    emoji: "⚡",
    color: "#8B2500",
  },
  {
    key: "mikasa",
    name: { ko: "미카사 아커만", en: "Mikasa Ackerman" },
    oneLiner: { ko: "지켜야 할 한 사람을 위해 모든 것을 거는 수호자", en: "A guardian who bets everything on the one person they must protect." },
    description: {
      ko: "당신의 세계는 한 사람을 중심으로 돌아갑니다. 자신의 의지가 없어서가 아니라, 그 사람을 지키는 것 자체가 당신의 의지이기 때문입니다. 겉으로는 조용하고 냉정해 보이지만, 지켜야 할 것이 위협받는 순간 누구도 막을 수 없는 힘이 됩니다. 침묵 뒤에 흔들리지 않는 헌신이 있어요.",
      en: "Your world revolves around one person — not because you lack your own will, but because protecting them IS your will. Quiet and composed on the surface, once what matters to you is threatened, you become an unstoppable force. Behind the silence lies devotion that nothing can shake.",
    },
    strength: { ko: "한 사람을 향한 흔들리지 않는 헌신과 압도적인 실력.", en: "Unshakeable devotion and overwhelming skill in protecting what you love." },
    weakPoint: { ko: "모든 것을 한 곳에 걸다가 균형을 잃을 수 있어요.", en: "Betting everything on one thing can cost you your balance." },
    friendSays: { ko: "넌 말 없이도 늘 결정적인 순간에 있더라.", en: "You never say much, but you're always there at the decisive moment." },
    shareLine: { ko: "나 진격 테스트에서 미카사 나왔다. 한 사람을 위해 모든 걸 거는 수호자래.", en: "I got Mikasa — the guardian who bets everything on one person." },
    emoji: "🌺",
    color: "#8C1A1A",
  },
  {
    key: "armin",
    name: { ko: "아르민 알레르토", en: "Armin Arlert" },
    oneLiner: { ko: "힘보다 아이디어로 세상을 바꾸는 전략가", en: "A strategist who changes the world with ideas rather than force." },
    description: {
      ko: "당신은 적을 이해하고 아무도 보지 못한 길을 찾는 것이 어떤 무기보다 강력하다고 믿습니다. 신체적으로 뒤처진다는 열등감을 오래 안고 살았지만, 사실 당신의 진짜 강점은 가장 어두운 상황에서 세 번째 선택지를 찾아내는 두뇌입니다. 남들이 포기할 때 당신은 아직 생각하고 있어요.",
      en: "You believe that understanding the enemy and finding the path no one else sees is more powerful than any weapon. You've carried the inferiority of lacking physical strength for a long time, but your true strength is finding a third option when everything looks impossible. When others give up, you're still thinking.",
    },
    strength: { ko: "위기에서 아무도 생각 못 한 방법을 찾는 창의적인 두뇌.", en: "A creative mind that finds solutions no one else imagines in a crisis." },
    weakPoint: { ko: "자신의 가치를 과소평가해 결정을 망설일 때가 있어요.", en: "You underestimate yourself and hesitate when you shouldn't." },
    friendSays: { ko: "넌 항상 마지막에 답을 찾더라. 그게 진짜 신기해.", en: "You always find the answer at the last moment. That's genuinely remarkable." },
    shareLine: { ko: "나 진격 테스트에서 아르민 나왔다. 아이디어로 세상을 바꾸는 전략가래.", en: "I got Armin — the strategist who changes the world with ideas." },
    emoji: "🌊",
    color: "#2B5FA5",
  },
  {
    key: "levi",
    name: { ko: "리바이 아커만", en: "Levi Ackerman" },
    oneLiner: { ko: "냉정한 겉모습 뒤에 동료를 가장 깊이 아끼는 최강의 병사", en: "The strongest soldier, whose cold exterior hides the deepest care for comrades." },
    description: {
      ko: "당신에게 효율은 전부입니다. 말도 행동도 낭비하지 않고, 자신과 타인에게 최고의 기준을 요구합니다. 사람들은 당신을 차갑다고 하지만, 가까이서 본 사람들은 압니다. 당신이 누구보다 깊이 슬퍼하고, 누구보다 진하게 아끼며, 절대 그것을 보여주지 않는다는 것을. 그게 최강의 자리에 있는 대가예요.",
      en: "Efficiency is everything to you. You waste nothing — not words, not movements — and you hold yourself and others to the highest standards. People call you cold, but those who've seen you close know: you grieve the hardest, care the deepest, and never let yourself show it. That's the price of being the best.",
    },
    strength: { ko: "흔들리지 않는 실력과 냉정한 판단력, 동료에 대한 깊은 헌신.", en: "Unshakeable skill, cold judgment, and deep unspoken devotion to comrades." },
    weakPoint: { ko: "감정을 드러내지 못해 진심이 오해받을 수 있어요.", en: "Hiding your feelings can cause your sincerity to be misread." },
    friendSays: { ko: "넌 말은 적은데 결국 제일 많이 지켜주더라.", en: "You say so little, but you protect people the most in the end." },
    shareLine: { ko: "나 진격 테스트에서 리바이 나왔다. 차갑지만 동료를 가장 깊이 아끼는 최강이래.", en: "I got Levi — the strongest, cold outside but caring the deepest for those he fights with." },
    emoji: "⚔️",
    color: "#2A2A35",
  },
  {
    key: "hange",
    name: { ko: "한지 조에", en: "Hange Zoë" },
    oneLiner: { ko: "두려운 것일수록 더 파고드는 열정적인 연구자", en: "A passionate researcher who digs deeper into exactly what others fear." },
    description: {
      ko: "당신은 무서운 것, 위험한 것, 이해하기 어려운 것일수록 더 매력적으로 느껴지는 사람입니다. 열정은 전염되고, 아이디어는 천재적이며 가끔 무모하고, 관심을 사로잡은 것에는 머리부터 뛰어듭니다. 사람들은 당신을 무모하다고 말하지만, 당신은 그들이 충분히 호기심이 없다고 생각해요.",
      en: "You find the things others fear most to be the most fascinating. Your enthusiasm is infectious, your ideas brilliant and sometimes chaotic, and whatever captures your attention gets your full head-first dive. People call you reckless; you think they just aren't curious enough.",
    },
    strength: { ko: "끝없는 호기심과 어떤 상황도 데이터로 바꾸는 지적 열정.", en: "Endless curiosity and the intellectual passion to turn any situation into data." },
    weakPoint: { ko: "열정이 앞서다 보면 안전을 간과할 때가 있어요.", en: "Your passion can lead you to overlook safety." },
    friendSays: { ko: "넌 진짜 신기한 게 없어. 무서운 것도 재밌어하잖아ㅋㅋ", en: "Nothing fazes you. You think terrifying things are fun, lol." },
    shareLine: { ko: "나 진격 테스트에서 한지 나왔다. 두려울수록 더 파고드는 열정 연구자래.", en: "I got Hange — the passionate researcher who digs deeper into exactly what's terrifying." },
    emoji: "🔬",
    color: "#C07820",
  },
  {
    key: "erwin",
    name: { ko: "엘빈 스미스", en: "Erwin Smith" },
    oneLiner: { ko: "자신을 포함한 모든 것을 인류의 미래를 위해 바치는 지휘관", en: "A commander who sacrifices everything — including himself — for humanity's future." },
    description: {
      ko: "당신은 자신보다 큰 비전을 품고 있고, 그것을 위해 모든 것을 희생할 준비가 되어 있습니다. 본인도 포함해서. 냉혹하게 필요한 결정을 내리는 것처럼 보이지만, 그 계산 뒤에는 선두에 세운 사람들을 향한 깊고 말 없는 애정이 있습니다. 그 모순이 당신을 특별하게 만들어요.",
      en: "You carry a vision bigger than yourself, and you're ready to sacrifice everything for it — yourself included. You seem to make cold, necessary decisions, but behind the calculation is a deep, unspoken love for the people you send into the abyss. That contradiction is what makes you extraordinary.",
    },
    strength: { ko: "비전을 위해 자신을 포함한 모든 것을 내놓는 결단력과 헌신.", en: "The decisiveness and devotion to sacrifice everything, including yourself, for the vision." },
    weakPoint: { ko: "너무 큰 것을 보다 보니 곁에 있는 것들을 놓칠 수 있어요.", en: "Seeing too far ahead can cause you to miss what's right beside you." },
    friendSays: { ko: "넌 무서울 정도로 의지가 단단해. 그게 다 어디서 나오는 거야.", en: "Your will is frightening in its strength. Where does all of it come from?" },
    shareLine: { ko: "나 진격 테스트에서 엘빈 나왔다. 인류의 미래를 위해 모든 걸 바치는 지휘관이래.", en: "I got Erwin — the commander who gives everything, including himself, for humanity's future." },
    emoji: "🦅",
    color: "#2C3E6B",
  },
  {
    key: "jean",
    name: { ko: "장 키르슈타인", en: "Jean Kirstein" },
    oneLiner: { ko: "자신의 나약함에 솔직해서 가장 진짜로 성장한 사람", en: "Honest about his own weakness, the one who grows the most genuinely." },
    description: {
      ko: "당신은 자신의 겁쟁이 같은 면, 이기적인 면을 솔직하게 인정하는 사람입니다. 그게 사실 드문 용기예요. 처음엔 자신만 생각하다, 존경하는 사람이 더 큰 무언가를 위해 쓰러지는 것을 보고 외면할 수 없었습니다. 그 솔직함 덕분에 당신의 성장은 진짜입니다. 불편하게 자라는 방식이지만, 진심이에요.",
      en: "You're honest about your cowardice, your selfishness — which is actually rare courage. You started thinking only about yourself, then saw people you respected fall for something bigger, and couldn't look away. That honesty is exactly why your growth is real. It's an uncomfortable way to grow, but it's genuine.",
    },
    strength: { ko: "자신에 대한 솔직함과 그것을 바탕으로 한 진짜 성장.", en: "Honesty about yourself, and genuine growth built on that honesty." },
    weakPoint: { ko: "현실적인 시선이 때로는 냉소로 흐를 수 있어요.", en: "Your realistic perspective can sometimes slide into cynicism." },
    friendSays: { ko: "넌 겉으로는 툴툴대는데 결국 제일 든든하게 있더라.", en: "You grumble on the outside, but you end up being the most dependable one there." },
    shareLine: { ko: "나 진격 테스트에서 장 나왔다. 자신에게 솔직해서 가장 진짜로 성장한 사람이래.", en: "I got Jean — the one who grows most genuinely by being honest about his own weaknesses." },
    emoji: "🐴",
    color: "#7C5C3E",
  },
  {
    key: "sasha",
    name: { ko: "사샤 브라우스", en: "Sasha Blouse" },
    oneLiner: { ko: "본능과 따뜻함으로 어둠 속에서도 빛나는 사람", en: "Someone who shines even in darkness through instinct and warmth." },
    description: {
      ko: "당신의 본능은 거의 초자연적이고, 마음은 누구보다 큽니다. 가장 위험한 상황에서도 당신이 있으면 조금 더 따뜻해지죠. 먹는 걸 좋아하고, 사람을 좋아하고, 위험을 향해 달려가는 건 허세가 아니라 그냥 소중한 사람이 다치는 걸 볼 수 없는 마음 때문입니다.",
      en: "Your instincts are almost supernatural, and your heart is enormous. Even in the most dangerous situations, things get a little warmer when you're there. You love food, you love people, and you run toward danger not out of bravado — just because you genuinely cannot watch someone you love get hurt.",
    },
    strength: { ko: "타고난 본능과 거대한 따뜻함, 사람을 향한 순수한 마음.", en: "Natural instinct, enormous warmth, and a pure heart for people." },
    weakPoint: { ko: "충동적으로 움직이다 상황을 더 복잡하게 만들 때가 있어요.", en: "Moving on impulse can sometimes complicate things further." },
    friendSays: { ko: "넌 배고프면 일단 먹고 봐야 한다는 거 이제 다 알아ㅋㅋ", en: "We all know you have to eat first before anything else can happen, lol." },
    shareLine: { ko: "나 진격 테스트에서 사샤 나왔다. 본능과 따뜻함으로 어둠에서도 빛나는 사람이래.", en: "I got Sasha — someone who shines even in darkness through instinct and warmth." },

    emoji: "🍖",
    color: "#5E8238",
  },
  {
    key: "connie",
    name: { ko: "코니 스프링거", en: "Connie Springer" },
    oneLiner: { ko: "단순하지만 진심 하나만은 누구보다 뜨거운 사람", en: "Simple-minded, but with a sincerity that burns hotter than anyone's." },
    description: {
      ko: "사람들이 당신을 과소평가할 때가 있고, 때로는 당신 스스로도 그렇습니다. 하지만 중요한 순간에 당신은 항상 거기 있어요. 전략이나 명예를 위해서가 아니라, 그냥 이 사람들이 내 사람들이기 때문입니다. 당신의 단순함은 실은 일종의 순수함입니다. 느끼는 것을 복잡하게 만들지 않고, 그냥 행동해요.",
      en: "People underestimate you sometimes, and so do you. But when it matters, you're always there — not for strategy, not for glory, because these are simply your people. Your simplicity is actually a kind of purity: you don't complicate what you feel, you just act on it.",
    },
    strength: { ko: "진심 어린 우정과 어떤 상황에서도 곁을 지키는 충성심.", en: "Genuine friendship and loyalty that stays by your side no matter what." },
    weakPoint: { ko: "너무 빠르게 움직이다가 깊게 생각하지 않을 때가 있어요.", en: "Moving too fast can mean you sometimes don't think things through." },
    friendSays: { ko: "넌 단순한 것 같은데 결정적일 때 꼭 있어. 신기하게.", en: "You seem simple, but you're always there when it counts. Somehow." },
    shareLine: { ko: "나 진격 테스트에서 코니 나왔다. 단순하지만 진심만은 누구보다 뜨거운 사람이래.", en: "I got Connie — simple-minded, but with sincerity that burns hotter than anyone's." },

    emoji: "☀️",
    color: "#C4762A",
  },
  {
    key: "historia",
    name: { ko: "히스토리아 레이스", en: "Historia Reiss" },
    oneLiner: { ko: "거짓 이름 뒤에서 버티다 마침내 자신을 선택한 사람", en: "Someone who endured behind a false name and finally chose themselves." },
    description: {
      ko: "당신은 오랫동안 자신의 진짜 모습을 숨기고, 모두가 편안해하는 얼굴을 쓰며 살았습니다. 하지만 그 안에는 언제나 더 강한 사람이 있었어요. 스스로의 이름을 선택하고, 스스로의 길을 택하는 순간, 모든 것이 달라졌습니다. 당신에게 부드러움과 강함은 모순이 아닙니다. 함께 존재해요.",
      en: "You spent a long time hiding your real self, wearing a face that made everyone comfortable. But there was always a stronger person inside. The moment you chose your own name, your own path, everything changed. For you, gentleness and strength don't contradict each other — they coexist.",
    },
    strength: { ko: "진짜 자신을 찾아가는 용기와 약한 사람을 향한 깊은 연민.", en: "The courage to find your true self and deep compassion for the weak." },
    weakPoint: { ko: "타인의 기대에 맞추려다 자신을 잃을 때가 있어요.", en: "Trying to meet others' expectations can sometimes make you lose yourself." },
    friendSays: { ko: "넌 처음엔 몰랐는데, 알고 보면 제일 강한 사람이더라.", en: "At first I didn't know, but you turn out to be the strongest person of all." },
    shareLine: { ko: "나 진격 테스트에서 히스토리아 나왔다. 거짓 이름 뒤에서 버티다 마침내 자신을 선택한 사람이래.", en: "I got Historia — someone who endured behind a false name and finally chose themselves." },
    emoji: "🌾",
    color: "#C9A227",
  },
  {
    key: "ymir",
    name: { ko: "유미르", en: "Ymir" },
    oneLiner: { ko: "냉소로 세상을 보지만 단 한 사람을 위해 모든 것을 버린 사람", en: "Views the world with cynicism, yet gave up everything for one single person." },
    description: {
      ko: "세상은 당신에게 친절하지 않았고, 당신은 일찌감치 스스로를 먼저 챙기는 법을 배웠습니다. 유머는 날카롭고, 솔직함은 거칠고, 고귀한 척하지 않습니다. 하지만 단 한 사람을 위해서라면 모든 것을 내줄 수 있습니다. 그리고 그렇게 했어요. 후회 없이. 끝을 보지 못하더라도.",
      en: "The world hasn't been kind to you, and you learned early to look out for yourself first. Your humor is sharp, your honesty rough, and you don't pretend to be noble. But for one single person, you'd give up everything. And you did. No regrets. Even without getting to see how it ends.",
    },
    strength: { ko: "누구보다 솔직한 시선과 단 한 사람을 위한 절대적인 헌신.", en: "An honesty sharper than anyone's, and absolute devotion to the one person who matters." },
    weakPoint: { ko: "냉소가 앞서 진심을 드러내기 어려울 때가 있어요.", en: "Your cynicism can make it hard to show what you truly feel." },
    friendSays: { ko: "넌 툭툭 던지는데 결국 제일 진심이더라.", en: "You say things so casually, but you're always the most sincere one." },
    shareLine: { ko: "나 진격 테스트에서 유미르 나왔다. 냉소적이지만 한 사람을 위해 모든 걸 버린 사람이래.", en: "I got Ymir — cynical on the outside, but gave up everything for one single person." },
    emoji: "🌑",
    color: "#5C6B3A",
  },
  {
    key: "reiner",
    name: { ko: "라이너 브라운", en: "Reiner Braun" },
    oneLiner: { ko: "두 개의 자신 사이에서 무너지면서도 멈추지 않는 사람", en: "Someone who keeps going even while collapsing between two selves." },
    description: {
      ko: "당신은 두 개의 삶을 살아왔고, 이제 어느 쪽이 진짜인지조차 모릅니다. 죄책감이 거의 당신을 부숴버렸고, 한두 번이 아니라 그랬으면 했던 적도 있어요. 그래도 계속 갑니다. 갈등이 해결돼서가 아니라, 그래도 안에서 무언가가 포기를 허락하지 않기 때문에. 그게 당신의 짐이자 당신의 힘이에요.",
      en: "You've been living two lives and don't know which is real anymore. The guilt has almost broken you, and more than once you wished it had. But you keep going — not because the conflict is resolved, but because something inside refuses to let you give up. That's both your burden and your strength.",
    },
    strength: { ko: "무너지면서도 다시 일어서는 끈기와 남모를 책임감.", en: "The tenacity to get back up even while breaking, and a responsibility no one else sees." },
    weakPoint: { ko: "자신의 죄책감 안에 갇혀 앞으로 나아가기 어려울 때가 있어요.", en: "You can get trapped inside your guilt and struggle to move forward." },
    friendSays: { ko: "넌 왜 그렇게 스스로를 힘들게 해. 그래도 멈추지 않는 건 대단해.", en: "Why do you make it so hard on yourself. But the fact that you never stop is remarkable." },
    shareLine: { ko: "나 진격 테스트에서 라이너 나왔다. 두 자신 사이에서 무너지면서도 멈추지 않는 사람이래.", en: "I got Reiner — someone who keeps going even while collapsing between two selves." },
    emoji: "🛡️",
    color: "#8A7440",
  },
  {
    key: "bertholdt",
    name: { ko: "베르톨트 후버", en: "Bertholdt Hoover" },
    oneLiner: { ko: "감정을 꾹 눌러놓고 뒤에서 묵묵히 따르는 사람", en: "Someone who suppresses their feelings and silently follows from behind." },
    description: {
      ko: "당신은 다른 사람이 앞장서는 동안 자신의 감정을 조용히 안에서 삭이는 경향이 있습니다. 무관심한 게 아니에요. 모든 것을 깊이 느끼지만, 그것을 드러내는 것이 거의 불가능하게 느껴집니다. 느끼는 것과 말하는 것 사이의 거리가 너무 멀어져 결국 그게 당신을 집어삼킬 수 있어요. 당신의 충성은 침묵 속에서, 절대적입니다.",
      en: "You tend to swallow your feelings quietly inside while others take the lead. It's not indifference — you feel everything deeply — but expressing it feels nearly impossible. The distance between what you feel and what you say can grow until it swallows you whole. Your loyalty is silent, and absolute.",
    },
    strength: { ko: "흔들리지 않는 충성심과 드러내지 않는 깊은 감정.", en: "Unshakeable loyalty and deep feelings you keep entirely to yourself." },
    weakPoint: { ko: "억눌린 감정이 쌓이다 결정적인 순간에 터질 수 있어요.", en: "Suppressed feelings can build until they break at the worst moment." },
    friendSays: { ko: "넌 말이 없는데 옆에 항상 있더라. 그게 사실 제일 든든해.", en: "You don't say anything, but you're always there. That's actually the most reassuring thing." },
    shareLine: { ko: "나 진격 테스트에서 베르톨트 나왔다. 감정을 꾹 눌러놓고 묵묵히 따르는 사람이래.", en: "I got Bertholdt — someone who suppresses their feelings and silently follows from behind." },
    emoji: "💨",
    color: "#4A7878",
  },
  {
    key: "annie",
    name: { ko: "애니 레온하트", en: "Annie Leonhart" },
    oneLiner: { ko: "차갑고 고독하지만 그 안에 누구보다 깊은 감정을 품은 사람", en: "Cold and solitary, yet holding deeper feelings inside than anyone." },
    description: {
      ko: "당신은 외부적인 이유가 생기기 훨씬 전부터 스스로 벽을 쌓았습니다. 사람들은 냉정함을 보고, 당신은 그것을 훈련이라 부릅니다. 고립을 보고, 당신은 효율이라 부릅니다. 하지만 그 모든 훈련과 얼음 뒤에 아직도 싸워야 했던 이유를 기억하는 사람이 있고, 그래서 모든 것이 아픕니다.",
      en: "You built walls around yourself long before there was any external reason to. People see coldness; you call it discipline. People see isolation; you call it efficiency. But behind all that training and ice, there's someone who still remembers what they were supposed to be fighting for — and that's why everything hurts.",
    },
    strength: { ko: "어떤 상황에서도 흔들리지 않는 자기 단련과 냉정한 판단.", en: "Unshakeable self-discipline and cold judgment in any situation." },
    weakPoint: { ko: "감정을 너무 눌러서 정작 자신이 무너질 때 혼자가 될 수 있어요.", en: "Suppressing feelings so much can leave you alone when you finally break." },
    friendSays: { ko: "넌 차갑다고들 하는데 나는 그 안에 뭔가 있다는 거 알아.", en: "People say you're cold, but I know there's something inside all of that." },
    shareLine: { ko: "나 진격 테스트에서 애니 나왔다. 차갑지만 그 안에 누구보다 깊은 감정을 품은 사람이래.", en: "I got Annie — cold and solitary, but holding deeper feelings inside than anyone." },

    emoji: "❄️",
    color: "#7EB7CA",
  },
  {
    key: "zeke",
    name: { ko: "지크 예거", en: "Zeke Yeager" },
    oneLiner: { ko: "고통의 근원을 뿌리째 없애려는 냉철한 지성의 소유자", en: "A cold intellect who seeks to eliminate the very root of suffering." },
    description: {
      ko: "당신은 세상을 시스템과 결과의 관점으로 보고, 대부분의 경우 다른 사람들보다 몇 수 앞에 있습니다. 고통은 원천부터 제거되어야 한다고 믿으며, 그것을 위해 다른 사람들에게는 끔찍하게 보이는 결정도 내릴 수 있어요. '차갑다'는 말도 부족합니다. 당신은 고통으로 철학을 만든 사람이에요.",
      en: "You see the world through the lens of systems and consequences, and you're usually several moves ahead of everyone else. You believe suffering must be eliminated at its source, and you can make decisions that look monstrous to others in service of that belief. 'Cold' doesn't begin to cover it: you've turned your pain into a philosophy.",
    },
    strength: { ko: "시스템적 사고와 감정을 배제한 냉철한 장기 전략.", en: "Systematic thinking and cold long-term strategy free from emotion." },
    weakPoint: { ko: "수단이 너무 극단적이어서 가장 소중한 것들을 잃을 수 있어요.", en: "Your means can be so extreme that you lose the very things that matter most." },
    friendSays: { ko: "넌 항상 몇 수 앞을 보는데, 그게 때론 무서워.", en: "You're always several moves ahead, and sometimes that's frightening." },
    shareLine: { ko: "나 진격 테스트에서 지크 나왔다. 고통의 근원을 없애려는 냉철한 지성이래.", en: "I got Zeke — a cold intellect who seeks to eliminate the very root of all suffering." },
    emoji: "🧠",
    color: "#4C5F78",
  },
  {
    key: "pieck",
    name: { ko: "피크 핑거", en: "Pieck Finger" },
    oneLiner: { ko: "어떤 상황도 빠르게 읽고 적응하는 냉정한 실용주의자", en: "A calm pragmatist who reads any situation fast and adapts." },
    description: {
      ko: "당신은 쉽게 당황하지 않습니다. 이미 모든 각도를 고려해봤으니까요. 당황하지 않고, 도덕적으로 따지지 않고, 그냥 가장 좋은 길을 찾습니다. 사람들이 당신이 얼마나 신경 쓰는지 과소평가하는 건 감정으로 보여주지 않기 때문입니다. 대신 능숙함으로 보여줘요. 그게 당신 방식의 사랑입니다.",
      en: "You're hard to rattle because you've already considered every angle. You don't panic, you don't moralize, you just find the best route through. People underestimate how much you care because you never show it through emotion — you show it through competence. That's your version of love.",
    },
    strength: { ko: "빠른 상황 파악과 어떤 역할도 소화하는 유연한 실용주의.", en: "Fast situational reading and flexible pragmatism that handles any role." },
    weakPoint: { ko: "감정을 내비치지 않아 진심이 전달되지 않을 때가 있어요.", en: "Not showing emotion can mean your sincerity doesn't get through." },
    friendSays: { ko: "넌 항상 차분한데 실력으로 보여주더라. 그게 제일 믿음직해.", en: "You're always calm and show it through what you do. That's the most trustworthy thing." },
    shareLine: { ko: "나 진격 테스트에서 피크 나왔다. 상황을 빠르게 읽고 적응하는 냉정한 실용주의자래.", en: "I got Pieck — a calm pragmatist who reads any situation fast and adapts." },
    emoji: "🦊",
    color: "#8C6B4A",
  },
  {
    key: "falco",
    name: { ko: "팔코 글라이스", en: "Falco Grice" },
    oneLiner: { ko: "아무 계산 없이, 그냥 선한 사람", en: "Without any calculation — just genuinely good." },
    description: {
      ko: "당신은 복잡하게 생각하지 않습니다. 누가 도움이 필요하면 돕습니다. 누가 잘못된 방향으로 가면 말합니다. 인정받기 위해서도, 결과를 계산해서도 아닙니다. 그냥 옳은 것이기 때문에, 당신은 그 외의 방식을 생각할 수 없어요. 그런 순수함은 어떤 힘보다 드뭅니다.",
      en: "You don't overthink it. Someone needs help, you help. Someone's going the wrong way, you say so. Not for recognition, not because you calculated consequences — because it's right, and you can't imagine being any other way. That kind of purity is rarer than any power.",
    },
    strength: { ko: "계산 없는 선함과 망설임 없이 내미는 손.", en: "Unconditional goodness and a hand extended without hesitation." },
    weakPoint: { ko: "순수한 마음이 때로는 세상의 복잡함에 상처받을 수 있어요.", en: "Your pure heart can sometimes be hurt by the world's complexity." },
    friendSays: { ko: "넌 진짜 착한 거잖아. 계산하는 거 아니잖아 분명히.", en: "You're genuinely good. You're clearly not calculating any of it." },
    shareLine: { ko: "나 진격 테스트에서 팔코 나왔다. 아무 계산 없이 그냥 선한 사람이래.", en: "I got Falco — without any calculation, just genuinely good." },

    emoji: "🕊️",
    color: "#5B9FCC",
  },
  {
    key: "gabi",
    name: { ko: "가비 브라운", en: "Gabi Braun" },
    oneLiner: { ko: "인정받기 위해 누구보다 치열하게 달리는 사람", en: "Someone who runs harder than anyone else to earn recognition." },
    description: {
      ko: "당신은 누구보다 빠르게 달리고 의심을 위해 멈추지 않습니다. 무언가를 증명해야 하고, 그 긴박감이 모든 것을 이끕니다. 가끔 지치고 세상이 생각보다 복잡하다는 걸 알게 되지만, 그 강렬함은 진짜입니다. 그저 에너지를 어디에 쏟을지 배울 필요가 있을 뿐이에요.",
      en: "You run harder than anyone and don't stop to doubt. You need to prove something, and that urgency drives everything. It's tiring sometimes, and the world turns out to be more complicated than you thought, but that intensity is real. You just need to learn where to aim it.",
    },
    strength: { ko: "누구도 따라오기 힘든 강렬한 추진력과 목표를 향한 집념.", en: "An intensity and drive toward your goal that's nearly impossible to match." },
    weakPoint: { ko: "너무 빠르게 달리다 보면 넓게 보는 것을 놓칠 수 있어요.", en: "Running so hard can make you miss the bigger picture." },
    friendSays: { ko: "넌 진짜 열심히 해. 그 에너지가 어디서 나오는지 모르겠어.", en: "You work so hard. I have no idea where all that energy comes from." },
    shareLine: { ko: "나 진격 테스트에서 가비 나왔다. 인정받기 위해 누구보다 치열하게 달리는 사람이래.", en: "I got Gabi — someone who runs harder than anyone else to earn recognition." },
    emoji: "🔥",
    color: "#C04040",
  },
  {
    key: "kenny",
    name: { ko: "케니 아커만", en: "Kenny Ackerman" },
    oneLiner: { ko: "남의 룰 없이 오직 자기 기준으로만 사는 사람", en: "Someone who lives only by their own code, no one else's rules." },
    description: {
      ko: "당신은 누구의 인정도 필요로 하지 않고, 그 사실과 화해했습니다. 자기만의 법칙으로 살고, 사회의 것도, 다른 누구의 것도 아닙니다. 그것이 대부분의 사람들이 찾지 못하는 종류의 자유를 줍니다. 당신이 차갑지 않은 건, 그냥 자기 방식으로, 자기 조건으로, 보통 아무도 보지 않을 때 표현할 뿐이에요.",
      en: "You've never needed anyone's approval, and you've made peace with that. You live by your own code — not society's, not anyone else's — and that gives you a kind of freedom most people never find. You're not heartless; you just express things in your own way, on your own terms, usually when no one's watching.",
    },
    strength: { ko: "어떤 권위에도 흔들리지 않는 자기만의 기준과 삶의 방식.", en: "Your own standard and way of life that bends to no authority." },
    weakPoint: { ko: "혼자 가는 길이 때론 너무 외로울 수 있어요.", en: "The path you walk alone can sometimes be very lonely." },
    friendSays: { ko: "넌 남들 눈치 안 보는 거, 부럽기도 하고 걱정되기도 해.", en: "The way you don't care what anyone thinks is both enviable and worrying." },
    shareLine: { ko: "나 진격 테스트에서 케니 나왔다. 남의 룰 없이 자기 기준으로만 사는 사람이래.", en: "I got Kenny — someone who lives only by their own code, no one else's rules." },
    emoji: "🎩",
    color: "#5A5A5A",
  },
  {
    key: "marco",
    name: { ko: "마르코 보트", en: "Marco Bott" },
    oneLiner: { ko: "사람의 좋은 면을 먼저 보고 그걸로 팀을 이끄는 사람", en: "Someone who leads by seeing the best in people first." },
    description: {
      ko: "당신은 각 사람을 가치 있게 만드는 것이 무엇인지 보는 재능이 있습니다. 스스로도 보지 못하는 사람들에게서도요. 당신에게 리더십은 가장 강한 것이 되는 것이 아닙니다. 사람들을 충분히 이해해서 최선을 이끌어내는 것입니다. 세상은 당신처럼 이끄는 사람이 더 많이 필요합니다.",
      en: "You have a gift for seeing what makes each person valuable — even people who can't see it themselves. Leadership for you isn't about being the strongest; it's about understanding people well enough to bring out the best in them. The world needs more people who lead the way you do.",
    },
    strength: { ko: "사람을 읽는 따뜻한 시선과 팀을 하나로 묶는 자연스러운 리더십.", en: "A warm eye for people and natural leadership that brings a team together." },
    weakPoint: { ko: "남의 좋은 면만 보다가 위험 신호를 놓칠 수 있어요.", en: "Seeing only the best in others can cause you to miss warning signs." },
    friendSays: { ko: "넌 내가 내 장점을 보기 전에 먼저 보더라.", en: "You saw my strengths before I saw them myself." },
    shareLine: { ko: "나 진격 테스트에서 마르코 나왔다. 사람의 좋은 면을 먼저 보고 팀을 이끄는 사람이래.", en: "I got Marco — someone who leads by seeing the best in people first." },
    emoji: "⭐",
    color: "#C4A47C",
  },
];

// 히든: 유미르 프리츠(시조 유미르). 4개 문항의 은밀한 선택지를 전부 골라야만 발동.
// 약 1.5% 확률 (4문항 각 1/4 선택 기준).
const HIDDEN: AnimeResult = {
  key: "ymir_fritz",
  name: { ko: "유미르 프리츠", en: "Ymir Fritz" },
  oneLiner: { ko: "2000년을 침묵 속에 바쳐온, 격이 다른 비극의 존재", en: "A being of a different class — 2000 years of silent, boundless sacrifice." },
  description: {
    ko: "당신은 아주 드물게 나오는 결과입니다. 선택하지 않은 사슬에 묶인 채 2000년을 침묵 속에서 버텨온, 상상도 못 할 무게를 조용한 품위로 짊어진 사람. 당신은 힘이나 강함으로 정의되지 않습니다. 대가를 묻지 않고 모든 것을 내주는 능력, 그리고 그 무게를 드러내지 않는 방식으로 정의됩니다. 누군가 그 무게를 진심으로 알아보고, 쓸모가 아닌 당신 자체를 선택한다면 — 그것이 모든 것을 바꿉니다.",
    en: "You are an extraordinarily rare result. Bound by chains you did not choose, enduring 2000 years of silence, carrying unimaginable weight with quiet dignity. You are not defined by power or strength — but by your capacity to give everything without asking what it costs, and to carry that weight without ever showing it. When someone truly sees that weight and chooses you, not your usefulness — that changes everything.",
  },
  strength: { ko: "어떤 무게도 조용히 짊어지는 초인적인 인내와 끝없는 헌신.", en: "Superhuman endurance and boundless devotion that carries any weight in silence." },
  weakPoint: { ko: "스스로를 위한 자리가 없어, 자기 자신을 잃어버릴 수 있어요.", en: "Having no room for yourself, you risk losing who you are entirely." },
  friendSays: { ko: "넌… 그냥, 차원이 다르다. 진심으로.", en: "You're just… on a completely different level. I mean that sincerely." },
  shareLine: { ko: "나 진격 테스트에서 '유미르 프리츠' 나왔다. 2000년을 침묵으로 바쳐온 히든 결과래 ㄷㄷㄷ", en: "I got 'Ymir Fritz' on the AoT test — the hidden result of 2000 years of silent sacrifice. Insane." },
  emoji: "💎",
  color: "#7A4E8A",
};

// 문항 원칙: 각 문항의 4답 = 서로 다른 4인. 각 캐릭터 정확히 4개 문항 등장(최대 점수 4).
// 히든(유미르 프리츠) 트리거: Q3·Q8·Q11·Q17 각 1개 선택지에 hiddenWeights.ymir_fritz:1 부여.
// 4개 전부 선택 시 threshold(4) 도달 → 유미르 프리츠 발동.
const QUESTIONS: AnimeQuestion[] = [
  {
    id: "q1",
    prompt: { ko: "당신에게 가장 중요한 것은 무엇인가요?", en: "What matters most to you?" },
    choices: [
      { id: "a", text: { ko: "자유. 어떤 벽도, 어떤 대가도 나를 막을 수 없다", en: "Freedom. No wall, no cost, can stop me." }, weights: { eren: 1 } },
      { id: "b", text: { ko: "지켜야 할 한 사람. 그 사람이 살아 있는 한 나도 싸운다", en: "One person I must protect. As long as they live, so do I." }, weights: { mikasa: 1 } },
      { id: "c", text: { ko: "이해. 적을 알고 세상을 알아야 진짜 길이 보인다", en: "Understanding. You have to know the enemy and the world to find the real way." }, weights: { armin: 1 } },
      { id: "d", text: { ko: "결과. 감정 말고 최선의 방법으로 해내는 것", en: "Results. Get it done the best way, not the emotional way." }, weights: { levi: 1 } },
    ],
  },
  {
    id: "q2",
    prompt: { ko: "동료들과 전략을 짜는 자리, 당신은?", en: "You're in a meeting planning strategy with your team. You…" },
    choices: [
      { id: "a", text: { ko: "흥분해서 아이디어를 쏟아내다 가장 엉뚱한 방법을 제안한다", en: "Get excited, overflow with ideas, and propose the most unconventional method." }, weights: { hange: 1 } },
      { id: "b", text: { ko: "큰 그림을 먼저 그리고, 희생이 필요한 선택도 차분하게 제시한다", en: "Draw the big picture first, then calmly present choices that require sacrifice." }, weights: { erwin: 1 } },
      { id: "c", text: { ko: "현실적으로 가능한 것과 불가능한 것을 먼저 분류한다", en: "First separate what's actually possible from what isn't." }, weights: { jean: 1 } },
      { id: "d", text: { ko: "배는 고프지만, 결정적인 순간에 핵심 한마디를 꼭 던진다", en: "You're hungry, but at the critical moment, you always land the key remark." }, weights: { sasha: 1 } },
    ],
  },
  {
    id: "q3",
    prompt: { ko: "당신만 아는 비밀이 있습니다. 어떻게 하나요?", en: "You carry a secret only you know. What do you do?" },
    choices: [
      { id: "a", text: { ko: "혼자 끙끙 앓다가 결국 친한 친구한테 다 털어놓는다", en: "Agonize alone, then finally spill everything to a close friend." }, weights: { connie: 1 } },
      { id: "b", text: { ko: "태어날 때부터 주어진 운명처럼, 말없이 혼자 안고 간다", en: "Like a fate given at birth, I carry it alone without a word." }, weights: { historia: 1 }, hiddenWeights: { ymir_fritz: 1 } },
      { id: "c", text: { ko: "이 비밀이 나에게 유리한지 먼저 계산하고, 그래도 결국 혼자 짊어진다", en: "First calculate whether it benefits me, but end up shouldering it alone regardless." }, weights: { ymir: 1 } },
      { id: "d", text: { ko: "두 가지 삶 사이에서 갈라지는 기분이다. 언제까지 버텨야 할지 모른다", en: "It feels like being torn between two lives. I don't know how long I can hold on." }, weights: { reiner: 1 } },
    ],
  },
  {
    id: "q4",
    prompt: { ko: "개인의 감정과 임무 사이에서 갈등할 때 당신은?", en: "When you're torn between personal feelings and duty, you…" },
    choices: [
      { id: "a", text: { ko: "감정을 눌러 놓고 해야 할 일을 한다. 나중에 혼자 무너진다", en: "Suppress the feeling and do what needs doing. Then collapse alone later." }, weights: { bertholdt: 1 } },
      { id: "b", text: { ko: "감정은 임무를 방해할 뿐이다. 차갑게 끊어낸다", en: "Feelings only get in the way of the mission. I cut them off coldly." }, weights: { annie: 1 } },
      { id: "c", text: { ko: "장기적으로 더 많은 사람을 위한 선택이 무엇인지 먼저 계산한다", en: "First calculate which choice serves the most people in the long run." }, weights: { zeke: 1 } },
      { id: "d", text: { ko: "상황을 빠르게 읽고 현실적인 타협점을 찾는다", en: "Read the situation fast and find a realistic middle ground." }, weights: { pieck: 1 } },
    ],
  },
  {
    id: "q5",
    prompt: { ko: "당신이 행동하게 만드는 가장 근본적인 이유는?", en: "What is the most fundamental reason you act?" },
    choices: [
      { id: "a", text: { ko: "소중한 사람이 올바른 길을 걸을 수 있도록 곁에서 지키는 것", en: "To stay by the side of someone precious so they can walk the right path." }, weights: { falco: 1 } },
      { id: "b", text: { ko: "내가 선택받을 자격이 있음을 증명하는 것", en: "To prove I'm worthy of being chosen." }, weights: { gabi: 1 } },
      { id: "c", text: { ko: "내 방식대로, 내 길대로 살기 위해", en: "To live my way, on my own terms." }, weights: { kenny: 1 } },
      { id: "d", text: { ko: "동료들이 각자의 강점을 믿고 앞으로 나아갈 수 있도록", en: "So my comrades can believe in their own strengths and move forward." }, weights: { marco: 1 } },
    ],
  },
  {
    id: "q6",
    prompt: { ko: "처음 보는 강한 적이 나타났습니다. 당신의 첫 반응은?", en: "A powerful enemy you've never seen appears. Your first reaction?" },
    choices: [
      { id: "a", text: { ko: "분노가 치밀어 오른다. 생각보다 몸이 먼저 달려든다", en: "Rage rises up. My body charges before my mind does." }, weights: { eren: 1 } },
      { id: "b", text: { ko: "어떤 능력을 가졌는지 궁금하다. 먼저 관찰하고 싶다", en: "I'm curious what abilities they have. I want to observe first." }, weights: { hange: 1 } },
      { id: "c", text: { ko: "적이지만 어쩔 수 없는 사정이 있을 거라고 생각한다", en: "Even if they're the enemy, they probably had reasons they couldn't help." }, weights: { reiner: 1 } },
      { id: "d", text: { ko: "감정 없이 상황을 파악한다. 이길 수 있는지 계산이 먼저다", en: "I assess the situation without emotion. First I calculate whether I can win." }, weights: { annie: 1 } },
    ],
  },
  {
    id: "q7",
    prompt: { ko: "중요한 사람을 지키기 위해 무언가를 포기해야 한다면?", en: "If you had to give something up to protect someone important, you…" },
    choices: [
      { id: "a", text: { ko: "내 모든 것을 포기해도 상관없다. 그 사람이 살아 있으면 된다", en: "I don't mind giving up everything I have. As long as they're alive." }, weights: { mikasa: 1 } },
      { id: "b", text: { ko: "개인의 감정과 행복은 내려놓는다. 더 큰 목표가 있다", en: "I set down my personal feelings and happiness. There's a bigger goal." }, weights: { erwin: 1 } },
      { id: "c", text: { ko: "포기하는 게 너무 어렵다. 다 붙잡으려다 오히려 무너질 것 같다", en: "Giving anything up is so hard. Trying to hold everything, I might just fall apart." }, weights: { connie: 1 } },
      { id: "d", text: { ko: "말없이 따라간다. 내 감정을 드러내는 건 사치 같다", en: "I follow silently. Showing my feelings feels like a luxury I can't afford." }, weights: { bertholdt: 1 } },
    ],
  },
  {
    id: "q8",
    prompt: { ko: "팀이 위기에 빠졌을 때 당신이 가장 먼저 하는 것은?", en: "When your team falls into crisis, the first thing you do is…" },
    choices: [
      { id: "a", text: { ko: "모든 가능성을 빠르게 훑어 아무도 생각 못 한 방법을 찾는다", en: "Scan every possibility fast and find a solution no one else thought of." }, weights: { armin: 1 } },
      { id: "b", text: { ko: "현실적으로 살아남을 수 있는 선택지를 냉정하게 계산한다", en: "Calculate the realistic options for survival, coldly." }, weights: { jean: 1 } },
      { id: "c", text: { ko: "내가 살아야 소중한 사람도 지킬 수 있다. 생존이 먼저다", en: "I have to survive to protect the one I care about. Survival comes first." }, weights: { ymir: 1 } },
      { id: "d", text: { ko: "감정을 배제하고, 전체 희생을 최소화할 냉정한 수를 둔다", en: "Set aside emotion and make the cold move that minimizes total sacrifice.", }, weights: { zeke: 1 }, hiddenWeights: { ymir_fritz: 1 } },
    ],
  },
  {
    id: "q9",
    prompt: { ko: "동료를 잃었습니다. 어떻게 이겨냅니까?", en: "You've lost a comrade. How do you get through it?" },
    choices: [
      { id: "a", text: { ko: "슬픔을 안으로 삭이고, 다음 전투에 더 집중한다", en: "Swallow the grief inside and focus harder on the next fight." }, weights: { levi: 1 } },
      { id: "b", text: { ko: "맛있는 거 먹으면서 잠깐 울고, 다시 웃으면서 앞으로 간다", en: "Eat something good, cry a little, then smile and move forward." }, weights: { sasha: 1 } },
      { id: "c", text: { ko: "조용히 혼자 운다. 그리고 남겨진 사람들을 먼저 챙긴다", en: "Cry quietly alone. Then take care of the people left behind first." }, weights: { historia: 1 } },
      { id: "d", text: { ko: "감상에 빠지기보다 살아남아서 의미 있게 쓰이는 게 최선이다", en: "Rather than dwell in grief, the best thing is to survive and be put to good use." }, weights: { pieck: 1 } },
    ],
  },
  {
    id: "q10",
    prompt: { ko: "혼자 있는 시간에 당신은?", en: "What do you do with time alone?" },
    choices: [
      { id: "a", text: { ko: "소중한 사람이 지금 어디서 뭘 하는지, 괜찮은지 걱정하며 보낸다", en: "Spend it worrying about what the person I care about is doing and whether they're okay." }, weights: { falco: 1 } },
      { id: "b", text: { ko: "지금보다 더 강해지기 위해 무엇을 해야 할지 생각한다", en: "Think about what I need to do to become stronger than I am now." }, weights: { gabi: 1 } },
      { id: "c", text: { ko: "아무도 상관 않는 곳에서 내 방식대로 쉰다", en: "Rest my own way somewhere no one interferes." }, weights: { kenny: 1 } },
      { id: "d", text: { ko: "동료들이 어떻게 지내는지 한 명씩 떠올린다", en: "Think through my comrades one by one, wondering how they're doing." }, weights: { marco: 1 } },
    ],
  },
  {
    id: "q11",
    prompt: { ko: "엄청난 힘이 주어진다면 당신은?", en: "If you were given enormous power, you would…" },
    choices: [
      { id: "a", text: { ko: "세상의 모든 억압과 장벽을 부숴버리는 데 쓴다", en: "Use it to shatter every form of oppression and every wall in the world." }, weights: { eren: 1 } },
      { id: "b", text: { ko: "인류의 생존과 진실을 밝히는 데 전부 쏟아붓는다", en: "Pour it all into securing humanity's survival and uncovering the truth." }, weights: { erwin: 1 } },
      { id: "c", text: { ko: "목소리 없는 약한 사람들을 먼저 지키는 데 쓴다", en: "Use it first to protect the weak who have no voice.", }, weights: { historia: 1 }, hiddenWeights: { ymir_fritz: 1 } },
      { id: "d", text: { ko: "이 힘이 짐처럼 느껴진다. 쓰고 싶지 않지만 어쩔 수 없다", en: "This power feels like a burden. I don't want to use it, but there's no choice." }, weights: { bertholdt: 1 } },
    ],
  },
  {
    id: "q12",
    prompt: { ko: "위기 속에서 당신의 생존 전략은?", en: "What's your survival strategy in a crisis?" },
    choices: [
      { id: "a", text: { ko: "몸이 먼저 움직인다. 계산보다 반사신경이 앞선다", en: "My body moves first. Instinct beats calculation." }, weights: { mikasa: 1 } },
      { id: "b", text: { ko: "감정 말고, 어떤 선택이 살아남을 확률이 높은지 따진다", en: "Set emotion aside and figure out which choice has the highest survival odds." }, weights: { jean: 1 } },
      { id: "c", text: { ko: "어떻게 해서든 살아야 한다. 체면보다 생존이 먼저다", en: "I have to survive no matter what. Survival before pride." }, weights: { ymir: 1 } },
      { id: "d", text: { ko: "상황에 맞게 빠르게 변한다. 유연함이 가장 큰 무기다", en: "I adapt fast to the situation. Flexibility is my biggest weapon." }, weights: { pieck: 1 } },
    ],
  },
  {
    id: "q13",
    prompt: { ko: "곤경에 처한 사람을 보면 당신은?", en: "When you see someone in trouble, you…" },
    choices: [
      { id: "a", text: { ko: "어떻게 도울 수 있을지 방법을 빠르게 찾는다", en: "Quickly find a way to help." }, weights: { armin: 1 } },
      { id: "b", text: { ko: "생각보다 몸이 먼저 달려간다. 뭐라도 나눠주고 싶다", en: "My body runs before my mind does. I want to share something, anything." }, weights: { sasha: 1 } },
      { id: "c", text: { ko: "돕고 싶지만 내 죄책감이 먼저 올라온다. 그래도 결국 나선다", en: "I want to help, but my guilt rises first. Still, I step in eventually." }, weights: { reiner: 1 } },
      { id: "d", text: { ko: "망설임 없이 나선다. 당연히 해야 하는 일이다", en: "I step up without hesitation. It's just the obvious thing to do." }, weights: { falco: 1 } },
    ],
  },
  {
    id: "q14",
    prompt: { ko: "팀 안에서 당신의 자연스러운 역할은?", en: "What's your natural role on a team?" },
    choices: [
      { id: "a", text: { ko: "말보다 행동으로 보여주는 사람. 필요하면 냉정하게 결단을 내린다", en: "Lead by action, not words. Make cold decisions when necessary." }, weights: { levi: 1 } },
      { id: "b", text: { ko: "에너지와 아이디어로 팀에 활기를 불어넣는 사람", en: "The one who breathes energy and ideas into the team." }, weights: { hange: 1 } },
      { id: "c", text: { ko: "옆에서 분위기를 풀어주고, 누가 힘들어도 알아채는 사람", en: "The one who lightens the mood and notices when someone's struggling." }, weights: { connie: 1 } },
      { id: "d", text: { ko: "최선을 다해 팀을 이끌고, 기대 이상의 결과를 만들어내는 사람", en: "Drive the team hard and produce results beyond what's expected." }, weights: { gabi: 1 } },
    ],
  },
  {
    id: "q15",
    prompt: { ko: "세상을 바라보는 당신의 방식은?", en: "How do you see the world?" },
    choices: [
      { id: "a", text: { ko: "세상은 원래 가혹하다. 살아남는 자만이 옳다", en: "The world is inherently harsh. Only the survivors are right." }, weights: { annie: 1 } },
      { id: "b", text: { ko: "세상의 구조 자체가 잘못됐다. 근본부터 바꿔야 한다", en: "The very structure of the world is wrong. It needs to be changed from the root." }, weights: { zeke: 1 } },
      { id: "c", text: { ko: "남의 룰보다 내 룰로 산다. 내 가치관이 나의 기준이다", en: "I live by my rules, not anyone else's. My values are my standard." }, weights: { kenny: 1 } },
      { id: "d", text: { ko: "사람들은 근본적으로 선하다. 서로 이해하면 길이 보인다", en: "People are fundamentally good. Understanding each other shows the way." }, weights: { marco: 1 } },
    ],
  },
  {
    id: "q16",
    prompt: { ko: "계획이 완전히 틀어졌을 때 당신은?", en: "When the plan completely falls apart, you…" },
    choices: [
      { id: "a", text: { ko: "아무리 힘들어도 계속 앞으로 나아간다. 멈추지 않는다", en: "Keep moving forward no matter how hard it gets. I don't stop." }, weights: { eren: 1 } },
      { id: "b", text: { ko: "지켜야 할 사람을 다시 떠올리며 중심을 잡는다", en: "Recall who I need to protect and find my center again." }, weights: { mikasa: 1 } },
      { id: "c", text: { ko: "빠르게 새 방법을 생각한다. 실패도 데이터다", en: "Think fast and find a new method. Failure is data too." }, weights: { hange: 1 } },
      { id: "d", text: { ko: "무너지는 것 같지만 옆에 있는 사람에게 기대 버틴다", en: "I feel like I'm collapsing, but I lean on the person beside me and hold on." }, weights: { bertholdt: 1 } },
    ],
  },
  {
    id: "q17",
    prompt: { ko: "소중한 사람을 위해 당신은 어디까지 할 수 있나요?", en: "How far would you go for someone precious to you?" },
    choices: [
      { id: "a", text: { ko: "목숨을 걸 수 있다. 살아서 돌아올 자신이 없어도 시도한다", en: "I'd risk my life. Even if I'm not sure I'd come back, I'd try." }, weights: { armin: 1 } },
      { id: "b", text: { ko: "나 자신을 전부 태워서라도 그 사람의 꿈을 이루게 한다", en: "I'd burn through everything I am so their dream can be realized.", }, weights: { erwin: 1 }, hiddenWeights: { ymir_fritz: 1 } },
      { id: "c", text: { ko: "내 미래 전부를 내줄 수 있다. 그 사람이 행복하면 그걸로 충분하다", en: "I'd give away my entire future. Their happiness is enough for me." }, weights: { ymir: 1 } },
      { id: "d", text: { ko: "가슴이 아파도 감정을 숨긴다. 표현 못 한 채 그냥 곁에 있는다", en: "Even if it hurts, I hide my feelings. I just stay beside them without saying a word." }, weights: { annie: 1 } },
    ],
  },
  {
    id: "q18",
    prompt: { ko: "힘든 훈련이나 어려운 과제를 앞에 두고 당신은?", en: "Faced with tough training or a hard task, you…" },
    choices: [
      { id: "a", text: { ko: "불평 없이 시작한다. 완벽하게 해내는 것만이 목표다", en: "Start without complaint. The only goal is to do it perfectly." }, weights: { levi: 1 } },
      { id: "b", text: { ko: "쓸모 있는 연습과 쓸모없는 연습을 먼저 구분한다", en: "First separate useful practice from useless practice." }, weights: { jean: 1 } },
      { id: "c", text: { ko: "투덜대면서도 친구들이랑 같이 버티면 어떻게든 된다", en: "Grumble through it, but get by with friends somehow." }, weights: { connie: 1 } },
      { id: "d", text: { ko: "몸보다 머리다. 전략적으로 힘을 써야 할 곳을 먼저 계산한다", en: "Mind over body. First calculate where to apply effort strategically." }, weights: { zeke: 1 } },
    ],
  },
  {
    id: "q19",
    prompt: { ko: "내면의 갈등과 마주할 때 당신은?", en: "When you face an inner conflict, you…" },
    choices: [
      { id: "a", text: { ko: "일단 맛있는 거 먹고 생각한다. 배고프면 아무것도 안 풀린다", en: "Eat something good first, then think. Nothing gets solved hungry." }, weights: { sasha: 1 } },
      { id: "b", text: { ko: "오래 혼자 안고 있다가, 결국 약한 사람들을 먼저 챙기며 내려놓는다", en: "Hold it alone for a long time, then finally let it go by looking after those weaker than me.", }, weights: { historia: 1 }, hiddenWeights: { ymir_fritz: 1 } },
      { id: "c", text: { ko: "혼란스러워도 '옳은 것은 무엇인가'를 붙잡고 버틴다", en: "Even in confusion, I hold onto 'what is right' and endure." }, weights: { falco: 1 } },
      { id: "d", text: { ko: "나만의 방식으로 직면한다. 누구의 도움도 없이", en: "I face it in my own way. Without anyone's help." }, weights: { kenny: 1 } },
    ],
  },
  {
    id: "q20",
    prompt: { ko: "당신에게 의무와 책임이란 무엇인가요?", en: "What do duty and responsibility mean to you?" },
    choices: [
      { id: "a", text: { ko: "도망치고 싶지만, 버린 채로는 살 수 없는 것", en: "Something I want to run from, but can't live with having abandoned." }, weights: { reiner: 1 } },
      { id: "b", text: { ko: "상황에 맞게 최선을 다하는 것. 감정에 흔들리지 않고", en: "Doing my best for the situation, without being swayed by emotion." }, weights: { pieck: 1 } },
      { id: "c", text: { ko: "무조건 다 해내야 하는 것. 실패는 없다", en: "Something I must carry out no matter what. Failure isn't an option." }, weights: { gabi: 1 } },
      { id: "d", text: { ko: "혼자 짊어지는 것이 아니라, 동료와 함께 나누는 것", en: "Not a weight to carry alone, but something shared with comrades." }, weights: { marco: 1 } },
    ],
  },
];

export const ATTACK_ON_TITAN_CONFIG: AnimeTestConfig = {
  testId: "attack-on-titan",
  path: "/tests/attack-on-titan",
  tone: "midnight",
  accent: "#A88B4A",
  ogBg: "linear-gradient(135deg, #0a0c08 0%, #1a1a0d 55%, #0a0c08 100%)",
  eyebrow: { ko: "나의 진격의 거인 캐릭터", en: "Your Attack on Titan Character" },
  gameName: { ko: "진격의 거인", en: "Attack on Titan" },
  title: { ko: "진격의 거인 캐릭터 테스트", en: "Attack on Titan Character Test" },
  subtitle: { ko: "나는 어떤 진격의 거인 캐릭터일까?", en: "Which Attack on Titan character are you?" },
  description: {
    ko: "20개의 상황 선택으로 엘런·미카사·아르민·리바이·한지·엘빈·장·사샤·라이너·애니·지크·팔코·가비 등 20명 중 나와 가장 닮은 캐릭터를 찾아드립니다. 아주 드물게 나오는 히든 결과 1종도 숨어 있어요.",
    en: "20 situation choices match you to one of 20 Attack on Titan characters — Eren, Mikasa, Armin, Levi, Hange, Erwin, Jean, Sasha, Reiner, Annie, Zeke, Falco, Gabi and more. Plus one ultra-rare hidden result.",
  },
  metaTitle: { ko: "진격의 거인 캐릭터 테스트 | 나는 어떤 캐릭터?", en: "Attack on Titan Character Test | Which AoT Character Are You?" },
  metaDescription: {
    ko: "20문항으로 알아보는 나의 진격의 거인 캐릭터. 엘런·미카사·아르민·리바이·한지 등 20명 중 나는? 아주 드물게 나오는 히든 결과 1종도 숨어 있어요.",
    en: "Find your Attack on Titan character in 20 questions. Which of 20 characters are you — Eren, Mikasa, Armin, Levi, Hange? One ultra-rare hidden result awaits.",
  },
  ogKicker: "ATTACK ON TITAN CHARACTER TEST",
  coverImage: "/images/tests/attack-on-titan/cover-og.jpg",
  results: RESULTS,
  hiddens: [HIDDEN],
  hiddenThreshold: 4,
  questions: QUESTIONS,
  recommendedIds: ["demon-slayer", "jujutsu-kaisen", "chainsaw-man", "cyberpunk"],
};
