import type { AnimeResult, AnimeQuestion, AnimeTestConfig } from "@/lib/anime-test";

// 일반 21명(켄자쿠 포함). 히든 2명(스쿠나=빌런 정점 / 리카=사랑 정점)은 config.hiddens 로 분리 — results[] 에 넣지 않는다.
const RESULTS: AnimeResult[] = [
  {
    key: "yuji",
    name: { ko: "이타도리 유지", en: "Yuji" },
    oneLiner: { ko: "정 많고 직진하는, 남을 위해 몸을 던지는 사람", en: "Warm-hearted and direct — you throw yourself in for others." },
    description: {
      ko: "당신은 정이 많고 솔직하게 직진하는 사람입니다. 곤란한 사람을 보면 그냥 못 지나치고, 내가 손해 보더라도 옳다고 믿는 쪽으로 움직입니다. 밝고 단순해 보여도 사실은 사람과 ‘제대로 사는 법’을 진지하게 고민하는 따뜻한 사람이에요.",
      en: "You're warm and refreshingly direct. You can't ignore someone in trouble, and you move toward what you believe is right even at a cost to yourself. You may look cheerful and simple, but you seriously care about people and doing right by them.",
    },
    strength: { ko: "남을 돕는 따뜻함과 행동력이 큽니다.", en: "Big-hearted and quick to act for others." },
    weakPoint: { ko: "남을 챙기다 자신을 희생할 수 있어요.", en: "You may sacrifice yourself while looking after others." },
    friendSays: { ko: "넌 손해 봐도 결국 옳은 쪽으로 가더라.", en: "Even at a loss, you always end up doing the right thing." },
    shareLine: { ko: "나 주술회전 테스트에서 이타도리 유지 나왔다.", en: "I got Yuji on the JJK character test." },
    emoji: "👊",
    color: "#E54B4B",
  },
  {
    key: "gojo",
    name: { ko: "고죠 사토루", en: "Gojo" },
    oneLiner: { ko: "압도적 자신감과 여유를 가진 천재", en: "A genius with overwhelming confidence and ease." },
    description: {
      ko: "당신은 실력에 대한 확신이 있고 웬만한 상황에선 여유를 잃지 않는 타입입니다. 장난기 넘치고 가벼워 보여도 정작 중요한 순간엔 누구보다 강하고 냉정합니다. 사람들을 이끌면서도 자기만의 방식을 고집하는 자유로운 천재예요.",
      en: "You trust your own ability and rarely lose your cool. You seem playful and breezy, yet in the moments that matter you're stronger and sharper than anyone. A free-spirited genius who leads while doing things your own way.",
    },
    strength: { ko: "실력과 여유, 위기에서의 침착함이 뛰어납니다.", en: "Skill, composure, and calm under pressure." },
    weakPoint: { ko: "여유가 지나쳐 방심으로 보일 수 있어요.", en: "Your ease can sometimes look like you've let your guard down." },
    friendSays: { ko: "넌 너무 잘나서 가끔 얄미워ㅋㅋ", en: "You're so good it's almost annoying, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 고죠 사토루 나왔다. 천재래ㅋ", en: "I got Gojo — the genius, apparently." },
    emoji: "🌀",
    color: "#5BC8E8",
  },
  {
    key: "megumi",
    name: { ko: "후시구로 메구미", en: "Megumi" },
    oneLiner: { ko: "무뚝뚝하지만 책임감 강한 전략가", en: "Blunt on the outside, a responsible strategist within." },
    description: {
      ko: "당신은 표현은 적지만 머릿속으로는 늘 상황을 계산하는 전략가입니다. 무뚝뚝해 보여도 옳다고 생각하는 사람은 끝까지 돕고, 자신의 역할에 대한 책임감이 강합니다. 감정보다 판단을 앞세우지만 속은 누구보다 진중한 사람이에요.",
      en: "You don't say much, but your mind is always calculating. You can seem cold, yet you help those you deem worth helping to the end, with a strong sense of duty. You lead with judgment over emotion, but you're deeply serious inside.",
    },
    strength: { ko: "냉정한 판단력과 책임감이 강합니다.", en: "Cool judgment and a strong sense of responsibility." },
    weakPoint: { ko: "감정을 잘 안 드러내 차가워 보일 수 있어요.", en: "Hiding emotion can make you seem cold." },
    friendSays: { ko: "넌 무뚝뚝한데 결국 다 챙기더라.", en: "You act blunt, but you take care of everyone in the end." },
    shareLine: { ko: "나 주술회전 테스트에서 후시구로 메구미 나왔다.", en: "I got Megumi on the JJK character test." },
    emoji: "🐺",
    color: "#2C3550",
  },
  {
    key: "nobara",
    name: { ko: "쿠기사키 노바라", en: "Nobara" },
    oneLiner: { ko: "흔들리지 않는 당당함과 소신의 소유자", en: "Unshakable confidence and conviction, all your own." },
    description: {
      ko: "당신은 남의 시선보다 ‘내가 나를 어떻게 보느냐’를 더 중요하게 여기는 당당한 사람입니다. 자신을 사랑할 줄 알고 하고 싶은 말은 분명하게 합니다. 쿨하고 자기 확신이 강해 함부로 휘둘리지 않아요. 그 단단함이 곧 당신의 매력입니다.",
      en: "You care more about how you see yourself than how others do. You know how to love yourself and you say what you mean. Cool and self-assured, you're not easily pushed around — and that firmness is your charm.",
    },
    strength: { ko: "자기 확신과 소신이 뚜렷합니다.", en: "Clear self-belief and conviction." },
    weakPoint: { ko: "당당함이 가끔 고집으로 비칠 수 있어요.", en: "Your confidence can occasionally read as stubbornness." },
    friendSays: { ko: "넌 남 눈치 안 보고 사는 게 멋있어.", en: "It's cool how you live without caring what others think." },
    shareLine: { ko: "나 주술회전 테스트에서 쿠기사키 노바라 나왔다. 당당함 인정.", en: "I got Nobara — unshakable confidence confirmed." },
    emoji: "🔨",
    color: "#E8853A",
  },
  {
    key: "nanami",
    name: { ko: "나나미 켄토", en: "Nanami" },
    oneLiner: { ko: "합리적이고 프로페셔널한 어른", en: "A rational, professional grown-up who values balance." },
    description: {
      ko: "당신은 감정에 휘둘리지 않고 합리적으로 판단하는 어른스러운 사람입니다. 일은 프로답게 확실히 처리하고 일과 삶의 균형도 중요하게 생각합니다. 불필요한 데 힘 빼지 않지만 지킬 사람과 원칙 앞에서는 누구보다 진지해집니다.",
      en: "You judge rationally without being swept by emotion — a true grown-up. You handle work like a pro and value work-life balance. You don't waste energy on the unnecessary, but you turn dead serious when it comes to your people and principles.",
    },
    strength: { ko: "합리적 판단과 프로다운 책임감이 있습니다.", en: "Rational judgment and professional reliability." },
    weakPoint: { ko: "선을 분명히 그어 다소 딱딱해 보일 수 있어요.", en: "Your firm boundaries can seem a bit rigid." },
    friendSays: { ko: "넌 진짜 믿고 맡길 수 있는 어른이야.", en: "You're the kind of adult people actually rely on." },
    shareLine: { ko: "나 주술회전 테스트에서 나나미 켄토 나왔다. 어른 of 어른.", en: "I got Nanami — the grown-up's grown-up." },
    emoji: "⏱️",
    color: "#B8975A",
  },
  {
    key: "yuta",
    name: { ko: "옷코츠 유타", en: "Yuta" },
    oneLiner: { ko: "다정하지만 누구보다 강한 헌신의 순애파", en: "Gentle, devoted — and stronger than anyone when it counts." },
    description: {
      ko: "당신은 평소엔 부드럽고 다정하지만, 소중한 사람을 위해서라면 가진 모든 걸 거는 헌신형입니다. 한번 마음을 주면 끝까지 가고, 그 사람을 지키는 일 앞에선 누구보다 강해지죠. 순수한 마음과 숨은 저력을 동시에 가진, 반전 매력의 소유자예요.",
      en: "You're soft and gentle most of the time, but you'll stake everything for the people you love. Once you give your heart, you go all the way, and protecting that person makes you stronger than anyone. You carry a pure heart and hidden power at the same time.",
    },
    strength: { ko: "헌신적인 다정함과 숨은 강함을 함께 가졌습니다.", en: "Devoted warmth paired with hidden strength." },
    weakPoint: { ko: "한 사람에게 너무 마음을 쏟을 수 있어요.", en: "You can pour too much of yourself into one person." },
    friendSays: { ko: "넌 순둥이인데 소중한 사람 일이면 눈빛이 달라져.", en: "You're a softie, but your eyes change when it's about someone you love." },
    shareLine: { ko: "나 주술회전 테스트에서 옷코츠 유타 나왔다. 다정한 강자래", en: "I got Yuta — the gentle powerhouse." },
    emoji: "🗡️",
    color: "#4A5BA0",
  },
  {
    key: "toji",
    name: { ko: "후시구로 토우지", en: "Toji" },
    oneLiner: { ko: "무심하고 실력만 보는 자유로운 프리랜서", en: "Detached, strength-only, a free-roaming freelancer." },
    description: {
      ko: "당신은 군더더기 없이 실력과 결과만 보는 쿨한 타입입니다. 남의 평가나 분위기에 얽매이지 않고, 자기 기준에 맞으면 움직이고 아니면 신경 끄죠. 어디에도 매이지 않는 자유로움과, 한번 나서면 확실히 끝내는 실력이 당신의 매력입니다.",
      en: "You look only at skill and results, with no fuss. You're not bound by others' opinions or the mood of the room — you move when it fits your standard and tune out when it doesn't. Your charm is that untethered freedom, plus the ability to finish the job for sure once you step in.",
    },
    strength: { ko: "흔들림 없는 실력과 얽매이지 않는 자유로움이 있습니다.", en: "Solid skill and an unbound, free spirit." },
    weakPoint: { ko: "무심함이 차갑게 비칠 수 있어요.", en: "Your detachment can come off as cold." },
    friendSays: { ko: "넌 관심 없는 척하면서 할 건 다 하더라ㅋㅋ", en: "You act like you don't care, but you get it all done, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 후시구로 토우지 나왔다. 실력파 프리랜서ㄷㄷ", en: "I got Toji — the strength-only freelancer." },
    emoji: "🔪",
    color: "#3A3A3A",
  },
  {
    key: "maki",
    name: { ko: "젠인 마키", en: "Maki" },
    oneLiner: { ko: "정해진 틀을 거부하고 노력으로 증명하는 반골", en: "A rebel who rejects the mold and proves it through effort." },
    description: {
      ko: "당신은 주어진 환경이나 정해진 틀에 순순히 따르지 않고, 자기 힘으로 증명해내는 사람입니다. 누구에게도 기대지 않고 남들보다 몇 배의 노력으로 길을 뚫죠. 독립심이 강하고 굽히지 않는 그 근성이, 당신을 더 단단하게 만들어요.",
      en: "You don't meekly follow the environment you're handed or the mold others set — you prove yourself by your own strength. You lean on no one and carve your path with several times the effort. That fierce independence and refusal to bend make you tougher than most.",
    },
    strength: { ko: "독립심과 노력으로 밀어붙이는 근성이 있습니다.", en: "Independence and grit that pushes through with effort." },
    weakPoint: { ko: "혼자 다 해내려다 무리할 수 있어요.", en: "Trying to do it all alone can wear you out." },
    friendSays: { ko: "넌 안 된다는 말을 제일 싫어하더라.", en: "You hate the words 'you can't' more than anything." },
    shareLine: { ko: "나 주술회전 테스트에서 젠인 마키 나왔다. 노력으로 증명하는 반골ㄷㄷ", en: "I got Maki — the rebel who proves it through effort." },
    emoji: "🎋",
    color: "#5B7B52",
  },
  {
    key: "choso",
    name: { ko: "쵸소우", en: "Choso" },
    oneLiner: { ko: "우직하게 제 사람을 지키는 든든한 맏형", en: "An earnest big brother who guards his people, no matter what." },
    description: {
      ko: "당신은 말보다 행동으로 사람을 챙기는 우직한 맏형 같은 사람입니다. 한번 ‘내 사람’이라고 정하면 끝까지 지키고, 손해를 보더라도 의리를 저버리지 않죠. 무뚝뚝하고 순박해 보여도 그 진심과 보호 본능이 주변을 안심시키는 타입이에요.",
      en: "You look after people through action more than words — earnest, like a reliable big brother. Once someone is 'yours,' you protect them to the end and never betray that loyalty, even at a cost. You may seem gruff and plain, but your sincerity and protective instinct put everyone at ease.",
    },
    strength: { ko: "변치 않는 의리와 든든한 보호 본능이 있습니다.", en: "Unwavering loyalty and a dependable protective instinct." },
    weakPoint: { ko: "정에 약해 손해를 감수할 때가 많아요.", en: "Your soft heart often makes you take the loss." },
    friendSays: { ko: "넌 말은 없어도 네 사람은 끝까지 지키더라.", en: "You say little, but you guard your people to the very end." },
    shareLine: { ko: "나 주술회전 테스트에서 쵸소우 나왔다. 든든한 맏형이래", en: "I got Choso — the dependable big brother." },
    emoji: "🩸",
    color: "#7A3A4A",
  },
  {
    key: "meimei",
    name: { ko: "메이메이", en: "Meimei" },
    oneLiner: { ko: "철저히 실리를 챙기는 냉정한 현실주의자", en: "A cool realist who always secures the practical gain." },
    description: {
      ko: "당신은 감정보다 실리를 먼저 따지는 냉정한 현실주의자입니다. 손익을 정확히 계산하고, 자신에게 이득이 되는 선택을 망설임 없이 합니다. 가벼운 다크 유머로 분위기를 풀 줄도 알죠. 똑부러진 판단과 자기 관리로 어떤 상황에서도 손해 보지 않는 타입이에요.",
      en: "You weigh practicality before emotion — a cool realist. You calculate gains and losses precisely and make the choice that benefits you without hesitation. You can also lighten the room with a bit of dark humor. With sharp judgment and self-management, you rarely come out behind.",
    },
    strength: { ko: "냉정한 손익 계산과 똑부러진 자기 관리가 있습니다.", en: "Cool cost-benefit sense and sharp self-management." },
    weakPoint: { ko: "실리만 따지다 차갑게 보일 수 있어요.", en: "Focusing on gain alone can make you seem cold." },
    friendSays: { ko: "넌 손해 보는 선택은 절대 안 하더라ㅋㅋ", en: "You never once make the losing choice, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 메이메이 나왔다. 실리의 끝판왕ㄷㄷ", en: "I got Meimei — the pragmatist's pragmatist." },
    emoji: "🦅",
    color: "#8E7B2E",
  },
  {
    key: "mahito",
    name: { ko: "마히토", en: "Mahito" },
    oneLiner: { ko: "천진하게 웃으며 종잡을 수 없는 호기심의 소유자", en: "A childlike smile and an unpredictable, boundless curiosity." },
    description: {
      ko: "당신은 천진난만하게 웃지만 속을 종잡을 수 없는, 호기심 가득한 사람입니다. 정해진 규칙보다 ‘재밌어 보이는 것’에 끌리고, 사람과 세상을 관찰하며 자기만의 결론을 내리죠. 순수함과 예측 불가함을 동시에 가진, 묘하게 매력적인 타입이에요.",
      en: "You smile innocently, yet no one can quite read you — you're brimming with curiosity. You're drawn to whatever looks interesting over set rules, observing people and the world to reach your own conclusions. Pure and unpredictable at once, you're strangely magnetic.",
    },
    strength: { ko: "거침없는 호기심과 자유로운 발상이 있습니다.", en: "Fearless curiosity and free-roaming imagination." },
    weakPoint: { ko: "흥미를 좇다 선을 넘을 때가 있어요.", en: "Chasing your interest can lead you over the line." },
    friendSays: { ko: "넌 웃고 있는데 무슨 생각 하는지 진짜 모르겠어ㅋㅋ", en: "You're smiling, but I genuinely can't tell what you're thinking, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 마히토 나왔다. 종잡을 수 없는 호기심ㄷㄷ", en: "I got Mahito — pure unpredictable curiosity." },
    emoji: "🧵",
    color: "#5C8BAE",
  },
  {
    key: "geto",
    name: { ko: "게토 스구루", en: "Geto" },
    oneLiner: { ko: "흔들리지 않는 신념과 우아한 카리스마", en: "Unbending conviction and an elegant, magnetic command." },
    description: {
      ko: "당신은 자기만의 분명한 신념을 가지고, 그것을 우아하게 밀고 나가는 카리스마형입니다. 좀처럼 흥분하지 않고 차분한 태도로 사람들을 이끌죠. 한번 옳다고 정한 길은 누가 뭐래도 흔들리지 않습니다. 냉정함과 기품을 함께 갖춘, 묵직한 존재감의 소유자예요.",
      en: "You hold a clear conviction of your own and push it forward with elegance and command. You rarely get flustered, guiding people with a calm demeanor. Once you decide a path is right, nothing sways you. With composure and grace together, you carry a weighty presence.",
    },
    strength: { ko: "흔들리지 않는 신념과 사람을 이끄는 카리스마가 있습니다.", en: "Unshakable conviction and the charisma to lead." },
    weakPoint: { ko: "신념이 강해 고집으로 비칠 수 있어요.", en: "Such strong conviction can read as inflexibility." },
    friendSays: { ko: "넌 차분한데 묘하게 다들 너를 따르더라.", en: "You're calm, yet somehow everyone follows your lead." },
    shareLine: { ko: "나 주술회전 테스트에서 게토 스구루 나왔다. 신념의 카리스마ㄷㄷ", en: "I got Geto — conviction and charisma." },
    emoji: "🌃",
    color: "#4A3A63",
  },
  {
    key: "toge",
    name: { ko: "이누마키 토게", en: "Toge" },
    oneLiner: { ko: "말은 적지만 마음은 누구보다 깊은 사람", en: "Few words, but a heart deeper than anyone's." },
    description: {
      ko: "당신은 말수가 적고 표현을 아끼지만, 곁에 있는 사람을 향한 마음만큼은 누구보다 깊습니다. 굳이 길게 말하지 않아도 행동과 짧은 한마디로 진심을 전하고, 동료가 위험할 땐 망설임 없이 나섭니다. 조용한 배려가 몸에 밴, 속 깊은 사람이에요.",
      en: "You don't say much and you hold your words back, but your care for the people beside you runs deeper than anyone's. You get your sincerity across through actions and a few short words, and you step up without hesitation when a friend is in danger. Quiet thoughtfulness is second nature to you.",
    },
    strength: { ko: "말없이도 마음을 전하는 깊은 배려가 있습니다.", en: "Deep, wordless thoughtfulness." },
    weakPoint: { ko: "표현을 아껴 마음을 못 알아챌 때가 있어요.", en: "Holding back can leave your feelings unnoticed." },
    friendSays: { ko: "넌 말은 없는데 결정적일 때 꼭 옆에 있더라.", en: "You barely talk, but you're always there when it counts." },
    shareLine: { ko: "나 주술회전 테스트에서 이누마키 토게 나왔다. 과묵한데 속 깊은 사람이래.", en: "I got Toge — quiet, but deeply caring." },
    emoji: "🍙",
    color: "#5C7A99",
  },
  {
    key: "panda",
    name: { ko: "판다", en: "Panda" },
    oneLiner: { ko: "분위기를 풀어주는 듬직한 맏형 같은 사람", en: "The dependable big-sibling who lightens the mood." },
    description: {
      ko: "당신은 어떤 무리에 있든 분위기를 부드럽게 풀어주고, 힘들어하는 사람을 먼저 챙기는 듬직한 사람입니다. 장난스럽고 유쾌해 보여도 상황을 냉정하게 읽고 필요할 땐 진지하게 중심을 잡죠. 곁에 있으면 마음이 놓이는 든든한 맏형 같은 타입이에요.",
      en: "Wherever you are, you ease the mood and look out for whoever's struggling first. You seem playful and cheerful, but you read situations coolly and anchor the group when it counts. The reassuring big-sibling type everyone feels safe around.",
    },
    strength: { ko: "사람을 편하게 하고 중심을 잡는 듬직함이 있습니다.", en: "You put people at ease and steady the group." },
    weakPoint: { ko: "남을 챙기다 정작 자기 얘긴 잘 안 해요.", en: "Caring for others, you rarely talk about yourself." },
    friendSays: { ko: "넌 같이 있으면 편한데 은근 다 꿰뚫고 있더라.", en: "You're easy to be around, but you secretly see everything." },
    shareLine: { ko: "나 주술회전 테스트에서 판다 나왔다. 듬직한 맏형이래.", en: "I got Panda — the dependable big-sibling." },
    emoji: "🐼",
    color: "#5E5E68",
  },
  {
    key: "jogo",
    name: { ko: "죠고", en: "Jogo" },
    oneLiner: { ko: "신념이 뜨겁고 자존심이 강한 외골수", en: "Burning conviction and fierce pride — single-minded." },
    description: {
      ko: "당신은 자신이 믿는 가치를 위해 누구보다 뜨겁게 타오르는 사람입니다. 신념이 확고하고 자존심이 강해, 무시당하는 걸 가장 못 참죠. 감정을 숨기지 못해 욱할 때도 있지만, 그만큼 진심이고 한번 정한 길은 끝까지 밀고 나갑니다. 뜨거운 외골수 타입이에요.",
      en: "You burn hotter than anyone for the values you believe in. Your conviction is firm and your pride is fierce, so being looked down on is what you can least tolerate. You can't hide your feelings and sometimes flare up, but that's how sincere you are — once you choose a path you push it to the end.",
    },
    strength: { ko: "확고한 신념과 끝까지 밀어붙이는 뚝심이 있습니다.", en: "Firm conviction and the grit to push it through." },
    weakPoint: { ko: "자존심에 욱해 감정에 휘둘릴 수 있어요.", en: "Wounded pride can make you flare up and lose composure." },
    friendSays: { ko: "넌 무시당하는 거 진짜 못 참더라ㅋㅋ 근데 그게 멋있어.", en: "You really can't stand being looked down on, lol — but that's the cool part." },
    shareLine: { ko: "나 주술회전 테스트에서 죠고 나왔다. 신념 뜨거운 외골수래.", en: "I got Jogo — the hot-blooded, single-minded one." },
    emoji: "🌋",
    color: "#C2410C",
  },
  {
    key: "yuki",
    name: { ko: "츠쿠모 유키", en: "Yuki" },
    oneLiner: { ko: "근본을 바꾸려는 크고 자유로운 야심가", en: "A free, big-picture dreamer who wants to change the root." },
    description: {
      ko: "당신은 눈앞의 문제보다 근본을 바꾸는 것을 고민하는 큰 그림의 사람입니다. 자유분방하고 거침없지만, 그 속엔 세상을 바꾸려는 진지한 야심이 있죠. 틀에 얽매이지 않고 자기 신념대로 움직이는 당당함이 매력이고, 실력도 그만큼 확실한 타입이에요.",
      en: "You think about changing things at the root rather than just the problem in front of you — a big-picture person. You're free-spirited and unfiltered, but underneath is a serious ambition to change the world. Your charm is the boldness to move by your own beliefs, unbound by convention — and you've got the ability to back it up.",
    },
    strength: { ko: "큰 그림을 보는 시야와 거침없는 추진력이 있습니다.", en: "Big-picture vision and unflinching drive." },
    weakPoint: { ko: "큰 목표에 빠져 디테일을 놓칠 수 있어요.", en: "Chasing the big goal, you may miss the details." },
    friendSays: { ko: "넌 스케일이 다르더라. 생각하는 게 남들이랑 달라.", en: "You operate on a different scale — you think unlike anyone else." },
    shareLine: { ko: "나 주술회전 테스트에서 츠쿠모 유키 나왔다. 자유로운 야심가래.", en: "I got Yuki — the free-spirited dreamer." },
    emoji: "🌟",
    color: "#C2557A",
  },
  {
    key: "hakari",
    name: { ko: "하카리 킨지", en: "Hakari" },
    oneLiner: { ko: "판을 크게 거는, 자기 룰대로 사는 승부사", en: "A high-roller who bets big and lives by his own rules." },
    description: {
      ko: "당신은 남이 정한 틀이나 안전한 길보다, 자기만의 룰로 크게 거는 걸 즐기는 승부사형입니다. 자신감 넘치고 거침없으며, 한번 꽂히면 끝까지 밀어붙이죠. 겉은 반항적이고 제멋대로 같아도 자기 사람에겐 의외로 의리가 깊어요. 위기를 오히려 즐기는 강심장과 한 방의 배짱이 당신의 매력입니다.",
      en: "Rather than someone else's rules or the safe path, you're a gambler who enjoys betting big by your own code. You're confident and unflinching, and once you're hooked you push it to the very end. You look rebellious and do-as-you-please, but you're surprisingly loyal to your own people. Your charm is the steel nerve that enjoys risk and the guts to go all in.",
    },
    strength: { ko: "위기를 즐기는 강심장과 크게 거는 승부 배짱이 있습니다.", en: "A steel nerve that enjoys risk and the guts to bet big." },
    weakPoint: { ko: "판을 크게 키우다 한 번에 무너질 위험도 있어요.", en: "Betting big means you can also lose big in one shot." },
    friendSays: { ko: "넌 무모해 보이는데 결국 크게 한 방 터뜨리더라ㄷㄷ", en: "You look reckless, but you end up hitting the jackpot, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 하카리 킨지 나왔다. 판 크게 거는 승부사래", en: "I got Hakari — the high-roller who bets big." },
    emoji: "🎰",
    color: "#C0398E",
  },
  {
    key: "todo",
    name: { ko: "토도 아오이", en: "Todo" },
    oneLiner: { ko: "자기 철학대로 사는, 뜨겁고 의리 있는 형님", en: "A hot-blooded, loyal big-bro who lives by his own philosophy." },
    description: {
      ko: "당신은 에너지가 넘치고 자기만의 확고한 철학으로 사는 사람입니다. 좋아하는 건 거침없이 표현하고, 한번 인정한 사람은 끝까지 챙기는 의리파죠. 엉뚱하고 시끄러워 보여도 결정적인 순간엔 누구보다 핵심을 꿰뚫는 통찰을 보여줍니다. 곁에 있으면 힘이 나는, 든든한 형님 같은 타입이에요.",
      en: "You overflow with energy and live by a firm philosophy all your own. You express what you love without holding back, and once you accept someone you look after them to the end. You may seem eccentric and loud, but in the decisive moment you show insight that cuts to the core like no one else. The reassuring big-brother type who fires everyone up.",
    },
    strength: { ko: "넘치는 에너지와 사람을 끌어올리는 의리, 날카로운 통찰이 있습니다.", en: "Boundless energy, loyalty that lifts others, and sharp insight." },
    weakPoint: { ko: "마이웨이가 강해 가끔 주변을 당황시켜요.", en: "Your strong my-way streak can leave others bewildered." },
    friendSays: { ko: "넌 4차원인데 결정적일 때 제일 멋있는 말 하더라ㅋㅋ", en: "You're off in your own world, but you say the coolest thing when it counts, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 토도 아오이 나왔다. 의리 형님 인정ㄷㄷ", en: "I got Todo — the loyal big-bro, confirmed." },
    emoji: "💪",
    color: "#D9543E",
  },
  {
    key: "kashimo",
    name: { ko: "카시모 하지메", en: "Kashimo" },
    oneLiner: { ko: "최고의 승부 한 판을 좇는 전투광", en: "A battle-junkie chasing one ultimate fight." },
    description: {
      ko: "당신은 안정보다 짜릿한 승부 그 자체에 살아 있음을 느끼는 사람입니다. 평범한 일엔 흥미가 없고, 자신을 진심으로 불태울 수 있는 상대나 도전을 만났을 때 가장 빛나죠. 결과보다 그 과정의 전율을 즐기는 순수한 승부사. 한번 불붙으면 누구도 못 말리는 열정이 당신의 매력입니다.",
      en: "You feel alive in the thrill of the contest itself, more than in comfort. The ordinary bores you; you shine brightest when you meet an opponent or challenge that truly fires you up. A pure competitor who savors the rush of the process over the result. Once you're lit up, no one can stop your passion.",
    },
    strength: { ko: "한계를 즐기는 승부욕과 거침없는 추진력이 있습니다.", en: "A thrill-seeking drive to win and unstoppable momentum." },
    weakPoint: { ko: "승부에만 빠져 주변을 놓칠 수 있어요.", en: "Fixating on the fight can make you miss what's around you." },
    friendSays: { ko: "넌 진짜 빡센 거 만날 때 제일 신나하더라ㅋㅋ", en: "You get the most pumped exactly when things get brutal, lol." },
    shareLine: { ko: "나 주술회전 테스트에서 카시모 하지메 나왔다. 전투광 인정", en: "I got Kashimo — the battle-junkie, confirmed." },
    emoji: "⚡",
    color: "#7E5AC2",
  },
  {
    key: "higuruma",
    name: { ko: "히구루마 히로미", en: "Higuruma" },
    oneLiner: { ko: "옳고 그름을 차분히 가리는 정의로운 판단가", en: "A calm arbiter of right and wrong with a deep sense of justice." },
    description: {
      ko: "당신은 감정에 휩쓸리지 않고 옳고 그름을 차분히 따지는 사람입니다. 불공정한 일을 그냥 넘기지 못하고, 자기 신념에 따라 정당한 결론을 내리려 하죠. 한때 지쳐 무기력했더라도 지킬 가치를 찾으면 누구보다 진지하게 움직입니다. 냉철한 판단력과 따뜻한 정의감을 함께 가진 사람이에요.",
      en: "You weigh right and wrong calmly, without being swept by emotion. You can't let injustice slide, and you try to reach a just conclusion by your own convictions. Even if you once burned out and felt listless, once you find something worth protecting you move more earnestly than anyone. You carry cool judgment and a warm sense of justice at once.",
    },
    strength: { ko: "냉철한 판단력과 흔들리지 않는 정의감이 있습니다.", en: "Cool judgment and an unshakable sense of justice." },
    weakPoint: { ko: "옳음을 따지다 스스로를 너무 몰아붙일 수 있어요.", en: "Pursuing what's right, you may push yourself too hard." },
    friendSays: { ko: "넌 조용한데 불공정한 거 보면 눈빛이 달라져.", en: "You're quiet, but your eyes change when you see something unfair." },
    shareLine: { ko: "나 주술회전 테스트에서 히구루마 히로미 나왔다. 정의로운 판단가래", en: "I got Higuruma — the just arbiter." },
    emoji: "⚖️",
    color: "#45627A",
  },
  {
    key: "kenjaku",
    name: { ko: "켄자쿠", en: "Kenjaku" },
    oneLiner: { ko: "수면 아래에서 판 전체를 짜는 흑막형 책략가", en: "A mastermind who weaves the whole board from the shadows." },
    description: {
      ko: "당신은 눈앞의 승부보다 판 전체를 길게 내다보는 책략가형입니다. 원하는 결과를 위해 몇 수 앞을 미리 깔아두고, 감정에 휘둘리지 않고 호기심과 목적만으로 움직이죠. 누구도 눈치채지 못하게 상황을 설계하고, 한발 물러나 모든 걸 조율합니다. 냉철한 머리와 긴 안목이 당신의 무기예요.",
      en: "You're a schemer who looks past the contest in front of you to the whole board. You lay moves several steps ahead for the outcome you want, unmoved by emotion and driven by curiosity and purpose alone. You design situations no one notices and orchestrate everything from one step back. Your cool head and long vision are your weapons.",
    },
    strength: { ko: "긴 안목과 치밀한 설계, 흔들리지 않는 냉철함이 있습니다.", en: "Long vision, meticulous design, and unshakable cool." },
    weakPoint: { ko: "한발 물러서 보다 사람과 멀어질 수 있어요.", en: "Always one step back, you may drift from people." },
    friendSays: { ko: "넌 다 계획이 있구나… 가끔 좀 무섭다ㄷㄷ", en: "You had a plan all along… honestly kind of scary." },
    shareLine: { ko: "나 주술회전 테스트에서 켄자쿠 나왔다. 판 짜는 책략가래ㄷㄷ", en: "I got Kenjaku — the mastermind who weaves the board." },
    emoji: "🧠",
    color: "#6A4A8C",
  },
];

// 히든(레어) — 극단 선택지(군림/실력지상/인간경시/오만) hiddenWeight 합이 임계값 이상일 때만 등장.
const HIDDEN: AnimeResult = {
  key: "sukuna",
  name: { ko: "료멘 스쿠나", en: "Sukuna" },
  oneLiner: { ko: "모두를 내려다보는 압도적인 저주의 왕", en: "The King of Curses, looking down on everyone." },
  description: {
    ko: "당신은 아주 드물게 나오는 ‘제왕’ 결과입니다. 누구에게도 고개 숙이지 않고, 자신의 기준만이 절대인 압도적 존재. 오만하다 할 만큼 당당하고, 한번 진심을 내면 그 누구도 막을 수 없습니다. 어중간함에 관심 없고 오직 강함으로 군림하는, 격이 다른 유형이에요.",
    en: "You're an extremely rare 'sovereign' result. You bow to no one, and your standard alone is absolute — an overwhelming presence. Confident to the point of arrogance, and once you go all in, nothing can stop you. Indifferent to the half-measure, reigning through sheer strength: a class entirely of your own.",
  },
  strength: { ko: "압도적인 자신감과 누구도 못 막는 추진력이 있습니다.", en: "Overwhelming confidence and a drive no one can halt." },
  weakPoint: { ko: "오만함이 주변을 멀어지게 할 수 있어요.", en: "Your arrogance can push everyone away." },
  friendSays: { ko: "넌 진짜… 왕이냐?ㅋㅋ 근데 인정.", en: "Are you literally… a king? lol — but fair." },
  shareLine: { ko: "나 주술회전 테스트에서 ‘스쿠나’ 나왔다. 저주의 왕 히든이래 ㄷㄷㄷ", en: "I pulled 'Sukuna' on the JJK test — the King of Curses hidden result. Insane." },
  emoji: "👹",
  color: "#7A1020",
};

// 히든 2 (사랑 정점) — "집착에 가까운 깊은 사랑/한 사람에 올인/끝까지 따라감" 트랙(hiddenWeights.rika) 합이 임계값 이상일 때만 등장.
const HIDDEN_RIKA: AnimeResult = {
  key: "rika",
  name: { ko: "오리모토 리카", en: "Rika" },
  oneLiner: { ko: "저주가 될 만큼 깊고 강렬한 사랑의 화신", en: "Love so deep and fierce it becomes a curse itself." },
  description: {
    ko: "당신은 아주 드물게 나오는 '순애 정점' 결과입니다. 한번 사랑하면 그 마음이 세상 무엇보다 커지고, 소중한 사람을 위해서라면 끝까지, 어디까지든 갑니다. 그 사랑이 때론 집착처럼 보일 만큼 강렬하지만, 그만큼 순수하고 거짓이 없죠. 누구보다 깊게 사랑할 줄 아는, 격이 다른 마음의 소유자예요.",
    en: "You're an extremely rare 'pure-love apex' result. Once you love, that feeling grows larger than anything in the world, and for the person you cherish you'll go all the way, as far as it takes. That love can look almost like obsession in its intensity — but it's just as pure and honest. The kind who can love deeper than anyone, in a class of your own.",
  },
  strength: { ko: "무엇보다 깊고 순수한 사랑과 끝까지 가는 헌신이 있습니다.", en: "Love deeper and purer than anything, and devotion that goes all the way." },
  weakPoint: { ko: "사랑이 너무 깊어 한 사람에게 모든 걸 거는 위험이 있어요.", en: "Love runs so deep you may stake everything on one person." },
  friendSays: { ko: "넌 한번 좋아하면 진짜 끝까지 가더라… 그게 좀 무서울 정도로ㄷㄷ", en: "Once you love someone you really go all the way… almost scarily so." },
  shareLine: { ko: "나 주술회전 테스트에서 '리카' 나왔다. 저주가 될 만큼 강렬한 사랑 히든이래 ㄷㄷㄷ", en: "I pulled 'Rika' on the JJK test — the love-so-strong-it-curses hidden. Insane." },
  emoji: "🥀",
  color: "#C24A6E",
};

// 문항 재설계 원칙: ① 한 문항의 4답 = 서로 뚜렷이 다른 성향. ② 같은 캐릭터는 매번 다른 상황·다른 면모로.
// ③ "당신은?" 반응형 답은 형용사 상태가 아니라 행동/동사(…한다)로. ④ 16명 전원 도달 가능, 4답은 뚜렷이 구분.
// 히든 2트랙(sukuna=군림/실력지상/인간경시/오만 · rika=집착에 가까운 깊은 사랑/한 사람에 올인/끝까지 따라감)은 hiddenWeights 로 분리.
// 두 트랙은 같은 분기 문항의 서로 다른 선택지에 배치 → 한쪽 "몰빵"이 다른 쪽 임계값을 막는 상호 배타.
const QUESTIONS: AnimeQuestion[] = [
  {
    id: "q1",
    prompt: { ko: "위험한 임무가 떨어졌습니다.\n당신은?", en: "A dangerous mission lands on you.\nYou…" },
    choices: [
      { id: "a", text: { ko: "누가 다칠 수 있으니 내가 먼저 나선다", en: "Someone could get hurt, so I step up first." }, weights: { yuji: 2 } },
      { id: "b", text: { ko: "냉정하게 작전부터 짠다", en: "I keep a cool head and plan the operation first." }, weights: { megumi: 2 } },
      { id: "c", text: { ko: "쫄 거 없지, 당당하게 들어간다", en: "Nothing to fear — I walk in head high." }, weights: { nobara: 2 } },
      { id: "d", text: { ko: "기댈 거 없이 내 힘으로 밀어붙인다", en: "No leaning on anyone — I push it through on my own." }, weights: { maki: 2 } },
    ],
  },
  {
    id: "q2",
    prompt: { ko: "압도적으로 강해 보이는 적과 마주쳤습니다.\n당신은?", en: "You face an enemy who looks overwhelmingly strong.\nYou…" },
    choices: [
      { id: "a", text: { ko: "솔직히 내가 한 수 위지, 가볍게 내려다본다", en: "Honestly, I'm a cut above — I look down on them, lightly." }, weights: { gojo: 2 }, hiddenWeights: { sukuna: 1 } },
      { id: "b", text: { ko: "약점부터 읽고 한 수 앞을 설계한다", en: "I read the weak point first and design a move ahead." }, weights: { megumi: 2 } },
      { id: "c", text: { ko: "드디어 제대로 붙을 상대다, 신나서 달려든다", en: "Finally a real fight — I charge in, thrilled." }, weights: { kashimo: 2 } },
      { id: "d", text: { ko: "긴장 같은 거 없이 실전 감각대로 움직인다", en: "No nerves — I just move on battle instinct." }, weights: { toji: 2 } },
    ],
  },
  {
    id: "q3",
    prompt: { ko: "남들의 평가 앞에서 당신은?", en: "Facing others' judgment, you…" },
    choices: [
      { id: "a", text: { ko: "남이 뭐라든 당당하게 내 소신을 밀고 간다", en: "Whatever they say, I push my own conviction with my head high." }, weights: { nobara: 2 } },
      { id: "b", text: { ko: "평가 따윈 제쳐두고 나한테 이득 되는 쪽을 계산한다", en: "I set the judgment aside and calculate which side actually pays off for me." }, weights: { meimei: 2 } },
      { id: "c", text: { ko: "한발 물러서서 사람들을 흥미롭게 관찰하며 판을 읽어둔다", en: "I step back, observe people with cool curiosity, and read the whole board for later." }, weights: { kenjaku: 2 } },
      { id: "d", text: { ko: "무시하는 기색이면 발끈해서 받아친다", en: "If they seem dismissive, I flare up and fire back." }, weights: { jogo: 2 } },
    ],
  },
  {
    id: "q4",
    prompt: { ko: "팀에 갈등이 생겼습니다.\n당신은?", en: "Conflict breaks out in the team.\nYou…" },
    choices: [
      { id: "a", text: { ko: "분위기부터 풀고 사람들을 다독인다", en: "I ease the mood first and settle everyone down." }, weights: { panda: 2 } },
      { id: "b", text: { ko: "할 말은 분명히 하고 넘어간다", en: "I say what needs saying, then move on." }, weights: { nobara: 2 } },
      { id: "c", text: { ko: "누가 옳은지 차분히 따져 공정하게 가린다", en: "I weigh who's right calmly and settle it fairly." }, weights: { higuruma: 2 } },
      { id: "d", text: { ko: "내 룰대로 판을 키워 한 방에 정리한다", en: "I raise the stakes my own way and settle it in one shot." }, weights: { hakari: 2 } },
    ],
  },
  {
    id: "q5",
    prompt: { ko: "소중한 친구가 위기에 빠졌습니다.\n당신은?", en: "A close friend is in serious trouble.\nYou…" },
    choices: [
      { id: "a", text: { ko: "내가 다치더라도 몸을 던져 막아선다", en: "I throw myself in to shield them, even if I get hurt." }, weights: { yuta: 2 } },
      { id: "b", text: { ko: "묻지도 따지지도 않고 바로 달려가 챙긴다", en: "No questions asked — I rush right over and look after them." }, weights: { choso: 2 } },
      { id: "c", text: { ko: "내가 옳다고 믿는 방식으로 지켜낸다", en: "I protect them the way I believe is right." }, weights: { geto: 2 } },
      { id: "d", text: { ko: "그 사람 곁에 나를 묶어두고 어디까지든 따라가 끝까지 지킨다", en: "I bind myself to their side and follow them wherever it leads, guarding them to the very end." }, weights: { nanami: 2 }, hiddenWeights: { rika: 1 } },
    ],
  },
  {
    id: "q6",
    prompt: { ko: "일이나 공부를 대할 때 당신은?", en: "Facing work or study, you…" },
    choices: [
      { id: "a", text: { ko: "프로답게 확실히 끝내고 칼퇴한다", en: "I finish it right like a pro, then clock out sharp." }, weights: { nanami: 2 } },
      { id: "b", text: { ko: "돈 되는 만큼만 효율적으로 처리한다", en: "I handle only as much as it pays — efficiently." }, weights: { meimei: 2 } },
      { id: "c", text: { ko: "남들 몇 배로 노력해서 따라잡는다", en: "I put in several times the effort to catch up." }, weights: { maki: 2 } },
      { id: "d", text: { ko: "강함만 좇고 나머진 다 쳐낸다", en: "I chase strength alone and cut away all the rest." }, weights: { toji: 2 }, hiddenWeights: { sukuna: 1 } },
    ],
  },
  {
    id: "q7",
    prompt: { ko: "스트레스를 풀 때 당신은?", en: "To blow off stress, you…" },
    choices: [
      { id: "a", text: { ko: "장난치고 놀러 다니며 가볍게 털어버린다", en: "I goof around and go out playing, shaking it off like it's nothing." }, weights: { gojo: 2 } },
      { id: "b", text: { ko: "말없이 혼자 조용히 쉬며 마음을 가라앉힌다", en: "Wordlessly, I rest alone in the quiet and let my mind settle." }, weights: { toge: 2 } },
      { id: "c", text: { ko: "땀 쫙 빼는 빡센 운동으로 몸을 불태운다", en: "I burn it off with a brutal, sweat-soaked workout." }, weights: { todo: 2 } },
      { id: "d", text: { ko: "쇼핑하고 돈 쓰며 푼다", en: "I shop and spend it off." }, weights: { meimei: 2 } },
    ],
  },
  {
    id: "q8",
    prompt: { ko: "사람들이 보는 당신의 첫인상은?", en: "What's your first impression on people?" },
    choices: [
      { id: "a", text: { ko: "천진하게 웃는데 종잡을 수 없는 사람", en: "Childlike smile, yet impossible to pin down." }, weights: { mahito: 2 } },
      { id: "b", text: { ko: "장난스러운데 은근 다 꿰뚫는 사람", en: "Playful, yet quietly sees right through it all." }, weights: { panda: 2 } },
      { id: "c", text: { ko: "무뚝뚝해도 정직하고 우직한 사람", en: "Blunt, but honest and earnest." }, weights: { choso: 2 } },
      { id: "d", text: { ko: "차분하고 기품 있는, 카리스마 있는 사람", en: "Calm, refined, and quietly commanding." }, weights: { geto: 2 } },
    ],
  },
  {
    id: "q9",
    prompt: { ko: "소중한 사람을 대할 때 당신은?", en: "With the people dearest to you, you…" },
    choices: [
      { id: "a", text: { ko: "오직 그 한 사람에게 깊이 헌신한다", en: "I devote myself deeply to that one person." }, weights: { yuta: 2 } },
      { id: "b", text: { ko: "말 대신 행동으로 조용히 챙긴다", en: "I look after them quietly through actions, not words." }, weights: { toge: 2 } },
      { id: "c", text: { ko: "한번 인정한 사람은 큰소리로 끝까지 띄워준다", en: "Once I accept someone, I hype them up loud, to the end." }, weights: { todo: 2 } },
      { id: "d", text: { ko: "당당하게 같이 맞서 준다", en: "I stand and face it alongside them, head high." }, weights: { nobara: 2 } },
    ],
  },
  {
    id: "q10",
    prompt: { ko: "새로운 것에 도전할 때 당신은?", en: "Taking on something new, you…" },
    choices: [
      { id: "a", text: { ko: "재밌어 보이면 규칙이고 뭐고 일단 해본다", en: "If it looks fun, I just try it — rules be damned." }, weights: { mahito: 2 } },
      { id: "b", text: { ko: "안 된다고 할수록 더 오기로 파고든다", en: "The more they say I can't, the harder I dig in." }, weights: { maki: 2 } },
      { id: "c", text: { ko: "별거 아니라는 듯 툭 해치운다", en: "I knock it out like it's nothing." }, weights: { gojo: 2 } },
      { id: "d", text: { ko: "옳다 싶으면 재기 전에 뛰어든다", en: "If it feels right, I dive in before I overthink." }, weights: { yuji: 2 } },
    ],
  },
  {
    id: "q11",
    prompt: { ko: "절대 타협 못 하는 당신의 원칙은?", en: "Your non-negotiable principle?" },
    choices: [
      { id: "a", text: { ko: "누구에게도 고개 숙이지 않고 군림한다", en: "I bow to no one and reign." }, weights: { geto: 2 }, hiddenWeights: { sukuna: 1 } },
      { id: "b", text: { ko: "사랑하는 단 한 사람에게 내 전부를 걸고 끝까지 매달린다", en: "I stake my whole self on the one person I love and cling to them to the very end." }, weights: { yuki: 2 }, hiddenWeights: { rika: 1 } },
      { id: "c", text: { ko: "손해를 봐도 사람답게 옳게 산다", en: "I live right by people, even at a loss." }, weights: { yuji: 2 } },
      { id: "d", text: { ko: "불공정한 건 절대 그냥 못 넘어간다", en: "I can never just let unfairness slide." }, weights: { higuruma: 2 } },
    ],
  },
  {
    id: "q12",
    prompt: { ko: "중요한 결정을 내릴 때 당신은?", en: "Making an important decision, you…" },
    choices: [
      { id: "a", text: { ko: "감정 빼고 판 전체를 길게 내다보고 몇 수 앞을 미리 깐다", en: "Emotion off, I read the whole board long-term and lay moves several steps ahead." }, weights: { kenjaku: 2 } },
      { id: "b", text: { ko: "합리적으로 따져 효율적인 쪽을 택한다", en: "I weigh it rationally and pick the efficient path." }, weights: { megumi: 2 } },
      { id: "c", text: { ko: "남이야 어찌 되든 내 힘으로 찍어누른다", en: "Whatever happens to the rest, I crush it with my own power." }, weights: { toji: 2 }, hiddenWeights: { sukuna: 1 } },
      { id: "d", text: { ko: "그 사람을 위한 선택이라면 나를 버리고서라도 그쪽으로 끝까지 간다", en: "If it's a choice for that person, I throw myself aside and go all the way toward them." }, weights: { choso: 2 }, hiddenWeights: { rika: 1 } },
    ],
  },
  {
    id: "q13",
    prompt: { ko: "당신을 무시하는 상대, 어떻게 하나요?", en: "Someone who looks down on you — what do you do?" },
    choices: [
      { id: "a", text: { ko: "무시당하는 건 못 참고 끝까지 받아친다", en: "I can't stand being looked down on — I fire back to the end." }, weights: { jogo: 2 } },
      { id: "b", text: { ko: "내려다보며 내 식대로 짓밟아버린다", en: "I look down on them and crush them my way." }, weights: { geto: 2 }, hiddenWeights: { sukuna: 1 } },
      { id: "c", text: { ko: "내 사랑하는 단 한 사람을 건드렸으니 세상 끝까지 쫓아가 모든 걸 걸고 갚아준다", en: "They touched the one person I love — I chase them to the end of the world and make them pay with everything I have." }, weights: { hakari: 2 }, hiddenWeights: { rika: 1 } },
      { id: "d", text: { ko: "내가 지키는 사람들을 건드리면 말없이 앞을 막아선다", en: "Touch the people I guard and I plant myself in the way, no words needed." }, weights: { choso: 2 } },
    ],
  },
  {
    id: "q14",
    prompt: { ko: "당신의 가장 큰 매력은?", en: "Your biggest charm?" },
    choices: [
      { id: "a", text: { ko: "잘나가는데 얄밉지 않은 여유", en: "Crushing it, yet somehow not annoying about it." }, weights: { gojo: 2 } },
      { id: "b", text: { ko: "사람을 큰소리로 끌어올리는 뜨거운 의리", en: "Hot-blooded loyalty that hypes people up out loud." }, weights: { todo: 2 } },
      { id: "c", text: { ko: "위기를 즐기며 크게 거는 강심장 배짱", en: "A steel nerve that enjoys risk and bets big." }, weights: { hakari: 2 } },
      { id: "d", text: { ko: "다정한데 누구보다 강한 반전", en: "Gentle — yet, surprise, stronger than anyone." }, weights: { yuta: 2 } },
    ],
  },
  {
    id: "q15",
    prompt: { ko: "당신이 진짜로 바라는 건?", en: "What do you truly want?" },
    choices: [
      { id: "a", text: { ko: "근본부터 갈아엎어 세상을 바꿔버린다", en: "I overturn things at the root and change the world." }, weights: { yuki: 2 } },
      { id: "b", text: { ko: "내가 믿는 가치를 위해 뜨겁게 타오른다", en: "I burn hot for the values I believe in." }, weights: { jogo: 2 } },
      { id: "c", text: { ko: "아무도 모르게 판 전체를 설계해 원하는 결말로 끌고 간다", en: "I design the whole board unnoticed and steer it to the ending I want." }, weights: { kenjaku: 2 } },
      { id: "d", text: { ko: "오직 그 한 사람만을 바라보며 평생 그 곁에 머문다", en: "I look only at that one person and stay by their side for life." }, weights: { toge: 2 }, hiddenWeights: { rika: 1 } },
    ],
  },
  {
    id: "q16",
    prompt: { ko: "당신을 한마디로 표현하면?", en: "Sum yourself up in a line?" },
    choices: [
      { id: "a", text: { ko: "틀에 안 얽매이고 크게 노는 자유로운 야심가", en: "A free-spirited dreamer who plays big, unbound by convention." }, weights: { yuki: 2 } },
      { id: "b", text: { ko: "분위기를 안고 가는 듬직한 맏형", en: "The dependable big-sibling who carries the mood." }, weights: { panda: 2 } },
      { id: "c", text: { ko: "옳고 그름을 차분히 가리는 정의로운 판단가", en: "A just arbiter who calmly tells right from wrong." }, weights: { higuruma: 2 } },
      { id: "d", text: { ko: "무시당하면 끝까지 타오르는 뜨거운 외골수", en: "A hot-blooded loner who burns to the end when looked down on." }, weights: { jogo: 2 } },
    ],
  },
  {
    id: "q17",
    prompt: { ko: "당신이 가장 살아있다고 느낄 때는?", en: "When do you feel most alive?" },
    choices: [
      { id: "a", text: { ko: "한계까지 몰아붙이는 짜릿한 승부에 뛰어들 때", en: "When I throw myself into a thrilling fight that pushes me to the limit." }, weights: { kashimo: 2 } },
      { id: "b", text: { ko: "내가 끌어준 사람이 멋지게 해내는 걸 보며 같이 함성을 지를 때", en: "When I watch someone I lifted up nail it and roar right along with them." }, weights: { todo: 2 } },
      { id: "c", text: { ko: "별거 아니라는 듯 가볍게 다 정리해버릴 때", en: "When I clear it all like it's nothing." }, weights: { gojo: 2 } },
      { id: "d", text: { ko: "잘못된 걸 바로잡아 균형을 되돌렸을 때", en: "When I right a wrong and set the balance back straight." }, weights: { higuruma: 2 } },
    ],
  },
  {
    id: "q18",
    prompt: { ko: "지루한 일상이 이어질 때 당신은?", en: "When dull, ordinary days drag on, you…" },
    choices: [
      { id: "a", text: { ko: "심심해 죽겠다, 제대로 불태울 판을 찾아 나선다", en: "Bored to death — I go hunt for a fight worth burning for." }, weights: { kashimo: 2 } },
      { id: "b", text: { ko: "흥미로운 걸 찾아 이것저것 건드려본다", en: "I poke at this and that, chasing whatever looks interesting." }, weights: { mahito: 2 } },
      { id: "c", text: { ko: "주변 사람부터 챙기며 조용히 분위기를 띄운다", en: "I look after the people around me and quietly lift the mood." }, weights: { panda: 2 } },
      { id: "d", text: { ko: "딱 필요한 만큼만 하고 내 시간을 지킨다", en: "I do exactly what's needed and protect my own time." }, weights: { nanami: 2 } },
    ],
  },
];

export const JUJUTSU_KAISEN_CONFIG: AnimeTestConfig = {
  testId: "jujutsu-kaisen",
  path: "/tests/jujutsu-kaisen",
  tone: "dark",
  accent: "#7AA2FF",
  ogBg: "linear-gradient(135deg, #0a0e1a 0%, #171b30 55%, #0a0c16 100%)",
  eyebrow: { ko: "나의 주술회전 캐릭터", en: "Your JJK Character" },
  gameName: { ko: "주술회전 캐릭터", en: "Jujutsu Kaisen" },
  title: { ko: "주술회전 캐릭터 테스트", en: "Jujutsu Kaisen Character Test" },
  subtitle: { ko: "너는 어떤 주술사일까?", en: "Which sorcerer are you?" },
  description: {
    ko: "18개의 상황 선택으로 21명의 주술회전 캐릭터 중 너와 가장 닮은 한 명을 찾아드립니다. 유지·고죠·메구미·나나미·토도·하카리·히구루마·켄자쿠… 그리고 아주 드물게 나오는 숨은 결과 2종까지!",
    en: "18 quick choices match you to one of 21 Jujutsu Kaisen characters — Yuji, Gojo, Megumi, Nanami, Todo, Hakari, Higuruma, Kenjaku… plus two ultra-rare hidden results.",
  },
  metaTitle: { ko: "주술회전 캐릭터 테스트 | 나는 어떤 주술사?", en: "Jujutsu Kaisen Character Test | Which Sorcerer Are You?" },
  metaDescription: {
    ko: "18문항으로 알아보는 나의 주술회전 캐릭터. 21명 중 나와 가장 닮은 주술사는? 아주 드물게 나오는 히든 결과 2종도 숨어 있어요.",
    en: "Find your Jujutsu Kaisen character in 18 questions — which of 21 sorcerers are you? Two rare hidden results await.",
  },
  ogKicker: "JUJUTSU KAISEN CHARACTER TEST",
  coverImage: "/images/tests/jujutsu-kaisen/cover-og.jpg",
  results: RESULTS,
  hiddens: [HIDDEN, HIDDEN_RIKA],
  hiddenThreshold: 4,
  questions: QUESTIONS,
  recommendedIds: ["demon-slayer", "chainsaw-man", "overwatch-playstyle", "crush-type"],
};
