import type { AnimeResult, AnimeQuestion, AnimeTestConfig } from "@/lib/anime-test";

// 일반 18명. 히든(골 D. 로저)은 config.hidden 으로 분리, results[] 에 넣지 않는다. (23문항)
// 히든 트리거: Q4d·Q9d·Q13c·Q17d·Q20c 총 5개 선택지에 hiddenWeight:1 부여.
// 5개 중 4개 이상 선택 시 threshold(4) 도달 → 로저 발동. (발동 확률 약 1.6%)

const RESULTS: AnimeResult[] = [
  {
    key: "luffy",
    name: { ko: "몽키 D. 루피", en: "Monkey D. Luffy" },
    oneLiner: { ko: "자유롭고 무모하지만, 사람을 끌어당기는 천성의 리더", en: "Free and reckless — a born leader who naturally pulls people in." },
    description: {
      ko: "당신은 규칙보다 자신의 감각을 믿고, 하고 싶은 일에 거침없이 뛰어드는 사람입니다. 생각보다 몸이 먼저 움직이고, 목표 앞에서는 두려움이 없습니다. 강요 없이도 사람들이 따라오는 이유는 당신의 순수함과 흔들리지 않는 확신 때문이에요. 약한 사람을 보면 그냥 지나치지 못하는 것도 당신의 매력입니다.",
      en: "You trust your gut over rules and dive into what you want without hesitation. Your body moves before your mind catches up, and you feel no fear before your goals. People follow without being pushed, drawn in by your purity and unshakeable conviction. And you simply can't walk past someone in need.",
    },
    strength: { ko: "흔들리지 않는 신념과 사람을 끌어당기는 천연 카리스마", en: "Unshakeable conviction and effortless, natural charisma." },
    weakPoint: { ko: "계획 없이 직진해서 큰 사고를 치기도 해요.", en: "Charging in without a plan can cause serious chaos." },
    friendSays: { ko: "무모한데 왜 이렇게 믿음직스럽냐ㅋㅋ", en: "You're reckless, so why do I trust you this much?? lol" },
    shareLine: { ko: "나 원피스 캐릭터 테스트에서 루피 나왔다! 천성의 리더래ㅋ", en: "I got Monkey D. Luffy! A born leader, apparently." },
    emoji: "🍖",
    color: "#D32F2F",
  },
  {
    key: "zoro",
    name: { ko: "롤로노아 조로", en: "Roronoa Zoro" },
    oneLiner: { ko: "목표 하나로 모든 것을 갈아 넣는, 외길 인생", en: "One goal, all-in — a single-path life of relentless refinement." },
    description: {
      ko: "당신은 한번 세운 목표를 향해 묵묵히, 그리고 치열하게 나아가는 사람입니다. 불필요한 말보다 행동으로 증명하고, 지는 것을 극도로 싫어합니다. 감정을 잘 드러내지 않고 무뚝뚝해 보여도, 자신이 소중하게 생각하는 것을 지키는 데는 누구보다 강합니다. 그 굳건함이 주변 사람들에게 든든한 버팀목이 됩니다.",
      en: "You move toward your goals steadily and fiercely, proving yourself through action rather than words. You despise losing. You may seem blunt and closed off, but when it comes to protecting what matters to you, you are the strongest. That steadiness makes you the pillar everyone leans on.",
    },
    strength: { ko: "흔들리지 않는 집중력과 지키는 힘", en: "Unwavering focus and the strength to protect." },
    weakPoint: { ko: "무뚝뚝해서 오해를 사거나, 방향을 잃기도 해요.", en: "That bluntness can cause misunderstandings — or you just get lost." },
    friendSays: { ko: "말은 없는데 항상 제일 든든해.", en: "Never says much, but always the most dependable." },
    shareLine: { ko: "나 원피스 테스트에서 조로 나왔다. 외길 집중형ㄷ", en: "I got Zoro. One path, one goal. No detours." },
    emoji: "⚔️",
    color: "#2E7D32",
  },
  {
    key: "nami",
    name: { ko: "나미", en: "Nami" },
    oneLiner: { ko: "영리하고 현실적인 전략가, 그러면서도 정 많은 사람", en: "Sharp and practical strategist — warmer than you look." },
    description: {
      ko: "당신은 상황을 빠르게 파악하고 현실적인 판단을 내리는 영리한 사람입니다. 감정에 휩쓸리기보다 실질적인 해결책을 찾고, 주변을 꼼꼼하게 챙깁니다. 겉으론 냉정해 보여도 가까운 사람들에겐 의외로 다정하고, 필요할 땐 그 누구보다 강하게 부딪힙니다.",
      en: "You read situations quickly and make practical, sharp judgments. You look for real solutions rather than getting swept up in emotion, and you take careful care of those around you. You seem cool on the outside, but you're surprisingly warm to people close to you — and fierce when needed.",
    },
    strength: { ko: "빠른 상황 판단과 꼼꼼한 실행력", en: "Quick situational read and meticulous execution." },
    weakPoint: { ko: "속마음을 잘 드러내지 않아 오해받을 수 있어요.", en: "Keeping your true feelings hidden can cause misunderstandings." },
    friendSays: { ko: "냉정해 보이는데 알고 보면 제일 챙겨줘.", en: "Seems cold, but honestly takes care of us the most." },
    shareLine: { ko: "나 원피스 테스트에서 나미 나왔다! 현실적인 전략가래.", en: "I got Nami! Sharp and strategic, apparently." },
    emoji: "🍊",
    color: "#EF8C00",
  },
  {
    key: "usopp",
    name: { ko: "우솝", en: "Usopp" },
    oneLiner: { ko: "겁은 많지만 결정적 순간 가장 눈부시게 빛나는", en: "Most scared of the bunch — most dazzling when it counts." },
    description: {
      ko: "당신은 무서운 걸 알면서도 자리를 지키는 진짜 용기를 가진 사람입니다. 큰소리도 치고 핑계도 대지만, 결정적인 순간엔 어디선가 힘이 나서 해내고야 맙니다. 창의적인 아이디어와 끝없는 상상력으로 위기를 돌파하고, 가까운 사람들을 위해서라면 두려움조차 뛰어넘습니다.",
      en: "You have real courage — the kind that stays even when you're scared. You boast and make excuses, but at the decisive moment you always find strength to come through. Creative ideas and limitless imagination get you through crises, and for people close to you, you leap over your own fear.",
    },
    strength: { ko: "창의력과 결정적 순간 발휘되는 진짜 용기", en: "Creativity and genuine courage that emerges when it truly matters." },
    weakPoint: { ko: "겁이 많고 자기 자신을 과소평가하는 경향이 있어요.", en: "Easily scared, and tends to underestimate yourself." },
    friendSays: { ko: "맨날 못 한다더니 결국엔 항상 해내ㅋㅋ", en: "Always says can't do it, always pulls it off anyway lol" },
    shareLine: { ko: "원피스 테스트에서 우솝 나왔다ㅋ 겁쟁이인데 결정적 순간 반전형!", en: "I got Usopp lol — the scaredy-cat who somehow always comes through!" },
    emoji: "🎯",
    color: "#8D6E63",
  },
  {
    key: "sanji",
    name: { ko: "빈스모크 상디", en: "Sanji" },
    oneLiner: { ko: "열정과 기사도로 불타는, 감성적인 낭만파", en: "Burning with passion and chivalry — a deeply romantic soul." },
    description: {
      ko: "당신은 감정이 풍부하고 열정적인 사람입니다. 좋아하는 것에는 온 마음을 쏟고, 자신이 소중히 여기는 사람에게는 기사 같은 헌신을 보여줍니다. 자존심이 강하고 원칙이 있지만, 그 안에는 따뜻한 감성과 낭만이 깊이 자리 잡고 있어요. 실력도 뛰어나지만 그걸 티 내기보다 조용히 행동으로 보여주는 타입입니다.",
      en: "You are rich in feeling and passion. You give everything to what you love and show knight-like devotion to those you treasure. You have strong pride and clear principles, but beneath that lives deep warmth and romance. Talented, but you prefer to show it through action rather than words.",
    },
    strength: { ko: "열정, 헌신, 높은 실행력", en: "Passion, devotion, and excellent execution." },
    weakPoint: { ko: "감정이 앞서거나 자존심이 방해가 될 때가 있어요.", en: "Emotions or pride can sometimes get in your way." },
    friendSays: { ko: "멋있는데 좀 오바해ㅋㅋ 그래도 좋아", en: "Overdoes it a bit, but honestly love that about you lol" },
    shareLine: { ko: "원피스 테스트에서 상디 나왔다! 열정 낭만파래", en: "I got Sanji! A passionate romantic, apparently." },
    emoji: "🍳",
    color: "#1565C0",
  },
  {
    key: "chopper",
    name: { ko: "토니토니 쵸파", en: "Tony Tony Chopper" },
    oneLiner: { ko: "순수하고 다정한 마음으로 세상을 대하는 사람", en: "Meeting the world with pure, gentle sincerity." },
    description: {
      ko: "당신은 세상에 대한 순수한 호기심과 다정한 마음을 가진 사람입니다. 배우는 것을 좋아하고, 상대의 감정에 민감하게 반응합니다. 겉으로는 수줍어 보여도, 자신이 사랑하는 사람들을 위해서라면 의외의 용기를 발휘합니다. 꾸미지 않은 솔직함과 따뜻함이 당신의 가장 큰 매력이에요.",
      en: "You carry pure curiosity and genuine warmth toward the world. You love learning and are sensitive to others' feelings. You may seem shy on the outside, but for the people you love, you summon unexpected courage. Unaffected honesty and warmth are your greatest charm.",
    },
    strength: { ko: "순수한 공감 능력과 배움에 대한 열정", en: "Pure empathy and a genuine passion for learning." },
    weakPoint: { ko: "쉽게 상처받거나 당황하는 경우가 있어요.", en: "Easily hurt or flustered." },
    friendSays: { ko: "넌 진짜 순수해. 가끔 걱정돼ㅋㅋ", en: "You're genuinely pure. Makes me worry sometimes lol" },
    shareLine: { ko: "원피스 테스트에서 쵸파 나왔다🦌 순수 공감형이래!", en: "I got Chopper! Pure and empathetic, apparently!" },
    emoji: "🦌",
    color: "#E91E63",
  },
  {
    key: "robin",
    name: { ko: "니코 로빈", en: "Nico Robin" },
    oneLiner: { ko: "침착하고 지적인 관찰자, 조용하지만 누구보다 깊은 사람", en: "Calm, intellectual observer — quiet but deeper than anyone." },
    description: {
      ko: "당신은 감정보다 이성이 앞서는, 조용히 깊이 생각하는 사람입니다. 말수는 적지만 항상 상황의 핵심을 꿰뚫고 있으며, 날카로운 관찰력과 지적 호기심을 가지고 있습니다. 가까이하기 어렵게 느껴질 수 있지만, 한번 마음을 열면 깊고 진한 유대를 만들어가는 타입이에요. 은근한 유머 감각도 있습니다.",
      en: "Reason leads over emotion, and you think deeply and quietly. You say little but always see to the heart of any situation, with sharp observation and intellectual curiosity. You may seem hard to approach, but once you open up, you build deep lasting bonds. And there's a quiet humor in you.",
    },
    strength: { ko: "날카로운 통찰력과 지적인 깊이", en: "Sharp insight and genuine intellectual depth." },
    weakPoint: { ko: "감정 표현을 아껴 가까워지기 어려워 보일 수 있어요.", en: "Holding emotions in can make you seem hard to get close to." },
    friendSays: { ko: "조용한데 관찰력이 무서워. 그리고 은근 웃겨ㅋ", en: "So quiet, but your read on everything is terrifying. Also lowkey funny." },
    shareLine: { ko: "원피스 테스트에서 로빈 나왔다. 냉정한 지성파래.", en: "I got Nico Robin. The calm intellectual type." },
    emoji: "🌸",
    color: "#6A1B9A",
  },
  {
    key: "franky",
    name: { ko: "프랑키", en: "Franky" },
    oneLiner: { ko: "과장되고 열정적이지만, 진심이 넘쳐흐르는 사람", en: "Over-the-top and passionate — overflowing with genuine heart." },
    description: {
      ko: "당신은 에너지가 넘치고 자신만의 스타일을 절대 숨기지 않는 사람입니다. 크게 표현하고, 크게 행동하고, 만드는 것에 진심을 쏟습니다. 허세처럼 보여도 그 안에는 진짜 감동과 진정성이 있어, 함께하는 사람들을 힘차게 밀어 올려줍니다. 눈물도 웃음도 전부 풀로 내뱉는 사람이에요.",
      en: "You burst with energy and never hide your style. You express big, act big, and pour real heart into what you build. It may look like bravado, but the genuine feeling underneath lifts everyone around you. You cry at full volume and laugh at full volume — all out, always.",
    },
    strength: { ko: "강렬한 에너지와 창의적인 추진력", en: "Intense energy and creative driving force." },
    weakPoint: { ko: "너무 과장되어 부담스러울 수 있어요.", en: "Can be a bit much sometimes." },
    friendSays: { ko: "좀 오버인데 옆에 있으면 힘이 나ㅋ", en: "Way over the top, but being near you energizes me lol" },
    shareLine: { ko: "원피스 테스트에서 프랑키 나왔다! SUPER 에너지형ㅋ", en: "I got Franky! SUPER energy type lol" },
    emoji: "🤖",
    color: "#0288D1",
  },
  {
    key: "brook",
    name: { ko: "브룩", en: "Brook" },
    oneLiner: { ko: "슬픔도 음악으로 바꾸는, 낙천적인 철학가", en: "Turns even sorrow into music — an optimistic philosopher." },
    description: {
      ko: "당신은 힘든 상황에서도 유머와 낙천성으로 주변을 환하게 밝히는 사람입니다. 깊은 슬픔이나 외로움을 가지고 있어도, 그것을 음악과 웃음으로 승화시킬 줄 알아요. 예의 바르고 품격 있는 태도 뒤에는 삶에 대한 깊은 철학이 있습니다. 어떤 상황에서도 자기다움을 잃지 않는 강인함이 있어요.",
      en: "You light up those around you with humor and optimism even in hard times. Even holding deep sorrow or loneliness, you transform it into music and laughter. Behind your polite, dignified manner sits a deep philosophy about life. You have the inner strength to never lose yourself regardless of circumstances.",
    },
    strength: { ko: "낙천적인 에너지와 삶에 대한 깊은 이해", en: "Optimistic energy and a deep understanding of life." },
    weakPoint: { ko: "외로움을 유머로 숨기는 경향이 있어요.", en: "You tend to hide loneliness behind humor." },
    friendSays: { ko: "가끔 뜬금없는데, 옆에 있으면 기분이 좋아져.", en: "Comes out of nowhere sometimes, but being near you just feels good." },
    shareLine: { ko: "원피스 테스트에서 브룩 나왔다🎵 낙천적 철학가래!", en: "I got Brook! The optimistic philosopher type~" },
    emoji: "🎵",
    color: "#455A64",
  },
  {
    key: "jinbei",
    name: { ko: "진베", en: "Jinbei" },
    oneLiner: { ko: "말 한마디도 흔들림 없이, 침착하고 의로운 보호자", en: "Calm and righteous — every word steady, every action sure." },
    description: {
      ko: "당신은 어떤 상황에서도 냉정함을 유지하고, 신중하게 판단하고 행동하는 사람입니다. 감정에 흔들리지 않고 전체를 보며, 자신이 옳다고 믿는 것을 끝까지 지킵니다. 강하고 믿음직스럽지만, 그 힘을 과시하기보다 묵묵히 보호하는 데 씁니다. 곁에 있으면 자연스럽게 안정감이 느껴지는 타입이에요.",
      en: "You keep calm in any situation, judging and acting with careful deliberation. You don't waver with emotion but see the whole picture, holding to what you believe is right to the end. Strong and dependable, you use that strength to protect quietly rather than show it off. People naturally feel stable beside you.",
    },
    strength: { ko: "흔들리지 않는 침착함과 깊은 의리", en: "Unshakeable calm and deep, unbreakable loyalty." },
    weakPoint: { ko: "신중한 나머지 결단이 느릴 수 있어요.", en: "Being so careful can sometimes slow your decisions." },
    friendSays: { ko: "항상 침착해. 내가 패닉일 때 제일 필요한 사람이야.", en: "Always calm. You're exactly who I need when I'm panicking." },
    shareLine: { ko: "원피스 테스트에서 진베 나왔다. 침착한 의리형이래.", en: "I got Jinbei. The calm, loyal guardian type." },
    emoji: "🌊",
    color: "#0D47A1",
  },
  {
    key: "law",
    name: { ko: "트라팔가 로", en: "Trafalgar Law" },
    oneLiner: { ko: "차갑고 전략적이지만, 내면엔 누구보다 뜨거운 것이 있는 사람", en: "Cold and strategic outside — burning with something deeper inside." },
    description: {
      ko: "당신은 감정을 잘 드러내지 않고 항상 판을 읽으며 냉정하게 움직이는 타입입니다. 즉흥보다 계획을, 열정보다 전략을 선택하죠. 그러나 그 차가운 겉모습 안에는 강한 신념과 지키고 싶은 것이 있고, 한번 맺은 의리는 절대 배신하지 않습니다. 쉽게 다가오진 않지만, 한번 신뢰를 얻으면 누구보다 믿음직한 동료가 됩니다.",
      en: "You rarely show emotion, always read the board, and move coolly. You choose planning over impulse, strategy over passion. But beneath that cold exterior lives a fierce conviction and things you want to protect — and the loyalties you form, you never betray. Hard to approach, but once you earn trust, you're the most reliable ally.",
    },
    strength: { ko: "냉철한 전략 사고와 깊은 의리", en: "Cool strategic thinking and deep, unbreakable loyalty." },
    weakPoint: { ko: "감정 표현이 부족해 속마음이 안 보일 수 있어요.", en: "Lack of expression can hide what's really inside you." },
    friendSays: { ko: "차가워 보이는데 알고 보면 진심인 거 다 알아.", en: "Seems cold, but we all know you really care." },
    shareLine: { ko: "원피스 테스트에서 로 나왔다. 냉정한 전략가래.", en: "I got Trafalgar Law. Cold strategist, apparently." },
    emoji: "💊",
    color: "#37474F",
  },
  {
    key: "ace",
    name: { ko: "포트거스 D. 에이스", en: "Portgas D. Ace" },
    oneLiner: { ko: "뜨겁게 타오르며 소중한 사람을 지키는 자유로운 영혼", en: "A free soul burning hot, protecting the ones they love." },
    description: {
      ko: "당신은 자유를 사랑하고, 자신이 아끼는 사람을 위해서라면 무엇이든 하는 뜨거운 사람입니다. 열정적이고 솔직하며, 약자를 보면 가만있지 못합니다. 겉으로 쿨하고 자유로워 보여도, 소중한 사람에게만큼은 의외로 책임감이 강합니다. 당신의 열정과 진심이 주변 사람들에게 큰 용기를 줍니다.",
      en: "You love freedom and will do anything for the people you care about — burning, passionate, honest. You can't stay still when you see someone weaker being pushed around. You may look cool and free on the outside, but toward those you love, you carry surprising responsibility. Your passion gives great courage to those around you.",
    },
    strength: { ko: "열정과 보호 본능, 솔직한 카리스마", en: "Passion, protective instinct, and honest charisma." },
    weakPoint: { ko: "충동적으로 움직여 본인이 위험해질 수 있어요.", en: "Acting on impulse can put yourself in danger." },
    friendSays: { ko: "자유로워 보이는데 소중한 사람한텐 진짜 진심이야.", en: "Looks so free, but deeply sincere about the people you love." },
    shareLine: { ko: "원피스 테스트에서 에이스 나왔다🔥 열정 보호자형!", en: "I got Ace! 🔥 The passionate protector type!" },
    emoji: "🔥",
    color: "#E64A19",
  },
  {
    key: "shanks",
    name: { ko: "샹크스", en: "Shanks" },
    oneLiner: { ko: "여유롭지만 존재감이 다른 차원인 사람", en: "Laid-back, but presence on a completely different level." },
    description: {
      ko: "당신은 겉으로 보기엔 여유롭고 부담 없는 사람처럼 보이지만, 실제로는 주변의 모든 것을 꿰뚫어 보고 있습니다. 큰소리치지 않아도 자연스럽게 분위기를 압도하고, 말 한마디의 무게가 다릅니다. 사람을 신뢰하고 큰 그림을 그리는 타입입니다. 당신의 여유 자체가 가장 강한 무기예요.",
      en: "You look easygoing and low-pressure on the outside, but you're actually seeing through everything around you. Without raising your voice, you naturally own the atmosphere, and your words carry unusual weight. You trust people and prefer drawing the big picture. Your ease itself is your greatest weapon.",
    },
    strength: { ko: "자연스러운 카리스마와 큰 그림을 보는 안목", en: "Natural charisma and the eye to see the big picture." },
    weakPoint: { ko: "여유 때문에 행동이 느리거나 주변을 애태울 수 있어요.", en: "That ease can mean slow action and anxious people around you." },
    friendSays: { ko: "항상 여유로운데 그게 왜 이렇게 멋있냐ㅋ", en: "Always so relaxed. Why does it look so cool though lol" },
    shareLine: { ko: "원피스 테스트에서 샹크스 나왔다. 여유로운 전설의 카리스마ㄷ", en: "I got Shanks. Effortless, legendary charisma." },
    emoji: "⚡",
    color: "#C62828",
  },
  {
    key: "vivi",
    name: { ko: "네펠타리 비비", en: "Nefertari Vivi" },
    oneLiner: { ko: "모두를 살리려 혼자 짊어지는, 공감형 리더", en: "Empathetic leader who shoulders it all to save everyone." },
    description: {
      ko: "당신은 사람들의 감정에 깊이 공감하고, 그 모두를 잃지 않기 위해 혼자라도 싸울 각오가 되어 있는 사람입니다. 직접 나서서 부딪히는 용기와, 외교적으로 상황을 풀어가는 영리함을 함께 가지고 있습니다. 힘든 상황에서도 사람에 대한 믿음을 쉽게 놓지 않아요. 당신의 따뜻한 결단력이 주변 사람에게 희망이 됩니다.",
      en: "You empathize deeply with people and are prepared to fight alone to make sure none of them are lost. You combine the courage to charge in yourself with the intelligence to resolve things diplomatically. Even in hard situations, you don't easily let go of your faith in people. Your warm decisiveness becomes a source of hope.",
    },
    strength: { ko: "깊은 공감 능력과 모두를 위한 결단력", en: "Deep empathy and decisive action for everyone's sake." },
    weakPoint: { ko: "혼자 너무 많이 짊어지다 지칠 수 있어요.", en: "Carrying too much alone can wear you down." },
    friendSays: { ko: "그 상황에서 어떻게 다 챙기냐. 진짜ㄷ", en: "How do you take care of everyone in that situation? Genuinely wow." },
    shareLine: { ko: "원피스 테스트에서 비비 나왔다💙 공감형 리더래!", en: "I got Vivi! 💙 The empathetic leader type!" },
    emoji: "💙",
    color: "#283593",
  },
  {
    key: "hancock",
    name: { ko: "보아 핸콕", en: "Boa Hancock" },
    oneLiner: { ko: "도도하고 오만하지만, 사랑 앞에선 누구보다 순수한 사람", en: "Proud and imperious — but utterly pure when it comes to love." },
    description: {
      ko: "당신은 강한 자존심과 자신감을 가진 사람입니다. 웬만한 것엔 굽히지 않고, 스스로가 특별하다는 확신이 있어요. 겉으로는 냉정하고 도도해 보여도, 마음을 준 사람 앞에서는 의외로 순수하고 솔직해집니다. 그 자존심과 순수함의 공존이 당신의 가장 큰 매력이에요.",
      en: "You have strong pride and self-confidence. You don't easily bend, and you carry a firm belief that you are exceptional. On the outside you seem cool and imperious, but in front of the person who has your heart, you are surprisingly pure and honest. That coexistence of pride and purity is your greatest charm.",
    },
    strength: { ko: "흔들리지 않는 자존심과 강한 존재감", en: "Unshakeable pride and commanding presence." },
    weakPoint: { ko: "자존심이 강해서 솔직하게 표현하기 어려울 때가 있어요.", en: "Strong pride can make it hard to be honest about your feelings." },
    friendSays: { ko: "도도한데 알고 보면 순정파잖아ㅋㅋ", en: "Acts so proud, but you're actually a total romantic lol" },
    shareLine: { ko: "원피스 테스트에서 보아 핸콕 나왔다👸 도도한 순정파래!", en: "I got Boa Hancock! Proud outside, pure romantic inside." },
    emoji: "🐍",
    color: "#C2185B",
  },
  {
    key: "buggy",
    name: { ko: "버기", en: "Buggy the Clown" },
    oneLiner: { ko: "의도한 건 없는데 어쩌다 보니 항상 살아남고 출세하는 사람", en: "Never meant to, but somehow always survives and ends up on top." },
    description: {
      ko: "당신은 계획대로 된 것이 별로 없는데도 신기하게 항상 살아남는 사람입니다. 허세도 있고 겁도 많지만, 그 상황에서 어떻게든 굴러가게 만드는 이상한 운이 있어요. 자신을 과장되게 표현하지만 실은 의외로 의리 있고, 역경 속에서도 특유의 낙관주의로 버팁니다. 주변 사람들이 뭔가를 기대하면 어쩌다 그걸 해내는 신기한 타입이에요.",
      en: "Somehow you're always the one who survives, even when nothing goes to plan. You have bravado and plenty of fear, but a strange luck that makes things work out anyway. You exaggerate yourself, but underneath you're surprisingly loyal, and you keep going through adversity with a peculiar optimism. And somehow when people expect things from you, you accidentally come through.",
    },
    strength: { ko: "어떤 상황에서도 살아남는 이상한 운과 낙관주의", en: "Uncanny luck and optimism that survives any situation." },
    weakPoint: { ko: "큰소리치다가 실제로 해야 할 때 도망치기도 해요.", en: "Big talk can give way to running when it's time to actually deliver." },
    friendSays: { ko: "어떻게 항상 살아나냐ㅋㅋ 진짜 신기해", en: "How do you always make it out?? It's honestly unreal lol" },
    shareLine: { ko: "원피스 테스트에서 버기 나왔다🤡 어쩌다 보니 출세형ㅋㅋ", en: "I got Buggy! 🤡 The accidental survivor who keeps coming out on top." },
    emoji: "🤡",
    color: "#D32F2F",
  },
  {
    key: "whitebeard",
    name: { ko: "에드워드 뉴게이트 (흰수염)", en: "Edward Newgate (Whitebeard)" },
    oneLiner: { ko: "부하들을 아들로 여기는, 압도적인 힘의 아버지", en: "A father of overwhelming power, who sees his crew as his children." },
    description: {
      ko: "당신은 힘과 카리스마를 갖추고 있지만, 그것을 자신을 위해서가 아닌 소중한 사람들을 위해 씁니다. 당신이 이끄는 사람들은 단순한 동료가 아니라 가족이에요. 타협하지 않는 강인함이 있지만, 그 안에는 깊은 온기와 책임감이 있습니다. 어떤 상황에서도 자신이 지켜야 할 것을 지키기 위해 물러서지 않는 사람이에요.",
      en: "You have power and charisma, but you use it not for yourself but for the people who matter to you. The people you lead are not just colleagues — they are family. You have an unyielding toughness, but inside it lives deep warmth and responsibility. You don't retreat from any situation when it comes to protecting what you must protect.",
    },
    strength: { ko: "압도적인 존재감과 가족을 지키는 강인함", en: "Overwhelming presence and the toughness to protect your family." },
    weakPoint: { ko: "자존심과 책임감으로 혼자 너무 많이 짊어집니다.", en: "Pride and responsibility lead you to carry too much alone." },
    friendSays: { ko: "옆에 있으면 어떻게든 될 것 같아. 그냥 믿음이 생겨.", en: "With you around, I feel like things will be okay. Just naturally." },
    shareLine: { ko: "원피스 테스트에서 흰수염 나왔다⚓ 부하들의 아버지형ㄷ", en: "I got Whitebeard! ⚓ The father of his crew, apparently." },
    emoji: "⚓",
    color: "#4A148C",
  },
  {
    key: "mihawk",
    name: { ko: "쥬라큘 미호크", en: "Dracule Mihawk" },
    oneLiner: { ko: "정상에 있어도 늘 배고픈, 고독한 완벽주의자", en: "Hungry even at the top — a solitary perfectionist." },
    description: {
      ko: "당신은 이미 압도적으로 잘하는데도 만족하지 않는 사람입니다. 사람들과 어울리기보다 혼자 갈고닦는 시간을 더 중요하게 여기고, 약한 상대에게는 흥미조차 느끼지 못합니다. 진짜로 강한 상대를 만나야 비로소 눈을 뜨는 타입이에요. 무뚝뚝하고 차가워 보이지만, 그 안에는 자신만의 엄격한 기준과 예의가 있습니다.",
      en: "You're already overwhelmingly good at what you do, yet it's never enough. You value solitary refinement over mixing with a crowd, and weak opponents simply don't interest you. You only truly come alive facing someone genuinely strong. You may look cold and blunt, but underneath is a strict personal code and quiet courtesy.",
    },
    strength: { ko: "타협 없는 실력과 고독을 두려워하지 않는 강인함", en: "Uncompromising skill and the strength to never fear being alone." },
    weakPoint: { ko: "혼자 있는 게 편해서 먼저 다가가는 법을 잘 모릅니다.", en: "Too comfortable alone — you rarely learn how to reach out first." },
    friendSays: { ko: "말은 없는데 눈빛만으로 다 이겨버려.", en: "Barely says a word, but wins the whole room with just a look." },
    shareLine: { ko: "원피스 테스트에서 미호크 나왔다⚔️ 고독한 완벽주의자래", en: "I got Mihawk! ⚔️ The lone perfectionist type." },
    emoji: "🗡️",
    color: "#212121",
  },
];

// 히든: 골 D. 로저 (해적왕)
// 트리거: Q4d·Q9d·Q13c·Q17d·Q20c — 총 5개 선택지에 hiddenWeight:1 부여
const HIDDEN: AnimeResult = {
  key: "roger",
  name: { ko: "골 D. 로저", en: "Gol D. Roger" },
  oneLiner: { ko: "웃으며 죽음마저 넘어선, 전설 그 자체인 사람", en: "One who laughed past even death — a living legend." },
  description: {
    ko: "당신은 두려움이라는 감정 자체가 다른 사람보다 작습니다. 압도적인 존재감으로 사람들을 끌어모으지만, 정작 스스로는 아무것도 아닌 척 웃어넘깁니다. 죽음 앞에서도 웃을 수 있는 건 이미 원하는 걸 다 해봤기 때문이에요. 당신이 남긴 한마디는 그 이후로도 오랫동안 사람들의 인생을 바꿔놓습니다.",
    en: "Fear simply takes up less space in you than in most people. You draw others in with overwhelming presence, yet you brush it all off with a laugh, as if it were nothing. You can smile even facing death, because you've already done everything you wanted to do. And whatever you say next quietly reshapes other people's lives for years to come.",
  },
  strength: { ko: "누구도 따라올 수 없는 존재감과 완전한 자유로움", en: "Presence no one can match, and total, unshakeable freedom." },
  weakPoint: { ko: "자신에 대해 거의 설명하지 않아 남겨진 사람들이 답을 찾아 헤매게 됩니다.", en: "You explain almost nothing about yourself, leaving everyone else to chase the answers." },
  friendSays: { ko: "무슨 생각으로 사는지 아직도 모르겠어. 근데 그게 매력이야.", en: "I still don't know what goes on in your head. That's exactly why it works." },
  shareLine: { ko: "원피스 테스트에서 골 D. 로저 나왔다ㄷㄷ 초희귀 히든!!", en: "I got Gol D. Roger?! The ultra-rare hidden result!!" },
  emoji: "👑",
  color: "#C9A227",
};

const QUESTIONS: AnimeQuestion[] = [
  {
    id: "q1",
    prompt: { ko: "새로운 일을 시작할 때 나는?", en: "When starting something new, I usually..." },
    choices: [
      { id: "a", text: { ko: "일단 뛰어든다. 하면서 배우면 된다", en: "Just dive in — I'll learn as I go." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "목표를 세우고 계획부터 잡는다", en: "Set the goal, then make a plan." }, weights: { zoro: 2, law: 1, mihawk: 1 } },
      { id: "c", text: { ko: "정보와 자원을 충분히 확보한 뒤 시작한다", en: "Gather enough info and resources first." }, weights: { nami: 2, robin: 1 } },
      { id: "d", text: { ko: "해야 하나 말아야 하나... 이것저것 재다 결국 시작한다", en: "Debate whether to do it... then eventually just start." }, weights: { usopp: 2, chopper: 1 } },
    ],
  },
  {
    id: "q2",
    prompt: { ko: "친구들 사이에서 나의 역할은?", en: "My role in a group of friends is usually..." },
    choices: [
      { id: "a", text: { ko: "앞장서고 분위기를 이끈다", en: "Leading from the front, driving the mood." }, weights: { luffy: 2, shanks: 1 } },
      { id: "b", text: { ko: "묵묵히 내 역할을 하는 무뚝뚝한 타입", en: "Quietly doing my part — the blunt, reliable one." }, weights: { zoro: 2, jinbei: 1 } },
      { id: "c", text: { ko: "이야기와 웃음으로 분위기를 살리는 엔터테이너", en: "The entertainer — stories and laughter keep things alive." }, weights: { usopp: 2, brook: 1, franky: 1 } },
      { id: "d", text: { ko: "모두를 챙기고 조율하는 조용한 서포터", en: "The quiet supporter who takes care of everyone." }, weights: { vivi: 2, chopper: 1, nami: 1 } },
    ],
  },
  {
    id: "q3",
    prompt: { ko: "목표가 생겼을 때 나는?", en: "When I set a goal, I..." },
    choices: [
      { id: "a", text: { ko: "무조건 이룬다. 포기란 없다", en: "Will achieve it no matter what — giving up isn't an option." }, weights: { zoro: 2, luffy: 1 } },
      { id: "b", text: { ko: "구체적인 계획을 세우고 단계별로 실행한다", en: "Make a concrete plan and execute it step by step." }, weights: { law: 2, nami: 1 } },
      { id: "c", text: { ko: "꿈은 크게 품고, 할 수 있는 것부터 하나씩", en: "Dream big, then tackle one thing at a time." }, weights: { usopp: 2, franky: 1 } },
      { id: "d", text: { ko: "소중한 사람들과 함께 이루는 것이 목표의 전부", en: "Achieving it together with the people I care about — that's the whole point." }, weights: { vivi: 2, ace: 1 } },
    ],
  },
  {
    id: "q4",
    prompt: { ko: "어려운 결정을 앞에 두고 나는?", en: "Facing a hard decision, I tend to..." },
    choices: [
      { id: "a", text: { ko: "감에 따라 직관적으로 결정한다", en: "Decide intuitively, trusting my gut." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "냉정하게 이익과 손실을 계산해서 선택한다", en: "Calculate gains and losses coolly and choose." }, weights: { law: 2, nami: 1 } },
      { id: "c", text: { ko: "관련된 사람들의 의견을 최대한 반영한다", en: "Factor in the views of everyone involved." }, weights: { vivi: 2, chopper: 1 } },
      { id: "d", text: { ko: "결과에 상관없이, 내가 옳다고 믿는 것을 따른다", en: "Follow what I believe is right, regardless of the outcome." }, weights: { jinbei: 1, zoro: 1 }, hiddenWeight: 1 },
    ],
  },
  {
    id: "q5",
    prompt: { ko: "화가 많이 났을 때 나는?", en: "When I'm really angry, I..." },
    choices: [
      { id: "a", text: { ko: "바로 폭발한다. 그냥 참는 게 안 된다", en: "Explode immediately — I just can't hold it in." }, weights: { luffy: 2, ace: 1, sanji: 1 } },
      { id: "b", text: { ko: "말은 안 하지만 눈빛과 행동으로 다 보인다", en: "Don't say a word, but my eyes and actions say everything." }, weights: { zoro: 2, law: 1 } },
      { id: "c", text: { ko: "감정을 추스르고 어떻게 풀어야 할지 먼저 생각한다", en: "Collect myself first and think about how to resolve it." }, weights: { nami: 2, jinbei: 1, robin: 1 } },
      { id: "d", text: { ko: "무섭지만 참으면서 조용히 끙끙 앓는다", en: "Too scared to show it — I quietly suffer inside." }, weights: { usopp: 2, chopper: 1 } },
    ],
  },
  {
    id: "q6",
    prompt: { ko: "처음 보는 사람을 만났을 때 나는?", en: "When meeting someone new, I..." },
    choices: [
      { id: "a", text: { ko: "먼저 말 걸고 바로 친해진다. 낯가림이 없다", en: "Make the first move and get close right away — no shyness." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "말수가 적고 상대를 먼저 관찰한다", en: "Stay quiet and observe the other person first." }, weights: { law: 2, robin: 1, zoro: 1, mihawk: 2 } },
      { id: "c", text: { ko: "분위기에 맞게 적당히 맞춰가며 거리를 좁힌다", en: "Adapt to the mood and gradually close the gap." }, weights: { vivi: 2, sanji: 1, nami: 1 } },
      { id: "d", text: { ko: "긴장되지만 재미있는 이야기로 분위기를 풀어보려 한다", en: "Nervous, but I try to ease the mood with a funny story." }, weights: { usopp: 2, brook: 1 } },
    ],
  },
  {
    id: "q7",
    prompt: { ko: "팀 과제에서 나의 포지션은?", en: "In a group project, my role tends to be..." },
    choices: [
      { id: "a", text: { ko: "자연스럽게 방향을 제시하고 이끈다", en: "Naturally pointing the direction and leading." }, weights: { luffy: 2, shanks: 1 } },
      { id: "b", text: { ko: "내 전문 영역을 맡아 철저하게 해낸다", en: "Owning my area of expertise and executing thoroughly." }, weights: { zoro: 2, sanji: 1 } },
      { id: "c", text: { ko: "전체 계획을 짜고 모두를 조율한다", en: "Drawing up the whole plan and coordinating everyone." }, weights: { nami: 2, law: 1 } },
      { id: "d", text: { ko: "팀 분위기를 살리고 모두를 응원한다", en: "Keeping up the team's mood and cheering everyone on." }, weights: { chopper: 2, brook: 1, usopp: 1 } },
    ],
  },
  {
    id: "q8",
    prompt: { ko: "감정 표현에 대한 나는?", en: "When it comes to expressing emotions, I..." },
    choices: [
      { id: "a", text: { ko: "생각보다 감정이 먼저 밖으로 나온다", en: "Feelings come out before I can think." }, weights: { luffy: 2, sanji: 1, ace: 1 } },
      { id: "b", text: { ko: "감정을 거의 드러내지 않는 편이다", en: "Rarely show my emotions." }, weights: { zoro: 2, law: 1, robin: 1, mihawk: 2 } },
      { id: "c", text: { ko: "상황 봐가면서 적당히 조절하는 편이다", en: "Read the room and calibrate accordingly." }, weights: { vivi: 2, nami: 1, shanks: 1 } },
      { id: "d", text: { ko: "웃음으로 대부분 넘기지만, 혼자 있을 땐 다르다", en: "Laugh most things off, but alone I'm different." }, weights: { brook: 2, usopp: 1 } },
    ],
  },
  {
    id: "q9",
    prompt: { ko: "갈등이나 싸움에서 나의 스타일은?", en: "My style when dealing with conflict is..." },
    choices: [
      { id: "a", text: { ko: "직접 부딪혀서 결판낸다", en: "Face it head-on and settle it directly." }, weights: { luffy: 2, ace: 1, zoro: 1 } },
      { id: "b", text: { ko: "냉정하게 계산하고 내게 유리한 타이밍을 잡는다", en: "Calculate coolly and pick the timing that favors me." }, weights: { law: 2, nami: 1 } },
      { id: "c", text: { ko: "최대한 갈등 없이 외교적으로 풀어보려 한다", en: "Try to resolve it diplomatically, avoiding conflict as much as possible." }, weights: { vivi: 2, sanji: 1 } },
      { id: "d", text: { ko: "싸움 자체를 되도록 피하고, 꼭 필요할 때만 나선다", en: "Avoid the fight if possible — only step in when truly necessary." }, weights: { jinbei: 1, shanks: 1 }, hiddenWeight: 1 },
    ],
  },
  {
    id: "q10",
    prompt: { ko: "힘든 상황에서 나를 버티게 하는 것은?", en: "What keeps me going in tough situations is..." },
    choices: [
      { id: "a", text: { ko: "이 사람들이랑 함께하고 싶다는 마음", en: "The feeling that I want to be with these people." }, weights: { luffy: 2, vivi: 1 } },
      { id: "b", text: { ko: "목표가 있다. 중간에 포기하는 건 없다", en: "I have a goal. There's no quitting midway." }, weights: { zoro: 2, ace: 1 } },
      { id: "c", text: { ko: "미래에 대한 계산이 맞으면 버틸 수 있다", en: "If the math on the future works out, I can hold on." }, weights: { nami: 2, law: 1 } },
      { id: "d", text: { ko: "뭐든 웃으면서 넘기는 것. 지금도 어떻게든 되겠지", en: "Laughing through it. It'll work out somehow." }, weights: { brook: 2, luffy: 1, franky: 1 } },
    ],
  },
  {
    id: "q11",
    prompt: { ko: "주변 사람들이 나에게 의지하는 이유는?", en: "People lean on me because..." },
    choices: [
      { id: "a", text: { ko: "나를 믿고 따라오면 어떻게든 된다", en: "Things somehow work out when they trust and follow me." }, weights: { luffy: 2, shanks: 1 } },
      { id: "b", text: { ko: "무슨 일이 있어도 내 자리를 지킨다", en: "I hold my position no matter what." }, weights: { zoro: 2, jinbei: 1 } },
      { id: "c", text: { ko: "냉정한 판단과 조언을 믿을 수 있다", en: "They can trust my clear-headed judgment and advice." }, weights: { nami: 2, robin: 1, law: 1 } },
      { id: "d", text: { ko: "힘들 때 옆에 있어주는 사람이라서", en: "I'm the person who's there when things get hard." }, weights: { chopper: 2, vivi: 1, brook: 1 } },
    ],
  },
  {
    id: "q12",
    prompt: { ko: "나의 가장 큰 약점은?", en: "My biggest weakness is probably..." },
    choices: [
      { id: "a", text: { ko: "계획 없이 직진해서 사고를 친다", en: "Charging straight ahead without a plan causes trouble." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "말이 없어서 사람들이 내 속을 모른다", en: "Saying too little — people can't tell what I'm thinking." }, weights: { zoro: 2, law: 1, robin: 1, mihawk: 1 } },
      { id: "c", text: { ko: "겁이 많아서 시작을 못 하고 망설인다", en: "Too scared to start — I hesitate too much." }, weights: { usopp: 2, chopper: 1 } },
      { id: "d", text: { ko: "감정이 앞서서 후회할 행동을 하기도 한다", en: "Emotions take over and I do things I regret." }, weights: { sanji: 2, ace: 1 } },
    ],
  },
  {
    id: "q13",
    prompt: { ko: "나에게 '강함'이란?", en: "To me, 'strength' means..." },
    choices: [
      { id: "a", text: { ko: "무엇이 와도 포기하지 않는 것", en: "Never giving up, no matter what comes." }, weights: { luffy: 2, zoro: 1 } },
      { id: "b", text: { ko: "소중한 사람을 끝까지 지키는 것", en: "Protecting the people I love to the very end." }, weights: { ace: 2, vivi: 1 } },
      { id: "c", text: { ko: "어떤 상황에서도 흔들리지 않는 평정심", en: "Keeping composure that doesn't waver regardless of the situation." }, weights: { jinbei: 1, law: 1 }, hiddenWeight: 1 },
      { id: "d", text: { ko: "두려워도 나아가는 용기", en: "The courage to move forward even when scared." }, weights: { usopp: 2, chopper: 1 } },
    ],
  },
  {
    id: "q14",
    prompt: { ko: "나를 움직이는 가장 강한 감정은?", en: "The emotion that drives me most is..." },
    choices: [
      { id: "a", text: { ko: "설렘. 새로운 것과 미지의 세계가 좋다", en: "Excitement — I love new things and the unknown." }, weights: { luffy: 2, robin: 1, nami: 1 } },
      { id: "b", text: { ko: "분노. 불의를 못 참는다", en: "Anger — I can't stand injustice." }, weights: { ace: 2, luffy: 1, sanji: 1 } },
      { id: "c", text: { ko: "사랑. 소중한 사람이 있으면 뭐든 할 수 있다", en: "Love — I can do anything for the people I care about." }, weights: { vivi: 2, chopper: 1, sanji: 1 } },
      { id: "d", text: { ko: "고요함. 마음이 편해야 제대로 움직인다", en: "Calm — I need inner peace to move at my best." }, weights: { jinbei: 2, law: 1, brook: 1 } },
    ],
  },
  {
    id: "q15",
    prompt: { ko: "친구가 절박한 위기에 처했을 때 나는?", en: "When a friend is in desperate crisis, I..." },
    choices: [
      { id: "a", text: { ko: "아무 생각 없이 뛰어든다. 일단 구하고 본다", en: "Jump in without thinking — save first, think later." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "상황을 빠르게 파악하고 가장 확실한 방법으로 움직인다", en: "Quickly read the situation and move with the most reliable method." }, weights: { nami: 2, law: 1, zoro: 1 } },
      { id: "c", text: { ko: "무섭지만 안 나설 수 없다. 떨면서 뛰어든다", en: "Terrified, but I can't stay back — I dive in trembling." }, weights: { usopp: 2, chopper: 1 } },
      { id: "d", text: { ko: "냉정하게 자신의 역할을 지키며 묵묵히 지원한다", en: "Calmly hold my role and provide steady support without breaking." }, weights: { jinbei: 2, robin: 1, brook: 1 } },
    ],
  },
  {
    id: "q16",
    prompt: { ko: "조용한 밤 혼자 있을 때 나는?", en: "On a quiet night alone, I tend to..." },
    choices: [
      { id: "a", text: { ko: "뭔가 하고 싶은 게 생겨서 금방 밖으로 나간다", en: "Feel like doing something and head out pretty quickly." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "조용히 훈련하거나 집중해야 할 것을 한다", en: "Train quietly or focus on what needs to be done." }, weights: { zoro: 2, law: 1, mihawk: 1 } },
      { id: "c", text: { ko: "음악을 듣거나, 아무 생각 없이 그냥 쉰다", en: "Listen to music or just rest without thinking about anything." }, weights: { brook: 2, shanks: 1 } },
      { id: "d", text: { ko: "읽고 싶은 것들, 알고 싶은 것들을 파고든다", en: "Dig into things I've been wanting to read or learn about." }, weights: { robin: 2, chopper: 1 } },
    ],
  },
  {
    id: "q17",
    prompt: { ko: "내 인생에서 가장 중요한 것은?", en: "The most important thing in my life is..." },
    choices: [
      { id: "a", text: { ko: "자유. 아무것도 나를 막아선 안 된다", en: "Freedom — nothing should stand in my way." }, weights: { luffy: 2, shanks: 1 } },
      { id: "b", text: { ko: "동료. 함께하는 사람들이 전부다", en: "Companions — the people beside me are everything." }, weights: { zoro: 2, jinbei: 1, ace: 1 } },
      { id: "c", text: { ko: "꿈. 언젠가 반드시 이루고 싶은 것", en: "A dream — something I must achieve someday." }, weights: { usopp: 2, nami: 1, franky: 1 } },
      { id: "d", text: { ko: "진실. 이 세계의 숨겨진 역사와 비밀", en: "Truth — the hidden history and secrets of this world." }, weights: { robin: 2 }, hiddenWeight: 1 },
    ],
  },
  {
    id: "q18",
    prompt: { ko: "예기치 못한 위기 상황, 내 반응은?", en: "Caught in an unexpected crisis — my reaction is..." },
    choices: [
      { id: "a", text: { ko: "일단 몸이 먼저 움직인다", en: "My body moves before my mind does." }, weights: { luffy: 2, ace: 2 } },
      { id: "b", text: { ko: "당황하지만 빠르게 대처법을 찾는다", en: "Flustered but quick to find a way out." }, weights: { nami: 2, usopp: 1 } },
      { id: "c", text: { ko: "냉정하게 상황을 분석하고 최선책을 택한다", en: "Stay calm, analyze, and choose the best option." }, weights: { law: 2, robin: 1, zoro: 1 } },
      { id: "d", text: { ko: "동료를 믿고 함께 버텨낸다", en: "Trust my companions and endure it together." }, weights: { chopper: 2, brook: 1, jinbei: 1 } },
    ],
  },
  {
    id: "q19",
    prompt: { ko: "내가 추구하는 '강함'의 의미는?", en: "What does strength mean to me?" },
    choices: [
      { id: "a", text: { ko: "어떤 적도 두렵지 않은 압도적인 힘", en: "Overwhelming power that fears no enemy." }, weights: { whitebeard: 2, luffy: 1, zoro: 1, mihawk: 1 } },
      { id: "b", text: { ko: "상대를 능가하는 지략과 전술", en: "Strategy and tactics that outmaneuver any opponent." }, weights: { law: 2, nami: 1, usopp: 1 } },
      { id: "c", text: { ko: "소중한 것을 지키기 위한 힘", en: "Strength to protect what matters most." }, weights: { zoro: 2, jinbei: 1, ace: 1 } },
      { id: "d", text: { ko: "자신만의 방식과 신념에서 나오는 힘", en: "Power that flows from your own style and conviction." }, weights: { sanji: 2, hancock: 1, shanks: 1 } },
    ],
  },
  {
    id: "q20",
    prompt: { ko: "누군가에게 특별한 것을 물려준다면?", en: "If you were to pass something special on to someone..." },
    choices: [
      { id: "a", text: { ko: "내가 직접 만든 작품이나 발명품", en: "Something I built or invented myself." }, weights: { franky: 2, usopp: 1 } },
      { id: "b", text: { ko: "내가 쌓아온 기술과 경험", en: "The skills and experience I've accumulated." }, weights: { zoro: 2, sanji: 1 } },
      { id: "c", text: { ko: "이 세계를 살아가는 데 필요한 모든 것", en: "Everything one needs to make it through this world." }, weights: { shanks: 2 }, hiddenWeight: 1 },
      { id: "d", text: { ko: "내 꿈과 의지 그 자체", en: "My dream and will itself." }, weights: { ace: 2, luffy: 1, whitebeard: 1 } },
    ],
  },
  {
    id: "q21",
    prompt: { ko: "오랜 여행 후 집에 돌아온다면 가장 먼저?", en: "After a long journey, the first thing I'd do at home..." },
    choices: [
      { id: "a", text: { ko: "바로 다음 모험을 계획한다", en: "Plan the next adventure immediately." }, weights: { luffy: 2, shanks: 1 } },
      { id: "b", text: { ko: "소중한 사람을 찾아 안부를 묻는다", en: "Find someone precious and check in on them." }, weights: { vivi: 2, nami: 1, chopper: 1 } },
      { id: "c", text: { ko: "혼자 조용히 쉬며 다음을 대비한다", en: "Rest quietly alone and prepare for what's next." }, weights: { zoro: 2, law: 1 } },
      { id: "d", text: { ko: "맛있는 음식을 먹으며 여운을 즐긴다", en: "Enjoy the afterglow over a delicious meal." }, weights: { sanji: 2, luffy: 1, brook: 1 } },
    ],
  },
  {
    id: "q22",
    prompt: { ko: "내가 가장 자신 있는 것을 하나 꼽자면?", en: "My single greatest strength is..." },
    choices: [
      { id: "a", text: { ko: "어떤 상황도 뚫어내는 추진력", en: "Drive that breaks through any situation." }, weights: { luffy: 2, ace: 1 } },
      { id: "b", text: { ko: "사람과 상황을 꿰뚫어 보는 통찰력", en: "Insight that sees through people and situations." }, weights: { robin: 2, nami: 1, law: 1 } },
      { id: "c", text: { ko: "어떤 어려움도 포기하지 않는 끈기", en: "Persistence that never gives up no matter what." }, weights: { usopp: 2, vivi: 1, buggy: 1 } },
      { id: "d", text: { ko: "특별한 재능과 그것을 갈고닦는 노력", en: "A unique talent and the hard work to sharpen it." }, weights: { brook: 2, sanji: 1, franky: 1 } },
    ],
  },
  {
    id: "q23",
    prompt: { ko: "나에게 '진짜 강한 사람'이란?", en: "To me, a truly strong person is..." },
    choices: [
      { id: "a", text: { ko: "무엇도 두려워하지 않고 앞으로 나아가는 사람", en: "Someone who moves forward fearing nothing." }, weights: { luffy: 2, shanks: 2 } },
      { id: "b", text: { ko: "소중한 것을 위해서라면 뭐든 할 수 있는 사람", en: "Someone who will do anything for what they hold dear." }, weights: { zoro: 2, ace: 1, whitebeard: 1 } },
      { id: "c", text: { ko: "자신만의 철학과 신념을 끝까지 지키는 사람", en: "Someone who upholds their philosophy and beliefs to the very end." }, weights: { hancock: 2, sanji: 1, jinbei: 1 } },
      { id: "d", text: { ko: "어떤 상황에서도 동료를 이끌고 나아가는 사람", en: "Someone who leads companions through any situation." }, weights: { nami: 2, vivi: 1, buggy: 1 } },
    ],
  },
];

export const ONE_PIECE_CONFIG: AnimeTestConfig = {
  testId: "one-piece",
  path: "/tests/one-piece",
  tone: "navy",
  accent: "#FFD700",
  ogBg: "linear-gradient(135deg, #02101F 0%, #0A2540 55%, #011628 100%)",
  eyebrow: { ko: "나의 원피스 캐릭터", en: "Your One Piece Character" },
  gameName: { ko: "원피스", en: "One Piece" },
  title: { ko: "원피스 캐릭터 테스트", en: "One Piece Character Test" },
  subtitle: { ko: "나는 어떤 원피스 캐릭터일까?", en: "Which One Piece character are you?" },
  description: {
    ko: "23개의 상황 선택으로 루피·롤로노아 조로·나미·우솝·상디·쵸파·로빈·프랑키·브룩·진베·로·에이스·샹크스·비비·보아 핸콕·버기·흰수염·쥬라큘 미호크 중 나와 가장 닮은 캐릭터를 찾아드립니다. 아주 드물게 나오는 히든 결과 1종도 숨어 있어요.",
    en: "23 situation choices match you to one of 18 One Piece characters — Luffy, Zoro, Nami, Usopp, Sanji, Chopper, Robin, Franky, Brook, Jinbei, Law, Ace, Shanks, Vivi, Boa Hancock, Buggy, Whitebeard, Mihawk and more. Plus one ultra-rare hidden result.",
  },
  metaTitle: { ko: "원피스 캐릭터 테스트 | 나는 어떤 캐릭터?", en: "One Piece Character Test | Which One Piece Character Are You?" },
  metaDescription: {
    ko: "23문항으로 알아보는 나의 원피스 캐릭터. 루피·조로·나미·상디·로빈 등 18명 중 나는? 아주 드물게 나오는 히든 결과 1종도 숨어 있어요.",
    en: "Find your One Piece character in 23 questions. Which of 18 characters are you — Luffy, Zoro, Nami, Sanji, Robin? One ultra-rare hidden result awaits.",
  },
  ogKicker: "ONE PIECE CHARACTER TEST",
  coverImage: "/images/tests/one-piece/cover-og.jpg",
  results: RESULTS,
  hiddens: [HIDDEN],
  hiddenThreshold: 4,
  questions: QUESTIONS,
  recommendedIds: ["demon-slayer", "jujutsu-kaisen", "attack-on-titan", "chainsaw-man"],
};
