import type { PlaystyleConfig } from "./core";

// 롤 플레이 성향 테스트 — 확정 콘텐츠 (1:1). 라이엇 챔피언 아트 self-host.
export const LOL_CONFIG: PlaystyleConfig = {
  id: "lol-playstyle",
  path: "/tests/lol-playstyle",
  testName: "LoL Playstyle Test",
  gameLabel: "롤",
  titleKo: "롤 플레이 성향 테스트 | 티어로는 안 보이는 너의 진짜 롤 스타일",
  metaDescription:
    "티어로는 안 보이는 너의 진짜 롤 스타일. 9문항으로 캐리형·운영형·트롤형까지 알아보는 롤 플레이 성향 테스트입니다.",
  eyebrowPill: "SUMMONER TEST",
  introSub: "티어로는 안 보이는 너의 진짜 롤 스타일.",
  introSubEn: "The real LoL style your rank doesn't show.",
  introDesc:
    "캐리형, 운영형, 탱커형, 암살자형, 서포터형, 트롤형까지. 9개의 상황 선택으로 너와 가장 닮은 챔피언과 플레이 성향을 찾아드립니다.",
  introDescEn:
    "Carry, strategist, tank, assassin, support, chaos — 9 quick calls reveal the champion you play like and your true playstyle.",
  introTypeLine: "게임 성향",
  introTypeLineEn: "Playstyle type",
  pairLabel: "닮은 챔피언",
  pairLabelEn: "Your champion",
  gameLabelEn: "LoL",
  media: "art",
  artBase: "/images/tests/lol/art",
  artExt: "jpg",
  notice:
    '이 콘텐츠는 Riot Games의 "Legal Jibber Jabber" 정책에 따라 Riot Games가 소유한 자산을 사용해 제작되었습니다. Riot Games는 본 프로젝트를 보증하거나 후원하지 않습니다. 챔피언 이미지 © Riot Games.',
  noticeEn:
    'This content was created using assets owned by Riot Games under Riot\'s "Legal Jibber Jabber" policy. Riot Games does not endorse or sponsor this project. Champion images © Riot Games.',
  tiebreak: ["carry", "assassin", "strat", "tank", "support", "chaos"],
  ogKicker: "LOL PLAYSTYLE TEST",
  ogDefault: {
    title: "롤 플레이 성향 테스트",
    sub: "티어로는 안 보이는 너의 진짜 롤 스타일.",
    line: "너는 캐리형? 운영형? 아니면 트롤형?",
  },
  ogDescriptionDefault: "티어로는 안 보이는 너의 진짜 롤 스타일. 너는 캐리형? 운영형? 아니면 트롤형?",
  recommendIds: ["valorant-playstyle", "overwatch-playstyle", "pubg-playstyle", "kbti"],
  theme: { accent: "#C8AA6E", accentInk: "#1c1505" },
  types: {
    carry: {
      ko: "하드 캐리형",
      en: "The Hard Carry",
      pair: "야스오",
      pairEn: "Yasuo",
      img: "Yasuo",
      desc: "승패는 곧 너의 손끝에 달렸다. 1인분으로는 만족 못 하고, 결국 네가 게임을 끝내야 직성이 풀린다. 잘 풀리면 그 누구보다 무섭지만, 욕심이 과하면 혼자 던지는 것도 너다.",
      descEn: "The win is in your hands, literally. Pulling your weight isn't enough — you won't be satisfied until you close out the game yourself. When you pop off, nobody's scarier; when greed takes over, you're also the one int-feeding solo.",
      tags: ["#공격성_만렙", "#1v9_가능", "#하이리스크_하이리턴", "#내가_곧_게임"],
      tagsEn: ["#MaxAggression", "#1v9_Potential", "#HighRisk_HighReward", "#I_Am_The_Game"],
    },
    strat: {
      ko: "두뇌 운영형",
      en: "The Strategist",
      pair: "아지르",
      pairEn: "Azir",
      img: "Azir",
      desc: "한타보다 운영. 시야, 오브젝트, 라인 관리로 게임을 천천히 조여간다. 화려하진 않아도 이기는 그림을 그릴 줄 안다. 다만 가끔 팀원이 네 큰 그림을 못 따라온다.",
      descEn: "Macro over teamfights. You squeeze the game shut with vision, objectives, and wave management. It's not flashy, but you know how to draw up a win — even if your teammates can't always keep up with the big picture.",
      tags: ["#오브젝트_장인", "#시야_집착", "#큰그림", "#침착함"],
      tagsEn: ["#ObjectiveMaster", "#VisionObsessed", "#BigPicture", "#IceInVeins"],
    },
    tank: {
      ko: "든든한 탱커형",
      en: "The Guardian",
      pair: "오른",
      pairEn: "Ornn",
      img: "Ornn",
      desc: "가장 앞에서 몸을 던진다. 팀을 지키고, 이니시를 열고, 궂은일을 도맡는다. 스포트라이트는 딜러가 받아도, 그 판을 받친 건 너라는 걸 팀은 안다(가끔 모르지만).",
      descEn: "You throw your body in first. You protect the team, open the engage, and do all the dirty work. The carries get the spotlight, but your team knows you're the one who held the game together — most of the time, anyway.",
      tags: ["#앞라인_담당", "#이니시에이터", "#팀의_방패", "#묵묵함"],
      tagsEn: ["#FrontlineDuty", "#Initiator", "#TeamShield", "#SilentWorkhorse"],
    },
    assassin: {
      ko: "침묵의 암살자형",
      en: "The Assassin",
      pair: "제드",
      pairEn: "Zed",
      img: "Zed",
      desc: "보이지 않게 들어와 핵심을 끊어먹는다. 한 번의 각으로 한타를 터뜨리는 짜릿함이 너의 연료. 스노우볼은 최고지만, 각이 안 나오면 그림자처럼 조용해진다.",
      descEn: "You slip in unseen and delete the key target. That rush of blowing up a fight with one clean read is your fuel. Nobody snowballs harder — but when the angle isn't there, you go quiet as a shadow.",
      tags: ["#끊어먹기", "#스노우볼", "#한방의_미학", "#기습"],
      tagsEn: ["#PickOff", "#Snowball", "#OneShotArt", "#Ambush"],
    },
    support: {
      ko: "헌신의 서포터형",
      en: "The Supporter",
      pair: "쓰레쉬",
      pairEn: "Thresh",
      img: "Thresh",
      desc: "내 점수보다 팀의 승리. 와드를 박고, 궁으로 살리고, 묵묵히 케어한다. 화려한 KDA는 없어도 너 없으면 팀이 안 굴러간다. 진짜 잘하는 사람만 아는 포지션의 주인공.",
      descEn: "The team's win over your own scoreboard. You ward, you ult to save lives, you quietly babysit everyone. Your KDA isn't flashy, but the team falls apart without you — the role only real players appreciate.",
      tags: ["#팀_케어", "#보이지않는_핵심", "#이타적", "#멘탈_지킴이"],
      tagsEn: ["#TeamCare", "#InvisibleMVP", "#Selfless", "#MoraleKeeper"],
    },
    chaos: {
      ko: "즐겜 트롤형",
      en: "The Chaos",
      pair: "티모",
      pairEn: "Teemo",
      img: "Teemo",
      desc: "승패? 재미가 먼저지. 의외의 픽, 예측불가 플레이로 변수를 만든다. 상대를 빡치게 하는 데 특화. 같은 팀이면 든든하고, 적이면 제일 짜증나는 그 사람이 바로 너다.",
      descEn: "Win or lose? Fun comes first. Off-meta picks and unpredictable plays that flip the script — and tilt the enemy hard. On your team you're a blessing; on the other side, you're the most annoying player in the lobby.",
      tags: ["#즐겜_장인", "#변수_창출", "#예측불가", "#상대_도발"],
      tagsEn: ["#ForFunMaster", "#WildCard", "#Unpredictable", "#EnemyTilt"],
    },
  },
  questions: [
    {
      q: "게임 시작! 로딩 화면에서 가장 먼저 드는 생각은?",
      qEn: "Game on! What's your first thought on the loading screen?",
      answers: [
        { label: "이번 판 내가 캐리한다", labelEn: "I'm carrying this one", types: ["carry"] },
        { label: "라인 구도랑 정글 동선부터 계산", labelEn: "Mapping out lane matchups and jungle paths", types: ["strat"] },
        { label: "우리 팀 안 터지게 잘 받쳐야지", labelEn: "Gotta keep the team from falling apart", types: ["tank", "support"] },
        { label: "아무튼 재밌게 하면 됐지ㅋㅋ", labelEn: "Whatever, just here to have fun lol", types: ["chaos"] },
      ],
    },
    {
      q: "라인전에서 너의 기본 스타일은?",
      qEn: "What's your default style in lane?",
      answers: [
        { label: "솔킬 노리고 계속 압박한다", labelEn: "Constant pressure, hunting for the solo kill", types: ["carry", "assassin"] },
        { label: "CS 안 놓치고 침착하게 파밍", labelEn: "Calmly farming, not missing a single CS", types: ["strat"] },
        { label: "로밍이나 갱 호응 위주로", labelEn: "Roaming and following up on ganks", types: ["support", "tank"] },
        { label: "상대 도발하고 멘탈 흔들기", labelEn: "Baiting the enemy and tilting them", types: ["chaos"] },
      ],
    },
    {
      q: "한타가 터지기 직전, 너의 위치는?",
      qEn: "Right before a teamfight breaks out, where are you?",
      answers: [
        { label: "맨 앞, 내가 먼저 진입한다", labelEn: "Front line — I'm engaging first", types: ["tank"] },
        { label: "측면에서 각 보다가 암살", labelEn: "On the flank, waiting for the assassination angle", types: ["assassin"] },
        { label: "뒤에서 안전하게 딜 욱여넣기", labelEn: "Safely in the back, cramming in damage", types: ["carry"] },
        { label: "아군 옆에서 보호막/힐 대기", labelEn: "Next to my teammates, shields and heals ready", types: ["support"] },
      ],
    },
    {
      q: "팀원들이 계속 죽고 있다. 너의 선택은?",
      qEn: "Your teammates keep dying. What do you do?",
      answers: [
        { label: "내가 더 잘하면 됨, 캐리각 본다", labelEn: "I'll just play better — looking for the carry", types: ["carry"] },
        { label: "오브젝트로 시선 돌려 운영으로 푼다", labelEn: "Pivot to objectives and play it out with macro", types: ["strat"] },
        { label: "다이브 막으러 합류한다", labelEn: "Group up to stop the dive", types: ["tank", "support"] },
        { label: "ㅋㅋ 어쩔 수 없지, 그냥 즐긴다", labelEn: "lol nothing I can do, just gonna enjoy it", types: ["chaos"] },
      ],
    },
    {
      q: "가장 짜릿한 순간을 하나 고른다면?",
      qEn: "Pick the single most thrilling moment for you.",
      answers: [
        { label: "1v3 상황에서 역으로 따낼 때", labelEn: "Turning a 1v3 around and winning it", types: ["carry"] },
        { label: "완벽한 이니시로 한타 터뜨릴 때", labelEn: "Popping off a fight with the perfect engage", types: ["tank"] },
        { label: "안 보이게 파고들어 적 원딜 짤라먹을 때", labelEn: "Sneaking in and deleting the enemy ADC", types: ["assassin"] },
        { label: "내 궁 하나로 팀을 다 살렸을 때", labelEn: "Saving the whole team with one ult", types: ["support"] },
      ],
    },
    {
      q: "챔피언 고를 때 가장 중요한 기준은?",
      qEn: "What matters most when you pick a champion?",
      answers: [
        { label: "캐리력. 하드캐리 가능한 챔프", labelEn: "Carry potential — something that can hard carry", types: ["carry", "assassin"] },
        { label: "운영. 시야/한타에 좋은 챔프", labelEn: "Macro — strong for vision and teamfights", types: ["strat"] },
        { label: "팀 기여. 도움 되는 챔프", labelEn: "Team value — something that helps the squad", types: ["support", "tank"] },
        { label: "그냥 내가 재밌는 챔프", labelEn: "Whatever's just fun for me", types: ["chaos"] },
      ],
    },
    {
      q: "와드와 시야에 대한 너의 진심은?",
      qEn: "How do you really feel about warding and vision?",
      answers: [
        { label: "꼼꼼히 박는다. 시야가 곧 승리", labelEn: "I ward meticulously — vision wins games", types: ["strat", "support"] },
        { label: "한타각 보이는 핵심 부쉬만", labelEn: "Just the key bushes for fight angles", types: ["tank"] },
        { label: "바빠서… 서폿이 박겠지", labelEn: "Too busy… the support's got it", types: ["carry", "chaos"] },
        { label: "내가 다 박는다, 그게 내 역할", labelEn: "I ward everything — that's my job", types: ["support"] },
      ],
    },
    {
      q: "패배가 거의 확정된 분위기. 마지막 너의 자세는?",
      qEn: "The loss is all but sealed. How do you finish it out?",
      answers: [
        { label: "끝까지 캐리각 노린다", labelEn: "Still hunting for the carry till the end", types: ["carry"] },
        { label: "복기용으로 끝까지 집중", labelEn: "Locked in till the end to review later", types: ["strat"] },
        { label: "GG 치고 깔끔하게 인정", labelEn: "Type GG and take the L cleanly", types: ["tank", "support"] },
        { label: "마지막까지 변수 만들어보기ㅋㅋ", labelEn: "Trying to make something happen till the last second lol", types: ["chaos"] },
      ],
    },
    {
      q: "친구들이 말하는 '너의 플레이'는?",
      qEn: "How would your friends describe your play?",
      answers: [
        { label: "혼자 캐리하려다 자주 짐", labelEn: "Always trying to solo carry, loses a lot doing it", types: ["carry"] },
        { label: "은근 똑똑하게 잘함", labelEn: "Quietly smart and solid", types: ["strat"] },
        { label: "각 나오면 바로 끊어먹는 놈", labelEn: "The one who picks people off the moment there's an angle", types: ["assassin"] },
        { label: "맨날 서폿 시켜도 군말 없는 애", labelEn: "The one who never complains about getting put on support", types: ["support"] },
      ],
    },
  ],
};
