// Hand-authored corpus: each modern Korean sentence with a per-era version.
// Indices match ERAS in eras.ts (0 = now, 8 = Hunminjeongeum/1447).
// Note: pre-1500 forms are stylized for readability — not strict philology.

import type { EraIndex } from "./eras";

export interface CorpusEntry {
  id: string;
  themeKo: string;
  themeEn: string;
  // versions[i] is the sentence as it would (plausibly) appear in ERAS[i].
  versions: [string, string, string, string, string, string, string, string, string];
  // glossEn[i] is an English gloss for foreign players.
  glossEn: [string, string, string, string, string, string, string, string, string];
}

export const CORPUS: CorpusEntry[] = [
  {
    id: "jmt",
    themeKo: "음식 칭찬",
    themeEn: "Praising food",
    versions: [
      "이거 진짜 JMT",
      "이거 진짜 존맛탱",
      "이거 ㄹㅇ 졸라맛",
      "이것 정말 맛있슴다 ^_^",
      "이것 참 맛이 좋다",
      "이것이 참으로 맛이 좋도다",
      "이것이 진실로 맛이 됴흔지라",
      "이거시 졍히 맛이 됴ᄒᆞ도다",
      "이긔 진실로 마ᄉᆞ시 됴ᄒᆞ니라",
    ],
    glossEn: [
      "This is legit J·M·T (so good).",
      "This is straight-up jonmat-taeng.",
      "This is for-real super tasty.",
      "This really is delicious ^_^",
      "Indeed, this tastes good.",
      "Verily, the flavor is most fine.",
      "Truly, the taste is most excellent.",
      "Forsooth, the flavor is most fair.",
      "Truly, the taste is most fair (archaic).",
    ],
  },
  {
    id: "love",
    themeKo: "사랑 고백",
    themeEn: "Love confession",
    versions: [
      "나 너 좋아해",
      "나 너 좋아함 ㅇㅇ",
      "난 니가 좋아 ^^",
      "저는 당신을 좋아합니다",
      "나는 그대를 사랑합니다",
      "내 그대를 사모하노라",
      "나 그대를 사모하노라",
      "내 그ᄃᆡ를 사ᄆᆞ하ᄂᆞ니라",
      "내 그ᄃᆡᄅᆞᆯ ᄉᆞ랑ᄒᆞ노라",
    ],
    glossEn: [
      "I like you.",
      "I like you, yeah.",
      "I like you ^^",
      "I (humbly) like you.",
      "I love thee.",
      "I do yearn for thee.",
      "I do yearn for thee.",
      "I do love thee (archaic).",
      "I do love thee (Hunmin-era).",
    ],
  },
  {
    id: "tired",
    themeKo: "피곤",
    themeEn: "Exhausted",
    versions: [
      "아 개피곤",
      "아 ㅈㄴ 피곤해",
      "아 졸라 피곤해 -_-;;",
      "아 정말 피곤하군요",
      "아 참 피곤하다",
      "참으로 곤하도다",
      "심히 곤한지라",
      "심히 곤ᄒᆞ도다",
      "ᄆᆞᅀᆞᆷ이 ᄀᆞᆺ초 곤ᄒᆞ니라",
    ],
    glossEn: [
      "Ugh, dog-tired.",
      "Ugh, hella tired.",
      "Ugh, super tired -_-;;",
      "Oh, I am quite tired.",
      "Ah, truly tired.",
      "Verily, weary am I.",
      "Most weary indeed.",
      "Most weary indeed.",
      "My spirit is full weary.",
    ],
  },
  {
    id: "daebak",
    themeKo: "놀라움",
    themeEn: "Astonishment",
    versions: [
      "헐 대박",
      "헐 ㄹㅇ 대박",
      "헐 -_- 대박이다",
      "이런, 정말 놀랍군요",
      "이거 참 놀랍다",
      "참으로 놀랍도다",
      "실로 놀라온지라",
      "긔 졀로 놀라온지라",
      "긔 ᄃᆡ단히 놀라온지라",
    ],
    glossEn: [
      "Whoa, daebak.",
      "Whoa, for-real daebak.",
      "Whoa -_-, that's daebak.",
      "Goodness, how surprising.",
      "Truly astonishing.",
      "Verily, astonishing.",
      "In truth, most astonishing.",
      "It is most astonishing.",
      "It is exceedingly astonishing.",
    ],
  },
  {
    id: "annoyed",
    themeKo: "분노",
    themeEn: "Anger",
    versions: [
      "아 빡쳐",
      "아 짜증나",
      "아 짜증ㅡㅡ",
      "아 정말 짜증나는군요",
      "아 정말 분하다",
      "심히 분하도다",
      "분기탱천하노라",
      "노여움이 ᄒᆞ늘에 다ᄒᆞ도다",
      "내 ᄆᆞᅀᆞᆷ이 분ᄒᆞ도다",
    ],
    glossEn: [
      "Ugh, fuming.",
      "Ugh, annoyed.",
      "Ugh, annoyed ㅡㅡ",
      "Ugh, this is truly annoying.",
      "Ah, I am truly vexed.",
      "Verily, vexed am I.",
      "My fury rises up.",
      "Mine wrath reacheth heaven.",
      "My heart is full of wrath.",
    ],
  },
  {
    id: "overtime",
    themeKo: "야근",
    themeEn: "Working late",
    versions: [
      "야근 또야 ㅠㅠ",
      "또 야근이네 하…",
      "또 야근ㅠㅠ -_-",
      "또 야근입니다 ㅡ.ㅡ",
      "또 늦게까지 일하는구나",
      "또 밤늦도록 일하는도다",
      "또 야심토록 직무에 매이노라",
      "또 야심토록 일에 매이도다",
      "또 밤들도록 일에 ᄆᆡ이ᄂᆞ니라",
    ],
    glossEn: [
      "Overtime again ㅠㅠ",
      "Late shift again, sigh.",
      "Overtime again ㅠㅠ -_-",
      "Working late again ㅡ.ㅡ",
      "Working late once more.",
      "Toiling deep into the night again.",
      "Bound to my duties till midnight again.",
      "Bound to labor till the dead of night.",
      "Bound to labor till deep night (archaic).",
    ],
  },
  {
    id: "money",
    themeKo: "월급",
    themeEn: "Payday",
    versions: [
      "월급 들어옴 ㅎㅎ",
      "월급 받았다 ㅋㅋ",
      "월급 들어왔어 ^_^",
      "월급이 들어왔습니다",
      "월급을 받았다",
      "삯을 받았도다",
      "녹을 받자온지라",
      "녹봉을 ᄒᆞ온지라",
      "녹을 ᄒᆞ온지라",
    ],
    glossEn: [
      "Salary's in hehe.",
      "Got paid lol.",
      "Salary came in ^_^",
      "My salary has arrived.",
      "I have received my salary.",
      "I have received my wages.",
      "I have received my stipend.",
      "I have received my stipend.",
      "I have received my stipend (archaic).",
    ],
  },
  {
    id: "weather",
    themeKo: "더위",
    themeEn: "Hot weather",
    versions: [
      "아 진짜 덥다",
      "아 개더워",
      "아 졸라 더워 ㅡㅡ",
      "아 정말 덥슴다",
      "오늘 참 덥다",
      "오늘 참 덥도다",
      "금일 매우 덥은지라",
      "오ᄂᆞᆯ 심히 덥도다",
      "오ᄂᆞᆯ ᄀᆞ장 더우니라",
    ],
    glossEn: [
      "It's really hot today.",
      "It's dog-hot.",
      "It's hella hot ㅡㅡ",
      "It really is hot.",
      "It is quite hot today.",
      "Verily, today is hot.",
      "Today is most hot.",
      "Today is exceedingly hot.",
      "Today is most hot (archaic).",
    ],
  },
  {
    id: "friend",
    themeKo: "절친",
    themeEn: "Best friends",
    versions: [
      "우리 찐친임",
      "우리 절친 ㅋ",
      "우리 베프 ^^",
      "우리는 절친한 사이입니다",
      "우리는 가까운 벗이다",
      "우리는 막역한 벗이로다",
      "우리는 지기지우라",
      "우리 ᄆᆞᆨ역혼 벗이로다",
      "우리 ᄀᆞ장 갓가온 벗이니라",
    ],
    glossEn: [
      "We're real besties.",
      "We're best friends lol.",
      "We're BFFs ^^",
      "We are close friends.",
      "We are dear friends.",
      "We are bosom companions.",
      "We are friends who know one another's hearts.",
      "We are bosom companions.",
      "We are the closest of friends.",
    ],
  },
  {
    id: "tomorrow",
    themeKo: "약속",
    themeEn: "Plans tomorrow",
    versions: [
      "낼 ㄱㄱ",
      "내일 보자 ㅋ",
      "내일 만나여 ^_^",
      "내일 만나요",
      "내일 만나자",
      "내일 만나기로 하세",
      "명일에 만나기로 ᄒᆞ세",
      "명일에 ᄆᆞᆫ나기로 ᄒᆞ세",
      "ᄂᆡᆯ 만나기로 ᄒᆞ노라",
    ],
    glossEn: [
      "Tmrw let's go.",
      "See you tomorrow lol.",
      "Let's meet tomorrow ^_^",
      "Let us meet tomorrow.",
      "Let's meet tomorrow.",
      "Let us meet on the morrow.",
      "Let us meet on the morrow.",
      "Let us meet on the morrow.",
      "I propose we meet tomorrow.",
    ],
  },
  {
    id: "music",
    themeKo: "음악",
    themeEn: "Music praise",
    versions: [
      "이 노래 띵곡",
      "이 노래 갓곡 ㄹㅇ",
      "이 노래 짱이야 ^^",
      "이 곡 정말 좋습니다",
      "이 곡이 참 좋다",
      "이 곡조 참 좋도다",
      "이 가락 진실로 묘하도다",
      "긔 곡됴 졍히 묘ᄒᆞ도다",
      "긔 곡됴 ᄀᆞ장 됴ᄒᆞ니라",
    ],
    glossEn: [
      "This song's a banger.",
      "This song is god-tier, real.",
      "This song's the best ^^",
      "This piece is truly fine.",
      "This piece is quite fine.",
      "Verily, this melody is fine.",
      "This tune is truly wondrous.",
      "This tune is most wondrous.",
      "This tune is most fine (archaic).",
    ],
  },
  {
    id: "pretty",
    themeKo: "외모",
    themeEn: "Looking good",
    versions: [
      "오늘 핵예뻐",
      "오늘 짱예쁨",
      "오늘 진짜 이뻐 ^_^",
      "오늘 참 예쁘시네요",
      "오늘 참 곱다",
      "오늘 자못 곱도다",
      "오ᄂᆞᆯ 자못 고온지라",
      "오ᄂᆞᆯ ᄀᆞ장 고온지라",
      "오ᄂᆞᆯ ᄀᆞ장 고오니라",
    ],
    glossEn: [
      "You look stunning today.",
      "Super pretty today.",
      "You're really pretty today ^_^",
      "You look quite lovely today.",
      "How fair you are today.",
      "Most fair art thou today.",
      "Most fair art thou today.",
      "Most fair art thou today.",
      "Most fair art thou today (archaic).",
    ],
  },
  {
    id: "quit",
    themeKo: "퇴사 결심",
    themeEn: "Quitting resolve",
    versions: [
      "나 퇴사 박을래",
      "나 퇴사할래 ㅡㅡ",
      "저 회사 그만둘래여",
      "저 회사 그만두렵니다",
      "나는 회사를 그만두겠다",
      "내 직을 떠나리로다",
      "내 관직을 사퇴코자 ᄒᆞ노라",
      "내 직임을 ᄇᆞ리고져 ᄒᆞ노라",
      "내 직을 ᄇᆞ리고져 ᄒᆞ노라",
    ],
    glossEn: [
      "I'm quitting this job.",
      "I'm quitting ㅡㅡ",
      "I'm leaving the company.",
      "I intend to leave the company.",
      "I shall leave the company.",
      "I shall depart from my post.",
      "I wish to resign from my office.",
      "I do wish to forsake my post.",
      "I do wish to forsake my post.",
    ],
  },
  {
    id: "hello",
    themeKo: "인사",
    themeEn: "Greeting",
    versions: [
      "ㅎㅇ",
      "안녕 ㅋ",
      "안뇽~ ^^",
      "안녕하세요",
      "안녕하십니까",
      "문안하옵니다",
      "문안 드리노라",
      "ᄆᆞᆫ안 ᄃᆞ리노라",
      "긔체 평안ᄒᆞ시니이ᄭᅡ",
    ],
    glossEn: [
      "Hi.",
      "Hi, lol.",
      "Hi~ ^^",
      "Hello.",
      "How do you do.",
      "I bid you good greetings.",
      "I offer my greetings.",
      "I offer my greetings.",
      "Is your honor at peace?",
    ],
  },
  {
    id: "busy",
    themeKo: "바쁨",
    themeEn: "Being busy",
    versions: [
      "아 바빠 죽겠다",
      "아 ㅈㄴ 바빠",
      "아 졸라 바빠 -_-;;",
      "아 정말 바쁩니다",
      "참으로 바쁘다",
      "참으로 분주하도다",
      "심히 분주ᄒᆞ온지라",
      "ᄀᆞ장 분주ᄒᆞ도다",
      "ᄆᆞᅀᆞᆷ과 몸이 분주ᄒᆞ니라",
    ],
    glossEn: [
      "I'm dying of being busy.",
      "I'm hella busy.",
      "I'm super busy -_-;;",
      "I really am busy.",
      "I am truly busy.",
      "Verily, I am bustling about.",
      "I am most bustling about.",
      "I am most bustling about.",
      "Heart and body are bustling.",
    ],
  },
];

export function getEntry(id: string): CorpusEntry | undefined {
  return CORPUS.find((c) => c.id === id);
}

export function pickRandom(excludeIds: string[] = []): CorpusEntry {
  const pool = CORPUS.filter((c) => !excludeIds.includes(c.id));
  const list = pool.length > 0 ? pool : CORPUS;
  return list[Math.floor(Math.random() * list.length)];
}

export function getVersion(entry: CorpusEntry, era: EraIndex): string {
  return entry.versions[era];
}

export function getGloss(entry: CorpusEntry, era: EraIndex): string {
  return entry.glossEn[era];
}
